// Data access for the administration-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── departments ───────────────────────────────────────────────────────────────

// @table departments
export function deleteDepartmentById(id: string | number | boolean) {
  return db().from("departments").delete().eq("id", id);
}

// @table departments
export function insertDepartments(rows: object | object[]) {
  return db().from("departments").insert(rows);
}

// @table departments
export function listDepartments() {
  return db().from("departments").select("id, department_name").order("department_name");
}

// @table departments
export function listDepartmentsOrderedByDepartmentName() {
  return db()
    .from("departments")
    .select("id, department_code, department_name, description, parent_id, department_head")
    .order("department_name", { ascending: true });
}

// @table departments
export function updateDepartmentById(patch: object, id: string | number | boolean) {
  return db().from("departments").update(patch).eq("id", id);
}

// ── leave_team_capacity ───────────────────────────────────────────────────────

// @table leave_team_capacity
export function listLeaveTeamCapacity() {
  return db().from("leave_team_capacity").select("*, departments(department_name)").order("max_percent");
}

// @table leave_team_capacity
export function upsertLeaveTeamCapacity(row: object) {
  return db().from("leave_team_capacity").upsert([row], { onConflict: "department_id" });
}

// ── leave_types ───────────────────────────────────────────────────────────────

// @table leave_types
export function deleteLeaveTypeById(id: string | number | boolean) {
  return db().from("leave_types").delete().eq("id", id);
}

// @table leave_types
export function insertLeaveTypes(rows: object | object[]) {
  return db().from("leave_types").insert(rows);
}

// @table leave_types
export function listLeaveTypes() {
  return db().from("leave_types").select("*").order("leave_name");
}

// @table leave_types
export function updateLeaveTypeById(patch: object, id: string | number | boolean) {
  return db().from("leave_types").update(patch).eq("id", id);
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function countProfilesByDepartmentId(departmentId: string | number | boolean) {
  return db().from("profiles").select("id", { count: "exact", head: true }).eq("department_id", departmentId);
}

// @table profiles
export function getProfileById(id: string | number | boolean) {
  return db().from("profiles").select("role").eq("id", id).maybeSingle();
}

// @table profiles
export function listProfiles() {
  return db().from("profiles").select("id, full_name").order("full_name", { ascending: true });
}

// ── user_roles ────────────────────────────────────────────────────────────────

// @table user_roles
export function listUserRolesByUserId(userId: string | number | boolean) {
  return db().from("user_roles").select("role_code").eq("user_id", userId);
}
