// Data access for the dashboard-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── contract_register ─────────────────────────────────────────────────────────

// @table contract_register
export function getContractRegisterByProjectIdWithStatusActive(projectId: string | number | boolean) {
  return db()
    .from("contract_register")
    .select("contract_no, party_name, contract_value, status")
    .eq("project_id", projectId)
    .eq("status", "active")
    .limit(1)
    .maybeSingle();
}

// ── departments ───────────────────────────────────────────────────────────────

// @table departments
export function listDepartmentsByDepartmentHead(departmentHead: string | number | boolean) {
  return db().from("departments").select("id").eq("department_head", departmentHead);
}

// ── documents ─────────────────────────────────────────────────────────────────

// @table documents
export function listDocuments() {
  return db().from("documents").select("status");
}

// @table documents
export function listDocumentsOrderedByCreatedAt() {
  return db()
    .from("documents")
    .select("id, document_number, title, status, created_at")
    .order("created_at", { ascending: false })
    .limit(10);
}

// ── hse_incidents ─────────────────────────────────────────────────────────────

// @table hse_incidents
export function countHseIncidents() {
  return db().from("hse_incidents").select("id", { count: "exact", head: true });
}

// ── leave_requests ────────────────────────────────────────────────────────────

// @table leave_requests
export function countLeaveRequestsByEmployeeIdWithStatusSubmitted(employeeId: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select("id", { count: "exact", head: true })
    .eq("employee_id", employeeId)
    .eq("status", "submitted");
}

// @table leave_requests
export function listLeaveRequestsByFilterWithStatusSubmittedPendingCancellation(filter: string) {
  return db()
    .from("leave_requests")
    .select("approver_1_id, approver_1_status, approver_2_id, approver_2_status, status")
    .or(filter)
    .in("status", ["submitted", "pending_cancellation"]);
}

// ── overtime_approvals ────────────────────────────────────────────────────────

// @table overtime_approvals
export function countOvertimeApprovalsByApproverIdWithStatusPending(approverId: string | number | boolean) {
  return db()
    .from("overtime_approvals")
    .select("id", { count: "exact", head: true })
    .eq("approver_id", approverId)
    .eq("status", "pending");
}

// ── overtime_notifications ────────────────────────────────────────────────────

// @table overtime_notifications
export function countOvertimeNotificationsByRecipientIdWithIsRead(recipientId: string | number | boolean) {
  return db()
    .from("overtime_notifications")
    .select("id", { count: "exact", head: true })
    .eq("recipient_id", recipientId)
    .eq("is_read", false);
}

// ── procurement_pos ───────────────────────────────────────────────────────────

// @table procurement_pos
export function listProcurementPos() {
  return db().from("procurement_pos").select("status");
}

// ── procurement_prs ───────────────────────────────────────────────────────────

// @table procurement_prs
export function listProcurementPrs() {
  return db().from("procurement_prs").select("approval_status");
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function getProfileById(id: string | number | boolean, columns: string) {
  return db().from("profiles").select(columns as "*").eq("id", id).single();
}

// ── project_precontract_details ───────────────────────────────────────────────

// @table project_precontract_details
export function getProjectPrecontractDetailByProjectId(projectId: string | number | boolean) {
  return db().from("project_precontract_details").select("*").eq("project_id", projectId).single();
}

// ── projects ──────────────────────────────────────────────────────────────────

// @table projects
export function countProjectsWithProjectTypeTender() {
  return db().from("projects").select("id", { count: "exact", head: true }).eq("project_type", "tender");
}

// @table projects
export function countProjectsWithProjectTypeTenderOfId() {
  return db().from("projects").select("id", { count: "exact", head: true }).neq("project_type", "tender");
}

// @table projects
export function listProjects() {
  return db()
    .from("projects")
    .select("id, project_code, project_name, project_type, project_status, progress_percentage, contract_type")
    .order("project_name", { ascending: true });
}

// ── task_alerts ───────────────────────────────────────────────────────────────

// @table task_alerts
export function countTaskAlertsByRecipientIdWithReadAt(recipientId: string | number | boolean) {
  return db()
    .from("task_alerts")
    .select("id", { count: "exact", head: true })
    .eq("recipient_id", recipientId)
    .is("read_at", null);
}

// @table task_alerts
export function listTaskAlertsByRecipientId(recipientId: string | number | boolean) {
  return db()
    .from("task_alerts")
    .select("*")
    .eq("recipient_id", recipientId)
    .order("created_at", { ascending: false })
    .limit(20);
}

// @table task_alerts
export function updateTaskAlertByIdAndRecipientId(patch: object, id: string | number | boolean, recipientId: string | number | boolean) {
  return db().from("task_alerts").update(patch).eq("id", id).eq("recipient_id", recipientId);
}

// @table task_alerts
export function updateTaskAlertsByIdsAndRecipientId(patch: object, ids: readonly (string | number)[], recipientId: string | number | boolean) {
  return db().from("task_alerts").update(patch).in("id", ids).eq("recipient_id", recipientId);
}

// @table task_alerts
export function updateTaskAlertsByRecipientIdWithReadAt(patch: object, recipientId: string | number | boolean) {
  return db().from("task_alerts").update(patch).eq("recipient_id", recipientId).is("read_at", null);
}

// ── tender_boq_items ──────────────────────────────────────────────────────────

// @table tender_boq_items
export function countTenderBoqItemsByTenderId(tenderId: string | number | boolean) {
  return db().from("tender_boq_items").select("id", { count: "exact", head: true }).eq("tender_id", tenderId);
}

// ── tender_preliminaries_items ────────────────────────────────────────────────

// @table tender_preliminaries_items
export function countTenderPreliminariesItemsByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_preliminaries_items")
    .select("id", { count: "exact", head: true })
    .eq("tender_id", tenderId);
}

// ── tender_risk_items ─────────────────────────────────────────────────────────

// @table tender_risk_items
export function listTenderRiskItemsByTenderId(tenderId: string | number | boolean) {
  return db().from("tender_risk_items").select("risk_score").eq("tender_id", tenderId);
}

// ── tender_sub_quotes ─────────────────────────────────────────────────────────

// @table tender_sub_quotes
export function countTenderSubQuotesByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_sub_quotes")
    .select("id", { count: "exact", head: true })
    .eq("tender_id", tenderId);
}

// ── user_roles ────────────────────────────────────────────────────────────────

// @table user_roles
export function listUserRolesByUserId(userId: string | number | boolean) {
  return db().from("user_roles").select("role_code").eq("user_id", userId);
}

// ── wbs_tasks ─────────────────────────────────────────────────────────────────

// @table wbs_tasks
export function countWbsTasksByDepartmentIdsWithCrossDeptStatusRequested(departmentIds: readonly (string | number)[]) {
  return db()
    .from("wbs_tasks")
    .select("id", { count: "exact", head: true })
    .in("department_id", departmentIds)
    .eq("cross_dept_status", "requested");
}

// @table wbs_tasks
export function listWbsTasks() {
  return db().from("wbs_tasks").select("status");
}

// @table wbs_tasks
export function listWbsTasksByProjectId(projectId: string | number | boolean) {
  return db()
    .from("wbs_tasks")
    .select("id, task_code, task_name, status, progress, priority, discipline, start_date, end_date, delay_status, owner_name")
    .eq("project_id", projectId)
    .order("end_date", { ascending: true, nullsFirst: false });
}
