// Data access for the qs-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── bid_evaluation_scores ─────────────────────────────────────────────────────

// @table bid_evaluation_scores
export function getBidEvaluationScoreByEvaluationIdAndSubmissionIdAndCriterionName(evaluationId: string | number | boolean, submissionId: string | number | boolean, criterionName: string | number | boolean) {
  return db()
    .from("bid_evaluation_scores")
    .select("id")
    .eq("evaluation_id", evaluationId)
    .eq("submission_id", submissionId)
    .eq("criterion_name", criterionName)
    .maybeSingle();
}

// @table bid_evaluation_scores
export function insertBidEvaluationScore(row: object) {
  return db().from("bid_evaluation_scores").insert([row]);
}

// @table bid_evaluation_scores
export function listBidEvaluationScoresByEvaluationId(evaluationId: string | number | boolean) {
  return db().from("bid_evaluation_scores").select("*").eq("evaluation_id", evaluationId);
}

// @table bid_evaluation_scores
export function updateBidEvaluationScoreById(patch: object, id: string | number | boolean) {
  return db().from("bid_evaluation_scores").update(patch).eq("id", id);
}

// ── bid_evaluations ───────────────────────────────────────────────────────────

// @table bid_evaluations
export function insertBidEvaluation(row: object) {
  return db().from("bid_evaluations").insert([row]);
}

// @table bid_evaluations
export function listBidEvaluationsByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("bid_evaluations")
    .select("*")
    .eq("tender_id", tenderId)
    .order("created_at", { ascending: false });
}

// @table bid_evaluations
export function updateBidEvaluationById(patch: object, id: string | number | boolean) {
  return db().from("bid_evaluations").update(patch).eq("id", id);
}

// ── budget_codes ──────────────────────────────────────────────────────────────

// @table budget_codes
export function listBudgetCodesWithIsActive() {
  return db().from("budget_codes").select("id, code, description").eq("is_active", true).order("code");
}

// @table budget_codes
export function listBudgetCodesWithIsActiveOrderedBySortOrder() {
  return db().from("budget_codes").select("id, code, description").eq("is_active", true).order("sort_order");
}

// ── contract_correspondence ───────────────────────────────────────────────────

// @table contract_correspondence
export function deleteContractCorrespondenceById(id: string | number | boolean) {
  return db().from("contract_correspondence").delete().eq("id", id);
}

// @table contract_correspondence
export function getContractCorrespondenceById(id: string | number | boolean) {
  return db()
    .from("contract_correspondence")
    .select("*, contract_register(contract_no, title)")
    .eq("id", id)
    .single();
}

// @table contract_correspondence
export function insertContractCorrespondence(row: object) {
  return db().from("contract_correspondence").insert([row]);
}

// @table contract_correspondence
export function listContractCorrespondence() {
  return db()
    .from("contract_correspondence")
    .select("*, contract_register!inner(project_id)")
    .order("correspondence_date", { ascending: false });
}

// @table contract_correspondence
export function updateContractCorrespondenceById(patch: object, id: string | number | boolean) {
  return db().from("contract_correspondence").update(patch).eq("id", id);
}

// ── contract_employer_instructions ────────────────────────────────────────────

// @table contract_employer_instructions
export function deleteContractEmployerInstructionById(id: string | number | boolean) {
  return db().from("contract_employer_instructions").delete().eq("id", id);
}

// @table contract_employer_instructions
export function getContractEmployerInstructionById(id: string | number | boolean) {
  return db()
    .from("contract_employer_instructions")
    .select("*, contract_register(contract_no, title)")
    .eq("id", id)
    .single();
}

// @table contract_employer_instructions
export function insertContractEmployerInstruction(row: object) {
  return db().from("contract_employer_instructions").insert([row]);
}

// @table contract_employer_instructions
export function listContractEmployerInstructions() {
  return db()
    .from("contract_employer_instructions")
    .select("*, contract_register!inner(project_id)")
    .order("instruction_date", { ascending: false });
}

// @table contract_employer_instructions
export function updateContractEmployerInstructionById(patch: object, id: string | number | boolean) {
  return db().from("contract_employer_instructions").update(patch).eq("id", id);
}

// ── contract_register ─────────────────────────────────────────────────────────

// @table contract_register
export function countContractRegister() {
  return db().from("contract_register").select("id", { count: "exact", head: true });
}

// @table contract_register
export function countContractRegisterWithStatusActive() {
  return db().from("contract_register").select("id", { count: "exact", head: true }).eq("status", "active");
}

// @table contract_register
export function deleteContractRegisterById(id: string | number | boolean) {
  return db().from("contract_register").delete().eq("id", id);
}

// @table contract_register
export function getContractRegisterById(id: string | number | boolean) {
  return db().from("contract_register").select("*, projects(project_name)").eq("id", id).single();
}

// @table contract_register
export function insertContractRegister(row: object) {
  return db().from("contract_register").insert([row]);
}

// @table contract_register
export function listContractRegister(columns: string) {
  return db().from("contract_register").select(columns as "*");
}

// @table contract_register
export function listContractRegisterOrderedByCreatedAt() {
  return db().from("contract_register").select("*").order("created_at", { ascending: false });
}

// @table contract_register
export function updateContractRegisterById(patch: object, id: string | number | boolean) {
  return db().from("contract_register").update(patch).eq("id", id);
}

// ── contractual_notices ───────────────────────────────────────────────────────

// @table contractual_notices
export function countContractualNotices() {
  return db().from("contractual_notices").select("id", { count: "exact", head: true });
}

// @table contractual_notices
export function countContractualNoticesByDeadlineDateBeforeWithStatusPending(deadlineDateBefore: string | number | boolean) {
  return db()
    .from("contractual_notices")
    .select("id", { count: "exact", head: true })
    .eq("status", "pending")
    .lt("deadline_date", deadlineDateBefore);
}

// @table contractual_notices
export function deleteContractualNoticeById(id: string | number | boolean) {
  return db().from("contractual_notices").delete().eq("id", id);
}

// @table contractual_notices
export function getContractualNoticeById(id: string | number | boolean) {
  return db()
    .from("contractual_notices")
    .select("*, contract_register(contract_no, title)")
    .eq("id", id)
    .single();
}

// @table contractual_notices
export function insertContractualNotice(row: object) {
  return db().from("contractual_notices").insert([row]);
}

// @table contractual_notices
export function listContractualNotices() {
  return db()
    .from("contractual_notices")
    .select("*, contract_register!inner(project_id)")
    .order("deadline_date", { ascending: true });
}

// @table contractual_notices
export function updateContractualNoticeById(patch: object, id: string | number | boolean) {
  return db().from("contractual_notices").update(patch).eq("id", id);
}

// ── dwl_assemblies ────────────────────────────────────────────────────────────

// @table dwl_assemblies
export function deleteDwlAssemblyByIdReturning(id: string | number | boolean) {
  return db().from("dwl_assemblies").delete().eq("id", id).select("id");
}

// @table dwl_assemblies
export function insertDwlAssembliesReturning(rows: object | object[]) {
  return db().from("dwl_assemblies").insert(rows).select("id").single();
}

// @table dwl_assemblies
export function insertDwlAssemblyReturning(row: object) {
  return db().from("dwl_assemblies").insert([row]).select("id").single();
}

// @table dwl_assemblies
export function listDwlAssemblies() {
  return db()
    .from("dwl_assemblies")
    .select("id, tenant_id, code, element_group, description, unit, measurement_rule, is_active, created_by, created_at")
    .order("code");
}

// @table dwl_assemblies
export function listDwlAssembliesByCode(code: string) {
  return db().from("dwl_assemblies").select("code").ilike("code", code);
}

// @table dwl_assemblies
export function listDwlAssembliesOfIdAndCode() {
  return db().from("dwl_assemblies").select("id, code");
}

// @table dwl_assemblies
export function listDwlAssembliesWithIsActive() {
  return db()
    .from("dwl_assemblies")
    .select("id, tenant_id, code, element_group, description, unit, measurement_rule, is_active, created_by, created_at")
    .eq("is_active", true)
    .order("code");
}

// @table dwl_assemblies
export function updateDwlAssemblyById(patch: object, id: string | number | boolean) {
  return db().from("dwl_assemblies").update(patch).eq("id", id);
}

// ── dwl_assembly_costing ──────────────────────────────────────────────────────

// @table dwl_assembly_costing
export function updateDwlAssemblyCostingByAssemblyId(patch: object, assemblyId: string | number | boolean) {
  return db().from("dwl_assembly_costing").update(patch).eq("assembly_id", assemblyId);
}

// @table dwl_assembly_costing
export function upsertDwlAssemblyCosting(row: object) {
  return db().from("dwl_assembly_costing").upsert([row], { onConflict: "assembly_id" });
}

// ── dwl_assembly_crew ─────────────────────────────────────────────────────────

// @table dwl_assembly_crew
export function deleteDwlAssemblyCrewById(id: string | number | boolean) {
  return db().from("dwl_assembly_crew").delete().eq("id", id);
}

// @table dwl_assembly_crew
export function listDwlAssemblyCrewByAssemblyId(assemblyId: string | number | boolean) {
  return db()
    .from("dwl_assembly_crew")
    .select("id, assembly_id, resource_id, role_label, quantity, sort_order, description, benchmark_note")
    .eq("assembly_id", assemblyId)
    .order("sort_order");
}

// ── dwl_assembly_equipment ────────────────────────────────────────────────────

// @table dwl_assembly_equipment
export function deleteDwlAssemblyEquipmentById(id: string | number | boolean) {
  return db().from("dwl_assembly_equipment").delete().eq("id", id);
}

// @table dwl_assembly_equipment
export function listDwlAssemblyEquipmentByAssemblyId(assemblyId: string | number | boolean) {
  return db()
    .from("dwl_assembly_equipment")
    .select("id, assembly_id, resource_id, role_label, quantity, sort_order, description")
    .eq("assembly_id", assemblyId)
    .order("sort_order");
}

// ── dwl_assembly_items ────────────────────────────────────────────────────────

// @table dwl_assembly_items
export function deleteDwlAssemblyItemById(id: string | number | boolean) {
  return db().from("dwl_assembly_items").delete().eq("id", id);
}

// @table dwl_assembly_items
export function insertDwlAssemblyItem(row: object) {
  return db().from("dwl_assembly_items").insert([row]);
}

// @table dwl_assembly_items
export function insertDwlAssemblyItems(rows: object | object[]) {
  return db().from("dwl_assembly_items").insert(rows);
}

// @table dwl_assembly_items
export function listDwlAssemblyItemsByAssemblyId(assemblyId: string | number | boolean, columns: string) {
  return db()
    .from("dwl_assembly_items")
    .select(columns as "*")
    .eq("assembly_id", assemblyId)
    .order("sort_order");
}

// @table dwl_assembly_items
export function updateDwlAssemblyItemById(patch: object, id: string | number | boolean) {
  return db().from("dwl_assembly_items").update(patch).eq("id", id);
}

// ── dwl_assembly_layer_materials ──────────────────────────────────────────────

// @table dwl_assembly_layer_materials
export function deleteDwlAssemblyLayerMaterialsByLayerId(layerId: string | number | boolean) {
  return db().from("dwl_assembly_layer_materials").delete().eq("layer_id", layerId);
}

// @table dwl_assembly_layer_materials
export function insertDwlAssemblyLayerMaterials(rows: object | object[]) {
  return db().from("dwl_assembly_layer_materials").insert(rows);
}

// @table dwl_assembly_layer_materials
export function listDwlAssemblyLayerMaterialsByLayerIds(layerIds: readonly (string | number)[]) {
  return db()
    .from("dwl_assembly_layer_materials")
    .select("id, layer_id, resource_id, sort_order")
    .in("layer_id", layerIds);
}

// ── dwl_assembly_layer_specs ──────────────────────────────────────────────────

// @table dwl_assembly_layer_specs
export function deleteDwlAssemblyLayerSpecsByLayerId(layerId: string | number | boolean) {
  return db().from("dwl_assembly_layer_specs").delete().eq("layer_id", layerId);
}

// @table dwl_assembly_layer_specs
export function insertDwlAssemblyLayerSpecs(rows: object | object[]) {
  return db().from("dwl_assembly_layer_specs").insert(rows);
}

// @table dwl_assembly_layer_specs
export function listDwlAssemblyLayerSpecsByLayerIds(layerIds: readonly (string | number)[]) {
  return db()
    .from("dwl_assembly_layer_specs")
    .select("id, layer_id, sort_order, spec_label, spec_value")
    .in("layer_id", layerIds)
    .order("sort_order");
}

// ── dwl_assembly_layers ───────────────────────────────────────────────────────

// @table dwl_assembly_layers
export function deleteDwlAssemblyLayerById(id: string | number | boolean) {
  return db().from("dwl_assembly_layers").delete().eq("id", id);
}

// @table dwl_assembly_layers
export function insertDwlAssemblyLayersReturning(rows: object | object[]) {
  return db().from("dwl_assembly_layers").insert(rows).select("id").single();
}

// @table dwl_assembly_layers
export function listDwlAssemblyLayersByAssemblyId(assemblyId: string | number | boolean) {
  return db()
    .from("dwl_assembly_layers")
    .select("id, assembly_id, sort_order, layer_name, material_label, thickness_mm, color_hex")
    .eq("assembly_id", assemblyId)
    .order("sort_order");
}

// @table dwl_assembly_layers
export function updateDwlAssemblyLayerById(patch: object, id: string | number | boolean) {
  return db().from("dwl_assembly_layers").update(patch).eq("id", id);
}

// ── dwl_assembly_specs ────────────────────────────────────────────────────────

// @table dwl_assembly_specs
export function deleteDwlAssemblySpecsByAssemblyIdAndSection(assemblyId: string | number | boolean, section: string | number | boolean) {
  return db().from("dwl_assembly_specs").delete().eq("assembly_id", assemblyId).eq("section", section);
}

// @table dwl_assembly_specs
export function insertDwlAssemblySpecs(rows: object | object[]) {
  return db().from("dwl_assembly_specs").insert(rows);
}

// @table dwl_assembly_specs
export function listDwlAssemblySpecsByAssemblyId(assemblyId: string | number | boolean) {
  return db()
    .from("dwl_assembly_specs")
    .select("id, assembly_id, section, sort_order, spec_label, spec_value")
    .eq("assembly_id", assemblyId)
    .order("sort_order");
}

// ── dwl_equipment_attributes ──────────────────────────────────────────────────

// @table dwl_equipment_attributes
export function insertDwlEquipmentAttribute(row: object) {
  return db().from("dwl_equipment_attributes").insert([row]);
}

// @table dwl_equipment_attributes
export function upsertDwlEquipmentAttribute(row: object) {
  return db().from("dwl_equipment_attributes").upsert([row], { onConflict: "resource_id" });
}

// ── dwl_labor_rate_attributes ─────────────────────────────────────────────────

// @table dwl_labor_rate_attributes
export function insertDwlLaborRateAttribute(row: object) {
  return db().from("dwl_labor_rate_attributes").insert([row]);
}

// @table dwl_labor_rate_attributes
export function upsertDwlLaborRateAttribute(row: object) {
  return db().from("dwl_labor_rate_attributes").upsert([row], { onConflict: "resource_id" });
}

// @table dwl_labor_rate_attributes
export function upsertDwlLaborRateAttributes(rows: object | object[]) {
  return db().from("dwl_labor_rate_attributes").upsert(rows, { onConflict: "resource_id" });
}

// ── dwl_material_attributes ───────────────────────────────────────────────────

// @table dwl_material_attributes
export function insertDwlMaterialAttribute(row: object) {
  return db().from("dwl_material_attributes").insert([row]);
}

// @table dwl_material_attributes
export function listDwlMaterialAttributes(columns: string) {
  return db().from("dwl_material_attributes").select(columns as "*");
}

// @table dwl_material_attributes
export function updateDwlMaterialAttributesByResourceId(patch: object, resourceId: string | number | boolean) {
  return db().from("dwl_material_attributes").update(patch).eq("resource_id", resourceId);
}

// @table dwl_material_attributes
export function updateDwlMaterialAttributesByResourceIds(patch: object, resourceIds: readonly (string | number)[]) {
  return db().from("dwl_material_attributes").update(patch).in("resource_id", resourceIds);
}

// ── dwl_material_categories ───────────────────────────────────────────────────

// @table dwl_material_categories
export function insertDwlMaterialCategories(rows: object | object[]) {
  return db().from("dwl_material_categories").insert(rows);
}

// @table dwl_material_categories
export function insertDwlMaterialCategory(row: object) {
  return db().from("dwl_material_categories").insert([row]);
}

// @table dwl_material_categories
export function listDwlMaterialCategories() {
  return db().from("dwl_material_categories").select("id, code, name");
}

// @table dwl_material_categories
export function listDwlMaterialCategoriesOrderedBySortOrderAndName(columns: string) {
  return db().from("dwl_material_categories").select(columns as "*").order("sort_order").order("name");
}

// @table dwl_material_categories
export function listDwlMaterialCategoriesWithIsActive() {
  return db()
    .from("dwl_material_categories")
    .select("id, group_name, name, code, specific_element, discipline, cost_code_prefix, color_tag, description, sort_order, is_active, created_at, updated_at")
    .eq("is_active", true)
    .order("sort_order");
}

// @table dwl_material_categories
export function listDwlMaterialCategoriesWithIsActiveOrderedBySortOrderAndName() {
  return db()
    .from("dwl_material_categories")
    .select("id, group_name, name, code, sort_order, is_active, created_at, updated_at")
    .eq("is_active", true)
    .order("sort_order")
    .order("name");
}

// @table dwl_material_categories
export function updateDwlMaterialCategoryById(patch: object, id: string | number | boolean) {
  return db().from("dwl_material_categories").update(patch).eq("id", id);
}

// ── dwl_material_division_sections ────────────────────────────────────────────

// @table dwl_material_division_sections
export function deleteDwlMaterialDivisionSectionById(id: string | number | boolean) {
  return db().from("dwl_material_division_sections").delete().eq("id", id);
}

// @table dwl_material_division_sections
export function insertDwlMaterialDivisionSection(row: object) {
  return db().from("dwl_material_division_sections").insert([row]);
}

// @table dwl_material_division_sections
export function listDwlMaterialDivisionSectionsOrderedBySortOrderAndCode() {
  return db()
    .from("dwl_material_division_sections")
    .select("id, division_code, code, name, parent_code, sort_order")
    .order("sort_order")
    .order("code");
}

// ── dwl_material_divisions ────────────────────────────────────────────────────

// @table dwl_material_divisions
export function insertDwlMaterialDivision(row: object) {
  return db().from("dwl_material_divisions").insert([row]);
}

// @table dwl_material_divisions
export function listDwlMaterialDivisionsOrderedBySortOrderAndCode() {
  return db()
    .from("dwl_material_divisions")
    .select("code, name, group_name, sort_order, is_active")
    .order("sort_order")
    .order("code");
}

// @table dwl_material_divisions
export function updateDwlMaterialDivisionByCode(patch: object, code: string) {
  return db().from("dwl_material_divisions").update(patch).eq("code", code);
}

// ── dwl_material_photos ───────────────────────────────────────────────────────

// @table dwl_material_photos
export function deleteDwlMaterialPhotoById(id: string | number | boolean) {
  return db().from("dwl_material_photos").delete().eq("id", id);
}

// @table dwl_material_photos
export function insertDwlMaterialPhoto(row: object) {
  return db().from("dwl_material_photos").insert([row]);
}

// @table dwl_material_photos
export function listDwlMaterialPhotosByResourceId(resourceId: string | number | boolean) {
  return db()
    .from("dwl_material_photos")
    .select("id, tenant_id, resource_id, storage_path, caption, created_by, created_at")
    .eq("resource_id", resourceId)
    .order("created_at");
}

// @table dwl_material_photos
export function listDwlMaterialPhotosByResourceIds(resourceIds: readonly (string | number)[]) {
  return db()
    .from("dwl_material_photos")
    .select("resource_id, storage_path, created_at")
    .in("resource_id", resourceIds)
    .order("created_at");
}

// ── dwl_material_spec_revisions ───────────────────────────────────────────────

// @table dwl_material_spec_revisions
export function insertDwlMaterialSpecRevision(row: object) {
  return db().from("dwl_material_spec_revisions").insert([row]);
}

// @table dwl_material_spec_revisions
export function listDwlMaterialSpecRevisions() {
  return db().from("dwl_material_spec_revisions").select("spec_id, revision_no");
}

// @table dwl_material_spec_revisions
export function listDwlMaterialSpecRevisionsBySpecIds(specIds: readonly (string | number)[]) {
  return db()
    .from("dwl_material_spec_revisions")
    .select("*")
    .in("spec_id", specIds)
    .order("effective_date", { ascending: false })
    .order("created_at", { ascending: false });
}

// ── dwl_material_specs ────────────────────────────────────────────────────────

// @table dwl_material_specs
export function insertDwlMaterialSpecReturning(row: object) {
  return db().from("dwl_material_specs").insert([row]).select("id").single();
}

// @table dwl_material_specs
export function listDwlMaterialSpecs() {
  return db().from("dwl_material_specs").select("id, spec_code");
}

// @table dwl_material_specs
export function listDwlMaterialSpecsByResourceId(resourceId: string | number | boolean) {
  return db().from("dwl_material_specs").select("*").eq("resource_id", resourceId).order("spec_code");
}

// ── dwl_model_factors ─────────────────────────────────────────────────────────

// @table dwl_model_factors
export function deleteDwlModelFactorById(id: string | number | boolean) {
  return db().from("dwl_model_factors").delete().eq("id", id);
}

// @table dwl_model_factors
export function insertDwlModelFactors(rows: object | object[]) {
  return db().from("dwl_model_factors").insert(rows);
}

// @table dwl_model_factors
export function listDwlModelFactors() {
  return db().from("dwl_model_factors").select("model_id");
}

// @table dwl_model_factors
export function listDwlModelFactorsByModelId(modelId: string | number | boolean) {
  return db()
    .from("dwl_model_factors")
    .select("id, tenant_id, model_id, assembly_id, driver, factor, basis_note, dwl_assemblies!inner(code, element_group, description, unit)")
    .eq("model_id", modelId)
    .order("basis_note");
}

// @table dwl_model_factors
export function updateDwlModelFactorById(patch: object, id: string | number | boolean) {
  return db().from("dwl_model_factors").update(patch).eq("id", id);
}

// ── dwl_price_submissions ─────────────────────────────────────────────────────

// @table dwl_price_submissions
export function insertDwlPriceSubmission(row: object) {
  return db().from("dwl_price_submissions").insert([row]);
}

// @table dwl_price_submissions
export function insertDwlPriceSubmissionReturning(row: object) {
  return db().from("dwl_price_submissions").insert([row]).select("id").single();
}

// @table dwl_price_submissions
export function listDwlPriceSubmissions() {
  return db().from("dwl_price_submissions").select("resource_id, valid_from, unit_price, notes");
}

// ── dwl_project_snapshots ─────────────────────────────────────────────────────

// @table dwl_project_snapshots
export function insertDwlProjectSnapshot(row: object) {
  return db().from("dwl_project_snapshots").insert([row]);
}

// @table dwl_project_snapshots
export function listDwlProjectSnapshotsByProjectId(projectId: string | number | boolean) {
  return db()
    .from("dwl_project_snapshots")
    .select("id, tenant_id, project_id, label, snapped_at, snapped_by, payload")
    .eq("project_id", projectId)
    .order("snapped_at", { ascending: false });
}

// ── dwl_projects ──────────────────────────────────────────────────────────────

// @table dwl_projects
export function insertDwlProjectsReturning(rows: object | object[]) {
  return db().from("dwl_projects").insert(rows).select("id").single();
}

// @table dwl_projects
export function listDwlProjects() {
  return db()
    .from("dwl_projects")
    .select("id, tenant_id, name, model_id, gfa, footprint, storeys, status, created_at")
    .order("created_at", { ascending: false });
}

// @table dwl_projects
export function updateDwlProjectById(patch: object, id: string | number | boolean) {
  return db().from("dwl_projects").update(patch).eq("id", id);
}

// ── dwl_quantity_models ───────────────────────────────────────────────────────

// @table dwl_quantity_models
export function insertDwlQuantityModelsReturning(rows: object | object[]) {
  return db().from("dwl_quantity_models").insert(rows).select("id").single();
}

// @table dwl_quantity_models
export function listDwlQuantityModels() {
  return db()
    .from("dwl_quantity_models")
    .select("id, tenant_id, code, building_type, description, basis_note, is_active, created_at")
    .order("code");
}

// ── dwl_quotation_items ───────────────────────────────────────────────────────

// @table dwl_quotation_items
export function insertDwlQuotationItem(row: object) {
  return db().from("dwl_quotation_items").insert([row]);
}

// @table dwl_quotation_items
export function listDwlQuotationItems() {
  return db().from("dwl_quotation_items").select("quotation_id, line_no");
}

// ── dwl_quotations ────────────────────────────────────────────────────────────

// @table dwl_quotations
export function insertDwlQuotationReturning(row: object) {
  return db().from("dwl_quotations").insert([row]).select("id").single();
}

// @table dwl_quotations
export function listDwlQuotations() {
  return db().from("dwl_quotations").select("id, quote_no");
}

// ── dwl_resource_prices ───────────────────────────────────────────────────────

// @table dwl_resource_prices
export function insertDwlResourcePrice(row: object) {
  return db().from("dwl_resource_prices").insert([row]);
}

// @table dwl_resource_prices
export function insertDwlResourcePrices(rows: object | object[]) {
  return db().from("dwl_resource_prices").insert(rows);
}

// @table dwl_resource_prices
export function listDwlResourcePrices() {
  return db().from("dwl_resource_prices").select("resource_id, valid_from, unit_price, notes");
}

// @table dwl_resource_prices
export function listDwlResourcePricesByResourceId(columns: string, resourceId: string | number | boolean) {
  return db()
    .from("dwl_resource_prices")
    .select(columns)
    .eq("resource_id", resourceId)
    .order("valid_from", { ascending: false })
    .order("created_at", { ascending: false });
}

// @table dwl_resource_prices
export function listDwlResourcePricesByResourceIds(resourceIds: readonly (string | number)[]) {
  return db()
    .from("dwl_resource_prices")
    .select("resource_id, unit_price, valid_from")
    .in("resource_id", resourceIds)
    .order("valid_from");
}

// @table dwl_resource_prices
export function listDwlResourcePricesOrderedByValidFrom(columns: string) {
  return db().from("dwl_resource_prices").select(columns).order("valid_from", { ascending: true });
}

// ── dwl_resources ─────────────────────────────────────────────────────────────

// @table dwl_resources
export function countDwlResourcesWithCategoryMaterial() {
  return db().from("dwl_resources").select("id", { count: "exact", head: true }).eq("category", "material");
}

// @table dwl_resources
export function deleteDwlResourceById(id: string | number | boolean) {
  return db().from("dwl_resources").delete().eq("id", id);
}

// @table dwl_resources
export function deleteDwlResourceByIdReturning(id: string | number | boolean) {
  return db().from("dwl_resources").delete().eq("id", id).select("id");
}

// @table dwl_resources
export function insertDwlResourceReturning(row: object) {
  return db().from("dwl_resources").insert([row]).select("id").single();
}

// @table dwl_resources
export function insertDwlResources(rows: object | object[]) {
  return db().from("dwl_resources").insert(rows);
}

// @table dwl_resources
export function listDwlResources() {
  return db().from("dwl_resources").select("id, code");
}

// @table dwl_resources
export function listDwlResourcesByCategoryWithIsActive(category: string | number | boolean) {
  return db()
    .from("dwl_resources")
    .select("id, tenant_id, code, category, description, unit, spec_reference, is_active, created_by, created_at, updated_at")
    .eq("is_active", true)
    .eq("category", category)
    .order("code");
}

// @table dwl_resources
export function listDwlResourcesByCodeWithCategoryMaterial(code: string) {
  return db().from("dwl_resources").select("code").eq("category", "material").ilike("code", code);
}

// @table dwl_resources
export function listDwlResourcesWithCategoryLabor() {
  return db().from("dwl_resources").select("id, code").eq("category", "labor");
}

// @table dwl_resources
export function listDwlResourcesWithCategoryMaterial() {
  return db().from("dwl_resources").select("id, code, description, unit").eq("category", "material");
}

// @table dwl_resources
export function listDwlResourcesWithIsActive() {
  return db()
    .from("dwl_resources")
    .select("id, tenant_id, code, category, description, unit, spec_reference, is_active, created_by, created_at, updated_at")
    .eq("is_active", true);
}

// @table dwl_resources
export function listDwlResourcesWithIsActiveAndCategoryMaterial() {
  return db()
    .from("dwl_resources")
    .select("id, tenant_id, code, category, description, unit, spec_reference, is_active, created_by, created_at, updated_at")
    .eq("is_active", true)
    .eq("category", "material")
    .order("code");
}

// @table dwl_resources
export function listDwlResourcesWithOptions(columns: string, options: object | undefined) {
  return db().from("dwl_resources").select(columns, options);
}

// @table dwl_resources
export function updateDwlResourceById(patch: object, id: string | number | boolean) {
  return db().from("dwl_resources").update(patch).eq("id", id);
}

// ── dwl_subcon_attributes ─────────────────────────────────────────────────────

// @table dwl_subcon_attributes
export function insertDwlSubconAttribute(row: object) {
  return db().from("dwl_subcon_attributes").insert([row]);
}

// @table dwl_subcon_attributes
export function listDwlSubconAttributes(columns: string) {
  return db().from("dwl_subcon_attributes").select(columns as "*");
}

// @table dwl_subcon_attributes
export function listDwlSubconAttributesByTrade(trade: string | number | boolean) {
  return db()
    .from("dwl_subcon_attributes")
    .select("resource_id, dwl_resources!inner(id, description)")
    .eq("trade", trade);
}

// ── dwl_submit_price_submission ───────────────────────────────────────────────

// @table dwl_submit_price_submission
export function dwlSubmitPriceSubmission(args: object) {
  return db().rpc("dwl_submit_price_submission", args);
}

// ── dwl_supplier_materials ────────────────────────────────────────────────────

// @table dwl_supplier_materials
export function insertDwlSupplierMaterial(row: object) {
  return db().from("dwl_supplier_materials").insert([row]);
}

// @table dwl_supplier_materials
export function listDwlSupplierMaterials() {
  return db().from("dwl_supplier_materials").select("supplier_id, resource_id");
}

// ── dwl_supplier_profiles ─────────────────────────────────────────────────────

// @table dwl_supplier_profiles
export function insertDwlSupplierProfile(row: object) {
  return db().from("dwl_supplier_profiles").insert([row]);
}

// @table dwl_supplier_profiles
export function listDwlSupplierProfiles(columns: string) {
  return db().from("dwl_supplier_profiles").select(columns as "*");
}

// @table dwl_supplier_profiles
export function listDwlSupplierProfilesByVendorKind(vendorKind: string | number | boolean) {
  return db().from("dwl_supplier_profiles").select("supplier_code").eq("vendor_kind", vendorKind);
}

// @table dwl_supplier_profiles
export function listDwlSupplierProfilesWithVendorKindSubcontractor() {
  return db()
    .from("dwl_supplier_profiles")
    .select("supplier_id, supplier_code, dwl_suppliers!inner(id, name, is_active)")
    .eq("vendor_kind", "subcontractor");
}

// @table dwl_supplier_profiles
export function listDwlSupplierProfilesWithVendorKindSubcontractorAndIsActive() {
  return db()
    .from("dwl_supplier_profiles")
    .select("supplier_id, supplier_code, dwl_suppliers!inner(id, name, is_active)")
    .eq("vendor_kind", "subcontractor")
    .eq("dwl_suppliers.is_active", true);
}

// @table dwl_supplier_profiles
export function updateDwlSupplierProfilesBySupplierId(patch: object, supplierId: string | number | boolean) {
  return db().from("dwl_supplier_profiles").update(patch).eq("supplier_id", supplierId);
}

// ── dwl_suppliers ─────────────────────────────────────────────────────────────

// @table dwl_suppliers
export function deleteDwlSupplierById(id: string | number | boolean) {
  return db().from("dwl_suppliers").delete().eq("id", id);
}

// @table dwl_suppliers
export function deleteDwlSupplierByIdReturning(id: string | number | boolean) {
  return db().from("dwl_suppliers").delete().eq("id", id).select("id");
}

// @table dwl_suppliers
export function insertDwlSupplierReturning(row: object) {
  return db().from("dwl_suppliers").insert([row]).select("id").single();
}

// @table dwl_suppliers
export function listDwlSuppliers() {
  return db().from("dwl_suppliers").select("id, name");
}

// @table dwl_suppliers
export function listDwlSuppliersWithIsActive() {
  return db()
    .from("dwl_suppliers")
    .select("id, tenant_id, name, contact, rating, is_active")
    .eq("is_active", true)
    .order("name");
}

// @table dwl_suppliers
export function updateDwlSupplierById(patch: object, id: string | number | boolean) {
  return db().from("dwl_suppliers").update(patch).eq("id", id);
}

// ── dwl_v_assembly_costing_summary ────────────────────────────────────────────

// @table dwl_v_assembly_costing_summary
export function getDwlVAssemblyCostingSummaryByAssemblyId(columns: string, assemblyId: string | number | boolean) {
  return db()
    .from("dwl_v_assembly_costing_summary")
    .select(columns)
    .eq("assembly_id", assemblyId)
    .maybeSingle();
}

// @table dwl_v_assembly_costing_summary
export function listDwlVAssemblyCostingSummary(columns: string) {
  return db().from("dwl_v_assembly_costing_summary").select(columns).order("code");
}

// ── dwl_v_assembly_layer_materials ────────────────────────────────────────────

// @table dwl_v_assembly_layer_materials
export function listDwlVAssemblyLayerMaterialsByLayerIds(layerIds: readonly (string | number)[]) {
  return db()
    .from("dwl_v_assembly_layer_materials")
    .select("layer_id, assembly_id, material_codes, material_names, total_cost_contribution")
    .in("layer_id", layerIds);
}

// ── dwl_v_assembly_material_explosion ─────────────────────────────────────────

// @table dwl_v_assembly_material_explosion
export function listDwlVAssemblyMaterialExplosionByAssemblyId(columns: string, assemblyId: string | number | boolean) {
  return db()
    .from("dwl_v_assembly_material_explosion")
    .select(columns)
    .eq("assembly_id", assemblyId)
    .order("sort_order");
}

// ── dwl_v_assembly_rates ──────────────────────────────────────────────────────

// @table dwl_v_assembly_rates
export function listDwlVAssemblyRates() {
  return db()
    .from("dwl_v_assembly_rates")
    .select("assembly_id, code, element_group, description, unit, net_direct_rate, has_expired_price");
}

// @table dwl_v_assembly_rates
export function listDwlVAssemblyRatesByAssemblyIds(assemblyIds: readonly (string | number)[]) {
  return db()
    .from("dwl_v_assembly_rates")
    .select("assembly_id, net_direct_rate, has_expired_price")
    .in("assembly_id", assemblyIds);
}

// @table dwl_v_assembly_rates
export function listDwlVAssemblyRatesOrderedByCode() {
  return db()
    .from("dwl_v_assembly_rates")
    .select("assembly_id, code, element_group, description, unit, net_direct_rate, has_expired_price")
    .order("code");
}

// ── dwl_v_current_material_spec ───────────────────────────────────────────────

// @table dwl_v_current_material_spec
export function getDwlVCurrentMaterialSpecByResourceId(resourceId: string | number | boolean) {
  return db().from("dwl_v_current_material_spec").select("*").eq("resource_id", resourceId).maybeSingle();
}

// ── dwl_v_current_prices ──────────────────────────────────────────────────────

// @table dwl_v_current_prices
export function listDwlVCurrentPrices() {
  return db()
    .from("dwl_v_current_prices")
    .select("resource_id, code, description, unit, unit_price, currency, valid_from, quote_valid_until, source_type, supplier_name, is_expired")
    .order("code");
}

// @table dwl_v_current_prices
export function listDwlVCurrentPricesByResourceIds(resourceIds: readonly (string | number)[]) {
  return db()
    .from("dwl_v_current_prices")
    .select("resource_id, code, description, unit, unit_price, currency, valid_from, quote_valid_until, source_type, supplier_name, is_expired")
    .in("resource_id", resourceIds);
}

// ── dwl_v_equipment_rates ─────────────────────────────────────────────────────

// @table dwl_v_equipment_rates
export function listDwlVEquipmentRatesWithIsActive(columns: string) {
  return db().from("dwl_v_equipment_rates").select(columns).eq("is_active", true).order("code");
}

// ── dwl_v_labor_rates ─────────────────────────────────────────────────────────

// @table dwl_v_labor_rates
export function listDwlVLaborRatesWithIsActive(columns: string) {
  return db().from("dwl_v_labor_rates").select(columns).eq("is_active", true).order("code");
}

// ── dwl_v_materials ───────────────────────────────────────────────────────────

// @table dwl_v_materials
export function getDwlVMaterialByResourceId(columns: string, resourceId: string | number | boolean) {
  return db().from("dwl_v_materials").select(columns).eq("resource_id", resourceId).maybeSingle();
}

// @table dwl_v_materials
export function listDwlVMaterials() {
  return db()
    .from("dwl_v_materials")
    .select("resource_id, code, material_name, category_id, category_name, application_element, discipline, is_active")
    .order("code");
}

// @table dwl_v_materials
export function listDwlVMaterialsOrderedByCode(columns: string) {
  return db().from("dwl_v_materials").select(columns).order("code");
}

// ── dwl_v_price_submissions ───────────────────────────────────────────────────

// @table dwl_v_price_submissions
export function listDwlVPriceSubmissions() {
  return db().from("dwl_v_price_submissions").select("*").order("created_at", { ascending: false });
}

// @table dwl_v_price_submissions
export function listDwlVPriceSubmissionsByResourceIdWithStatusApproved(resourceId: string | number | boolean) {
  return db()
    .from("dwl_v_price_submissions")
    .select("*")
    .eq("resource_id", resourceId)
    .neq("status", "approved")
    .order("created_at", { ascending: false });
}

// ── dwl_v_project_estimate ────────────────────────────────────────────────────

// @table dwl_v_project_estimate
export function listDwlVProjectEstimateByProjectId(projectId: string | number | boolean) {
  return db()
    .from("dwl_v_project_estimate")
    .select("project_id, name, element_group, assembly_code, description, unit, quantity, net_direct_rate, amount")
    .eq("project_id", projectId)
    .order("element_group");
}

// ── dwl_v_resource_costing_rates ──────────────────────────────────────────────

// @table dwl_v_resource_costing_rates
export function listDwlVResourceCostingRatesByResourceIds(resourceIds: readonly (string | number)[]) {
  return db()
    .from("dwl_v_resource_costing_rates")
    .select("resource_id, code, unit_price:costing_rate, currency")
    .in("resource_id", resourceIds);
}

// ── dwl_v_subcon_rates ────────────────────────────────────────────────────────

// @table dwl_v_subcon_rates
export function listDwlVSubconRates() {
  return db().from("dwl_v_subcon_rates").select("resource_id, subcontractor_id, effective_date");
}

// @table dwl_v_subcon_rates
export function listDwlVSubconRatesOrderedBySubcontractorNameAndItemDescriptionAndRateYear(columns: string) {
  return db()
    .from("dwl_v_subcon_rates")
    .select(columns)
    .order("subcontractor_name")
    .order("item_description")
    .order("rate_year", { ascending: false });
}

// ── dwl_v_supplier_materials ──────────────────────────────────────────────────

// @table dwl_v_supplier_materials
export function listDwlVSupplierMaterialsByResourceId(resourceId: string | number | boolean) {
  return db()
    .from("dwl_v_supplier_materials")
    .select("*")
    .eq("resource_id", resourceId)
    .order("supplier_name");
}

// @table dwl_v_supplier_materials
export function listDwlVSupplierMaterialsByResourceIdsWithIsActive(resourceIds: readonly (string | number)[]) {
  return db()
    .from("dwl_v_supplier_materials")
    .select("id, tenant_id, supplier_id, supplier_name, supplier_code, resource_id, material_code, material_name, material_unit, supplier_product_code, supplier_product_name, brand, manufacturer, specification, standard, package_size, moq, lead_time_days, is_active, notes, created_at, updated_at")
    .in("resource_id", resourceIds)
    .eq("is_active", true);
}

// ── dwl_v_suppliers ───────────────────────────────────────────────────────────

// @table dwl_v_suppliers
export function listDwlVSuppliersWithVendorKindMaterialSupplier(columns: string) {
  return db().from("dwl_v_suppliers").select(columns).eq("vendor_kind", "material_supplier").order("name");
}

// ── dwl_v_work_item_explosion ─────────────────────────────────────────────────

// @table dwl_v_work_item_explosion
export function listDwlVWorkItemExplosionByWorkItemCode(workItemCode: string | number | boolean) {
  return db()
    .from("dwl_v_work_item_explosion")
    .select("work_item_code, sort_order, resource_code, resource_desc, resource_unit, consumption, waste_pct, unit_price, line_cost, source_type, is_expired, basis_note")
    .eq("work_item_code", workItemCode)
    .order("sort_order");
}

// ── dwl_v_work_item_rates ─────────────────────────────────────────────────────

// @table dwl_v_work_item_rates
export function listDwlVWorkItemRates() {
  return db()
    .from("dwl_v_work_item_rates")
    .select("work_item_id, code, boq_section, description, unit, net_direct_rate, has_expired_price, recipe_lines");
}

// @table dwl_v_work_item_rates
export function listDwlVWorkItemRatesByWorkItemIds(workItemIds: readonly (string | number)[]) {
  return db()
    .from("dwl_v_work_item_rates")
    .select("work_item_id, net_direct_rate, has_expired_price")
    .in("work_item_id", workItemIds);
}

// @table dwl_v_work_item_rates
export function listDwlVWorkItemRatesOrderedByCode() {
  return db()
    .from("dwl_v_work_item_rates")
    .select("work_item_id, code, boq_section, description, unit, net_direct_rate, has_expired_price, recipe_lines")
    .order("code");
}

// ── dwl_work_item_resources ───────────────────────────────────────────────────

// @table dwl_work_item_resources
export function deleteDwlWorkItemResourceById(id: string | number | boolean) {
  return db().from("dwl_work_item_resources").delete().eq("id", id);
}

// @table dwl_work_item_resources
export function insertDwlWorkItemResources(rows: object | object[]) {
  return db().from("dwl_work_item_resources").insert(rows);
}

// @table dwl_work_item_resources
export function listDwlWorkItemResourcesByWorkItemId(workItemId: string | number | boolean) {
  return db()
    .from("dwl_work_item_resources")
    .select("id, tenant_id, work_item_id, resource_id, consumption, waste_pct, basis_note, sort_order, dwl_resources!inner(code)")
    .eq("work_item_id", workItemId);
}

// @table dwl_work_item_resources
export function listDwlWorkItemResourcesByWorkItemIds(workItemIds: readonly (string | number)[]) {
  return db()
    .from("dwl_work_item_resources")
    .select("id, tenant_id, work_item_id, resource_id, consumption, waste_pct, basis_note, sort_order")
    .in("work_item_id", workItemIds);
}

// @table dwl_work_item_resources
export function updateDwlWorkItemResourceById(patch: object, id: string | number | boolean) {
  return db().from("dwl_work_item_resources").update(patch).eq("id", id);
}

// ── dwl_work_items ────────────────────────────────────────────────────────────

// @table dwl_work_items
export function deleteDwlWorkItemByIdReturning(id: string | number | boolean) {
  return db().from("dwl_work_items").delete().eq("id", id).select("id");
}

// @table dwl_work_items
export function insertDwlWorkItemReturning(row: object) {
  return db()
    .from("dwl_work_items")
    .insert([row])
    .select("id, tenant_id, code, boq_section, description, unit, method_note, is_active, created_by, created_at, updated_at")
    .single();
}

// @table dwl_work_items
export function insertDwlWorkItemsReturning(rows: object | object[]) {
  return db().from("dwl_work_items").insert(rows).select("id").single();
}

// @table dwl_work_items
export function listDwlWorkItems() {
  return db().from("dwl_work_items").select("id, code");
}

// @table dwl_work_items
export function listDwlWorkItemsByIds(ids: readonly (string | number)[]) {
  return db()
    .from("dwl_work_items")
    .select("id, tenant_id, code, boq_section, description, unit, method_note, is_active, created_by, created_at, updated_at")
    .in("id", ids);
}

// @table dwl_work_items
export function listDwlWorkItemsOrderedByCode() {
  return db()
    .from("dwl_work_items")
    .select("id, tenant_id, code, boq_section, description, unit, method_note, is_active, created_by, created_at, updated_at")
    .order("code");
}

// @table dwl_work_items
export function listDwlWorkItemsWithIsActive() {
  return db()
    .from("dwl_work_items")
    .select("id, tenant_id, code, boq_section, description, unit, method_note, is_active, created_by, created_at, updated_at")
    .eq("is_active", true)
    .order("code");
}

// @table dwl_work_items
export function updateDwlWorkItemById(patch: object, id: string | number | boolean) {
  return db().from("dwl_work_items").update(patch).eq("id", id);
}

// ── entitlement_register ──────────────────────────────────────────────────────

// @table entitlement_register
export function deleteEntitlementRegisterById(id: string | number | boolean) {
  return db().from("entitlement_register").delete().eq("id", id);
}

// @table entitlement_register
export function getEntitlementRegisterById(id: string | number | boolean) {
  return db()
    .from("entitlement_register")
    .select("*, contract_register(contract_no, title), contractual_notices(notice_no, title)")
    .eq("id", id)
    .single();
}

// @table entitlement_register
export function insertEntitlementRegister(row: object) {
  return db().from("entitlement_register").insert([row]);
}

// @table entitlement_register
export function listEntitlementRegister() {
  return db()
    .from("entitlement_register")
    .select("*, contract_register!inner(project_id)")
    .order("created_at", { ascending: false });
}

// @table entitlement_register
export function updateEntitlementRegisterById(patch: object, id: string | number | boolean) {
  return db().from("entitlement_register").update(patch).eq("id", id);
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function getProfileById(id: string | number | boolean, columns: string) {
  return db().from("profiles").select(columns as "*").eq("id", id).single();
}

// ── project_precontract_details ───────────────────────────────────────────────

// @table project_precontract_details
export function getProjectPrecontractDetailByProjectId(projectId: string | number | boolean) {
  return db()
    .from("project_precontract_details")
    .select("tender_stage")
    .eq("project_id", projectId)
    .maybeSingle();
}

// ── projects ──────────────────────────────────────────────────────────────────

// @table projects
export function listProjects() {
  return db().from("projects").select("id,name:project_name");
}

// ── qs_description_library ────────────────────────────────────────────────────

// @table qs_description_library
export function deleteQsDescriptionLibraryById(id: string | number | boolean) {
  return db().from("qs_description_library").delete().eq("id", id);
}

// @table qs_description_library
export function insertQsDescriptionLibraryReturning(row: object) {
  return db().from("qs_description_library").insert([row]).select().single();
}

// @table qs_description_library
export function listQsDescriptionLibrary() {
  return db().from("qs_description_library").select("*").order("sort_order");
}

// @table qs_description_library
export function updateQsDescriptionLibraryById(patch: object, id: string | number | boolean) {
  return db().from("qs_description_library").update(patch).eq("id", id);
}

// ── qs_element_library ────────────────────────────────────────────────────────

// @table qs_element_library
export function deleteQsElementLibraryById(id: string | number | boolean) {
  return db().from("qs_element_library").delete().eq("id", id);
}

// @table qs_element_library
export function insertQsElementLibraryReturning(row: object) {
  return db().from("qs_element_library").insert([row]).select().single();
}

// @table qs_element_library
export function listQsElementLibrary() {
  return db().from("qs_element_library").select("*").order("sort_order");
}

// @table qs_element_library
export function listQsElementLibraryWithIsActive() {
  return db().from("qs_element_library").select("sub_element").eq("is_active", true);
}

// @table qs_element_library
export function updateQsElementLibraryById(patch: object, id: string | number | boolean) {
  return db().from("qs_element_library").update(patch).eq("id", id);
}

// ── qs_v_boq_requisition_status ───────────────────────────────────────────────

// @table qs_v_boq_requisition_status
export function listQsVBoqRequisitionStatusByProjectId(projectId: string | number | boolean) {
  return db()
    .from("qs_v_boq_requisition_status")
    .select("boq_item_id, requisitioned_quantity, ordered_quantity, delivered_quantity, remaining_quantity, po_ids")
    .eq("project_id", projectId);
}

// ── qto_drawing_revisions ─────────────────────────────────────────────────────

// @table qto_drawing_revisions
export function updateQtoDrawingRevisionById(patch: object, id: string | number | boolean) {
  return db().from("qto_drawing_revisions").update(patch).eq("id", id);
}

// ── subcontract_back_charges ──────────────────────────────────────────────────

// @table subcontract_back_charges
export function insertSubcontractBackCharge(row: object) {
  return db().from("subcontract_back_charges").insert([row]);
}

// @table subcontract_back_charges
export function listSubcontractBackCharges() {
  return db()
    .from("subcontract_back_charges")
    .select("*, ncrs(ncr_number), subcontracts!inner(project_id)")
    .order("raised_date", { ascending: false });
}

// @table subcontract_back_charges
export function listSubcontractBackChargesBySubcontractId(subcontractId: string | number | boolean) {
  return db()
    .from("subcontract_back_charges")
    .select("*")
    .eq("subcontract_id", subcontractId)
    .order("raised_date", { ascending: false });
}

// ── subcontract_ipcs ──────────────────────────────────────────────────────────

// @table subcontract_ipcs
export function insertSubcontractIpc(row: object) {
  return db().from("subcontract_ipcs").insert([row]);
}

// @table subcontract_ipcs
export function listSubcontractIpcsByProjectId(columns: string, projectId: string | number | boolean) {
  return db()
    .from("subcontract_ipcs")
    .select(columns)
    .eq("subcontracts.project_id", projectId)
    .order("created_at", { ascending: false });
}

// @table subcontract_ipcs
export function listSubcontractIpcsBySubcontractId(subcontractId: string | number | boolean) {
  return db()
    .from("subcontract_ipcs")
    .select("*")
    .eq("subcontract_id", subcontractId)
    .order("created_at", { ascending: false });
}

// ── subcontract_items ─────────────────────────────────────────────────────────

// @table subcontract_items
export function deleteSubcontractItemById(id: string | number | boolean) {
  return db().from("subcontract_items").delete().eq("id", id);
}

// @table subcontract_items
export function insertSubcontractItem(row: object) {
  return db().from("subcontract_items").insert([row]);
}

// @table subcontract_items
export function listSubcontractItemsBySubcontractId(subcontractId: string | number | boolean) {
  return db().from("subcontract_items").select("*").eq("subcontract_id", subcontractId).order("sort_order");
}

// ── subcontract_performance_notices ───────────────────────────────────────────

// @table subcontract_performance_notices
export function insertSubcontractPerformanceNotice(row: object) {
  return db().from("subcontract_performance_notices").insert([row]);
}

// @table subcontract_performance_notices
export function listSubcontractPerformanceNotices() {
  return db()
    .from("subcontract_performance_notices")
    .select("*, subcontracts!inner(project_id)")
    .order("created_at", { ascending: false });
}

// @table subcontract_performance_notices
export function listSubcontractPerformanceNoticesBySubcontractId(subcontractId: string | number | boolean) {
  return db()
    .from("subcontract_performance_notices")
    .select("*")
    .eq("subcontract_id", subcontractId)
    .order("created_at", { ascending: false });
}

// @table subcontract_performance_notices
export function updateSubcontractPerformanceNoticeById(patch: object, id: string | number | boolean) {
  return db().from("subcontract_performance_notices").update(patch).eq("id", id);
}

// ── subcontract_variations ────────────────────────────────────────────────────

// @table subcontract_variations
export function deleteSubcontractVariationById(id: string | number | boolean) {
  return db().from("subcontract_variations").delete().eq("id", id);
}

// @table subcontract_variations
export function insertSubcontractVariation(row: object) {
  return db().from("subcontract_variations").insert([row]);
}

// @table subcontract_variations
export function listSubcontractVariationsByProjectId(columns: string, projectId: string | number | boolean) {
  return db()
    .from("subcontract_variations")
    .select(columns)
    .eq("subcontracts.project_id", projectId)
    .order("created_at", { ascending: false });
}

// @table subcontract_variations
export function listSubcontractVariationsBySubcontractId(subcontractId: string | number | boolean) {
  return db()
    .from("subcontract_variations")
    .select("*")
    .eq("subcontract_id", subcontractId)
    .order("created_at", { ascending: false });
}

// @table subcontract_variations
export function updateSubcontractVariationById(patch: object, id: string | number | boolean) {
  return db().from("subcontract_variations").update(patch).eq("id", id);
}

// ── subcontracts ──────────────────────────────────────────────────────────────

// @table subcontracts
export function getSubcontractById(id: string | number | boolean) {
  return db().from("subcontracts").select("*").eq("id", id).single();
}

// @table subcontracts
export function insertSubcontract(row: object) {
  return db().from("subcontracts").insert([row]);
}

// @table subcontracts
export function listSubcontracts() {
  return db().from("subcontracts").select("id,subcontract_no");
}

// @table subcontracts
export function listSubcontractsByProjectId(projectId: string | number | boolean) {
  return db().from("subcontracts").select("id,subcontract_no").eq("project_id", projectId);
}

// @table subcontracts
export function listSubcontractsOrderedByCreatedAt() {
  return db().from("subcontracts").select("*").order("created_at", { ascending: false });
}

// @table subcontracts
export function updateSubcontractById(patch: object, id: string | number | boolean) {
  return db().from("subcontracts").update(patch).eq("id", id);
}

// ── tender_addenda ────────────────────────────────────────────────────────────

// @table tender_addenda
export function deleteTenderAddendaById(id: string | number | boolean) {
  return db().from("tender_addenda").delete().eq("id", id);
}

// @table tender_addenda
export function insertTenderAddenda(row: object) {
  return db().from("tender_addenda").insert([row]);
}

// @table tender_addenda
export function listTenderAddendaByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_addenda")
    .select("*")
    .eq("tender_id", tenderId)
    .order("issue_date", { ascending: false });
}

// ── tender_award_records ──────────────────────────────────────────────────────

// @table tender_award_records
export function countTenderAwardRecords() {
  return db().from("tender_award_records").select("id", { count: "exact", head: true });
}

// @table tender_award_records
export function deleteTenderAwardRecordById(id: string | number | boolean) {
  return db().from("tender_award_records").delete().eq("id", id);
}

// @table tender_award_records
export function insertTenderAwardRecord(row: object) {
  return db().from("tender_award_records").insert([row]);
}

// @table tender_award_records
export function listTenderAwardRecordsByTenderId(tenderId: string | number | boolean) {
  return db().from("tender_award_records").select("*").eq("tender_id", tenderId);
}

// @table tender_award_records
export function updateTenderAwardRecordById(patch: object, id: string | number | boolean) {
  return db().from("tender_award_records").update(patch).eq("id", id);
}

// ── tender_boq_items ──────────────────────────────────────────────────────────

// @table tender_boq_items
export function listTenderBoqItemsByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_boq_items")
    .select("dwl_assembly_id, level, building_code")
    .eq("tender_id", tenderId)
    .not("dwl_assembly_id", "is", null);
}

// ── tender_cost_databases ─────────────────────────────────────────────────────

// @table tender_cost_databases
export function countTenderCostDatabasesBySourceTenderId(sourceTenderId: string | number | boolean) {
  return db()
    .from("tender_cost_databases")
    .select("id", { count: "exact", head: true })
    .eq("source_tender_id", sourceTenderId);
}

// ── tender_invitations ────────────────────────────────────────────────────────

// @table tender_invitations
export function deleteTenderInvitationById(id: string | number | boolean) {
  return db().from("tender_invitations").delete().eq("id", id);
}

// @table tender_invitations
export function insertTenderInvitation(row: object) {
  return db().from("tender_invitations").insert([row]);
}

// @table tender_invitations
export function listTenderInvitationsByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_invitations")
    .select("id, company_name, response, bid_submitted")
    .eq("tender_id", tenderId)
    .order("company_name");
}

// @table tender_invitations
export function listTenderInvitationsByTenderIdOrderedByInvitedDate(tenderId: string | number | boolean) {
  return db()
    .from("tender_invitations")
    .select("*")
    .eq("tender_id", tenderId)
    .order("invited_date", { ascending: false });
}

// @table tender_invitations
export function updateTenderInvitationById(patch: object, id: string | number | boolean) {
  return db().from("tender_invitations").update(patch).eq("id", id);
}

// ── tender_is_locked ──────────────────────────────────────────────────────────

// @table tender_is_locked
export function tenderIsLocked(args: object) {
  return db().rpc("tender_is_locked", args);
}

// ── tender_preliminaries_items ────────────────────────────────────────────────

// @table tender_preliminaries_items
export function insertTenderPreliminariesItems(rows: object | object[]) {
  return db().from("tender_preliminaries_items").insert(rows);
}

// @table tender_preliminaries_items
export function listTenderPreliminariesItemsByTenderId(tenderId: string | number | boolean) {
  return db().from("tender_preliminaries_items").select("code").eq("tender_id", tenderId);
}

// ── tender_register ───────────────────────────────────────────────────────────

// @table tender_register
export function countTenderRegister() {
  return db().from("tender_register").select("id", { count: "exact", head: true });
}

// @table tender_register
export function countTenderRegisterWithStatusPublishedInvitationSubmission() {
  return db()
    .from("tender_register")
    .select("id", { count: "exact", head: true })
    .in("status", ["published","invitation","submission"]);
}

// @table tender_register
export function deleteTenderRegisterById(id: string | number | boolean) {
  return db().from("tender_register").delete().eq("id", id);
}

// @table tender_register
export function getTenderRegisterById(id: string | number | boolean, columns: string) {
  return db().from("tender_register").select(columns as "*").eq("id", id).single();
}

// @table tender_register
export function insertTenderRegister(rows: object | object[]) {
  return db().from("tender_register").insert(rows);
}

// @table tender_register
export function listTenderRegister(columns: string) {
  return db().from("tender_register").select(columns as "*").order("created_at", { ascending: false });
}

// @table tender_register
export function updateTenderRegisterById(patch: object, id: string | number | boolean) {
  return db().from("tender_register").update(patch).eq("id", id);
}

// ── tender_risk_items ─────────────────────────────────────────────────────────

// @table tender_risk_items
export function deleteTenderRiskItemById(id: string | number | boolean) {
  return db().from("tender_risk_items").delete().eq("id", id);
}

// @table tender_risk_items
export function insertTenderRiskItem(row: object) {
  return db().from("tender_risk_items").insert([row]);
}

// @table tender_risk_items
export function listTenderRiskItemsByTenderId(tenderId: string | number | boolean) {
  return db().from("tender_risk_items").select("*").eq("tender_id", tenderId);
}

// ── tender_sub_quotes ─────────────────────────────────────────────────────────

// @table tender_sub_quotes
export function deleteTenderSubQuoteById(id: string | number | boolean) {
  return db().from("tender_sub_quotes").delete().eq("id", id);
}

// @table tender_sub_quotes
export function insertTenderSubQuote(row: object) {
  return db().from("tender_sub_quotes").insert([row]);
}

// @table tender_sub_quotes
export function listTenderSubQuotesByTenderId(tenderId: string | number | boolean) {
  return db().from("tender_sub_quotes").select("*").eq("tender_id", tenderId);
}

// ── tender_submission_items ───────────────────────────────────────────────────

// @table tender_submission_items
export function deleteTenderSubmissionItemsBySubmissionId(submissionId: string | number | boolean) {
  return db().from("tender_submission_items").delete().eq("submission_id", submissionId);
}

// @table tender_submission_items
export function insertTenderSubmissionItems(rows: object | object[]) {
  return db().from("tender_submission_items").insert(rows);
}

// @table tender_submission_items
export function listTenderSubmissionItemsBySubmissionId(submissionId: string | number | boolean, columns: string) {
  return db()
    .from("tender_submission_items")
    .select(columns as "*")
    .eq("submission_id", submissionId)
    .order("item_code");
}

// ── tender_submissions ────────────────────────────────────────────────────────

// @table tender_submissions
export function countTenderSubmissions() {
  return db().from("tender_submissions").select("id", { count: "exact", head: true });
}

// @table tender_submissions
export function deleteTenderSubmissionById(id: string | number | boolean) {
  return db().from("tender_submissions").delete().eq("id", id);
}

// @table tender_submissions
export function insertTenderSubmissionsReturning(rows: object | object[]) {
  return db().from("tender_submissions").insert(rows).select("id").single();
}

// @table tender_submissions
export function listTenderSubmissionsByTenderId(tenderId: string | number | boolean) {
  return db().from("tender_submissions").select("*").eq("tender_id", tenderId);
}

// @table tender_submissions
export function listTenderSubmissionsByTenderIdOrderedBySubmittedDate(tenderId: string | number | boolean) {
  return db()
    .from("tender_submissions")
    .select("*, tender_register!inner(tender_no, title)")
    .eq("tender_id", tenderId)
    .order("submitted_date", { ascending: false });
}

// @table tender_submissions
export function updateTenderSubmissionById(patch: object, id: string | number | boolean) {
  return db().from("tender_submissions").update(patch).eq("id", id);
}

// ── tender_win_loss ───────────────────────────────────────────────────────────

// @table tender_win_loss
export function getTenderWinLossByTenderId(tenderId: string | number | boolean) {
  return db().from("tender_win_loss").select("*").eq("tender_id", tenderId).maybeSingle();
}

// @table tender_win_loss
export function insertTenderWinLoss(rows: object | object[]) {
  return db().from("tender_win_loss").insert(rows);
}

// @table tender_win_loss
export function updateTenderWinLossById(patch: object, id: string | number | boolean) {
  return db().from("tender_win_loss").update(patch).eq("id", id);
}

// ── time_bar_alerts ───────────────────────────────────────────────────────────

// @table time_bar_alerts
export function listTimeBarAlerts() {
  return db().from("time_bar_alerts").select("*").order("deadline_date");
}

// ── unit_rate_library ─────────────────────────────────────────────────────────

// @table unit_rate_library
export function deleteUnitRateLibraryById(id: string | number | boolean) {
  return db().from("unit_rate_library").delete().eq("id", id);
}

// @table unit_rate_library
export function insertUnitRateLibrary(row: object) {
  return db().from("unit_rate_library").insert([row]);
}

// @table unit_rate_library
export function listUnitRateLibrary() {
  return db().from("unit_rate_library").select("*").order("category");
}

// ── Material Master code allocation / duplicate detection ─────────────────────

// @table dwl_create_material
export function dwlCreateMaterial(payload: object) {
  return db().rpc("dwl_create_material", { p: payload });
}

// @table dwl_find_material_matches
export function dwlFindMaterialMatches(args: object) {
  return db().rpc("dwl_find_material_matches", args);
}

// @table dwl_v_material_duplicates
export function listDwlVMaterialDuplicates() {
  return db().from("dwl_v_material_duplicates").select("fingerprint, copies, codes, names").order("copies", { ascending: false });
}
