// Data access for the design-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── design_arc_room_data ──────────────────────────────────────────────────────

// @table design_arc_room_data
export function insertDesignArcRoomData(row: object) {
  return db().from("design_arc_room_data").insert([row]);
}

// @table design_arc_room_data
export function listDesignArcRoomData() {
  return db().from("design_arc_room_data").select("*").order("room_no");
}

// @table design_arc_room_data
export function updateDesignArcRoomDataById(patch: object, id: string | number | boolean) {
  return db().from("design_arc_room_data").update(patch).eq("id", id);
}

// ── design_coordination_log ───────────────────────────────────────────────────

// @table design_coordination_log
export function insertDesignCoordinationLog(row: object) {
  return db().from("design_coordination_log").insert([row]);
}

// @table design_coordination_log
export function listDesignCoordinationLog() {
  return db().from("design_coordination_log").select("*").order("created_at", { ascending: false });
}

// ── design_drawings ───────────────────────────────────────────────────────────

// @table design_drawings
export function countDesignDrawingsWithDisciplineArc() {
  return db().from("design_drawings").select("id", { count: "exact", head: true }).eq("discipline", "arc");
}

// @table design_drawings
export function countDesignDrawingsWithDisciplineMep() {
  return db().from("design_drawings").select("id", { count: "exact", head: true }).eq("discipline", "mep");
}

// @table design_drawings
export function countDesignDrawingsWithDisciplineStr() {
  return db().from("design_drawings").select("id", { count: "exact", head: true }).eq("discipline", "str");
}

// @table design_drawings
export function insertDesignDrawing(row: object) {
  return db().from("design_drawings").insert([row]);
}

// @table design_drawings
export function listDesignDrawings() {
  return db().from("design_drawings").select("project_id").limit(1);
}

// @table design_drawings
export function listDesignDrawingsByDiscipline(discipline: string | number | boolean) {
  return db().from("design_drawings").select("*").eq("discipline", discipline).order("drawing_no");
}

// @table design_drawings
export function listDesignDrawingsOfIdAndDrawingNo() {
  return db().from("design_drawings").select("id,drawing_no");
}

// @table design_drawings
export function updateDesignDrawingById(patch: object, id: string | number | boolean) {
  return db().from("design_drawings").update(patch).eq("id", id);
}

// ── design_review_comments ────────────────────────────────────────────────────

// @table design_review_comments
export function insertDesignReviewComment(row: object) {
  return db().from("design_review_comments").insert([row]);
}

// @table design_review_comments
export function listDesignReviewCommentsByEntityTypeAndEntityId(entityType: string | number | boolean, entityId: string | number | boolean) {
  return db()
    .from("design_review_comments")
    .select("*")
    .eq("entity_type", entityType)
    .eq("entity_id", entityId)
    .order("created_at");
}

// @table design_review_comments
export function updateDesignReviewCommentById(patch: object, id: string | number | boolean) {
  return db().from("design_review_comments").update(patch).eq("id", id);
}

// ── design_rfi ────────────────────────────────────────────────────────────────

// @table design_rfi
export function countDesignRfiWithStatusOpen() {
  return db().from("design_rfi").select("id", { count: "exact", head: true }).eq("status", "open");
}

// @table design_rfi
export function insertDesignRfi(row: object) {
  return db().from("design_rfi").insert([row]);
}

// @table design_rfi
export function listDesignRfiByDiscipline(discipline: string | number | boolean) {
  return db()
    .from("design_rfi")
    .select("*")
    .eq("discipline", discipline)
    .order("created_at", { ascending: false });
}

// @table design_rfi
export function updateDesignRfiById(patch: object, id: string | number | boolean) {
  return db().from("design_rfi").update(patch).eq("id", id);
}

// ── drawing_markups ───────────────────────────────────────────────────────────

// @table drawing_markups
export function insertDrawingMarkup(row: object) {
  return db().from("drawing_markups").insert([row]);
}

// @table drawing_markups
export function listDrawingMarkups() {
  return db().from("drawing_markups").select("*").order("created_at", { ascending: false });
}
