// Data access for the profile-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── departments ───────────────────────────────────────────────────────────────

// @table departments
export function listDepartments() {
  return db().from("departments").select("id, department_name").order("department_name", { ascending: true });
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function getProfileById(id: string | number | boolean) {
  return db()
    .from("profiles")
    .select("id, employee_id, full_name, email, department_id, job_title, role, account_status, last_login_at, phone, current_address, gender, date_of_birth, nationality, emergency_contact_name, emergency_contact_relationship, emergency_contact_phone")
    .eq("id", id)
    .single();
}
