// Data access for the hr-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── asset_assignments ─────────────────────────────────────────────────────────

// @table asset_assignments
export function listAssetAssignmentsWithStatusActive() {
  return db()
    .from("asset_assignments")
    .select(`
        id,
        assignment_date,
        return_date,
        status,
        condition_on_assignment,
        profiles(full_name, employee_id),
        employee_assets(asset_code, asset_name, asset_type, brand, model)
      `)
    .eq("status", "active")
    .order("assignment_date", { ascending: false })
    .limit(50);
}

// ── attendance_logs ───────────────────────────────────────────────────────────

// @table attendance_logs
export function upsertAttendanceLogs(rows: object | object[]) {
  return db().from("attendance_logs").upsert(rows);
}

// ── attendance_records ────────────────────────────────────────────────────────

// @table attendance_records
export function deleteAttendanceRecordsByEmployeeIdAndAttendanceDatesWithAttendanceTypeLEAVE(employeeId: string | number | boolean, attendanceDates: readonly (string | number)[]) {
  return db()
    .from("attendance_records")
    .delete()
    .eq("employee_id", employeeId)
    .in("attendance_date", attendanceDates)
    .eq("attendance_type", "LEAVE");
}

// @table attendance_records
export function listAttendanceRecords() {
  return db()
    .from("attendance_records")
    .select(`
        id,
        employee_id,
        attendance_date,
        attendance_type,
        check_in_time,
        check_out_time,
        verified,
        profiles!inner(full_name, employee_id)
      `)
    .order("attendance_date", { ascending: false })
    .limit(50);
}

// @table attendance_records
export function listAttendanceRecordsByAttendanceDate(attendanceDate: string | number | boolean, columns: string) {
  return db().from("attendance_records").select(columns as "*").eq("attendance_date", attendanceDate);
}

// @table attendance_records
export function listAttendanceRecordsByDateFromAndDateTo(dateFrom: string | number | boolean, dateTo: string | number | boolean) {
  return db()
    .from("attendance_records")
    .select("employee_id, status")
    .gte("date", dateFrom)
    .lte("date", dateTo);
}

// @table attendance_records
export function listAttendanceRecordsByEmployeeIdAndAttendanceDateFromAndAttendanceDateTo(employeeId: string | number | boolean, attendanceDateFrom: string | number | boolean, attendanceDateTo: string | number | boolean) {
  return db()
    .from("attendance_records")
    .select("attendance_date, attendance_type, check_in_time, check_out_time, hours_worked, verified")
    .eq("employee_id", employeeId)
    .gte("attendance_date", attendanceDateFrom)
    .lte("attendance_date", attendanceDateTo)
    .order("attendance_date", { ascending: true });
}

// @table attendance_records
export function listAttendanceRecordsByEmployeeIdsAndAttendanceDateFromAndAttendanceDateTo(employeeIds: readonly (string | number)[], attendanceDateFrom: string | number | boolean, attendanceDateTo: string | number | boolean) {
  return db()
    .from("attendance_records")
    .select("employee_id, attendance_date, attendance_type, hours_worked")
    .in("employee_id", employeeIds)
    .gte("attendance_date", attendanceDateFrom)
    .lte("attendance_date", attendanceDateTo);
}

// @table attendance_records
export function listAttendanceRecordsOrderedByAttendanceDate() {
  return db()
    .from("attendance_records")
    .select(`attendance_date, attendance_type, employee_id, profiles(full_name)`)
    .order("attendance_date", { ascending: false });
}

// @table attendance_records
export function upsertAttendanceRecords(rows: object | object[]) {
  return db()
    .from("attendance_records")
    .upsert(rows, {
        onConflict: "employee_id, attendance_date",
        ignoreDuplicates: false,
      });
}

// @table attendance_records
export function upsertAttendanceRecords2(rows: object | object[]) {
  return db().from("attendance_records").upsert(rows, { onConflict: "employee_id,attendance_date" });
}

// ── candidates ────────────────────────────────────────────────────────────────

// @table candidates
export function listCandidates() {
  return db().from("candidates").select("status");
}

// @table candidates
export function listCandidatesOrderedByCreatedAt() {
  return db()
    .from("candidates")
    .select(`
        id,
        candidate_name,
        email,
        current_company,
        status,
        created_at,
        job_requisitions(job_title)
      `)
    .order("created_at", { ascending: false })
    .limit(20);
}

// ── departments ───────────────────────────────────────────────────────────────

// @table departments
export function listDepartments() {
  return db().from("departments").select("id, department_name").order("department_name");
}

// ── employee_assets ───────────────────────────────────────────────────────────

// @table employee_assets
export function listEmployeeAssets() {
  return db().from("employee_assets").select("status");
}

// @table employee_assets
export function listEmployeeAssetsOrderedByPurchaseDate() {
  return db()
    .from("employee_assets")
    .select(`
        id,
        asset_code,
        asset_name,
        asset_type,
        serial_number,
        purchase_date,
        purchase_cost,
        status,
        warranty_expiry
      `)
    .order("purchase_date", { ascending: false })
    .limit(50);
}

// ── employee_attendance_site_assignments ──────────────────────────────────────

// @table employee_attendance_site_assignments
export function insertEmployeeAttendanceSiteAssignment(row: object) {
  return db().from("employee_attendance_site_assignments").insert([row]);
}

// @table employee_attendance_site_assignments
export function listEmployeeAttendanceSiteAssignmentsByFilter(filter: string) {
  return db()
    .from("employee_attendance_site_assignments")
    .select("id, employee_id, site_id, effective_from, effective_to, is_required")
    .or(filter)
    .order("effective_from", { ascending: false });
}

// @table employee_attendance_site_assignments
export function updateEmployeeAttendanceSiteAssignmentById(patch: object, id: string | number | boolean) {
  return db().from("employee_attendance_site_assignments").update(patch).eq("id", id);
}

// ── employee_bank_accounts ────────────────────────────────────────────────────

// @table employee_bank_accounts
export function getEmployeeBankAccountByEmployeeIdWithIsPrimary(employeeId: string | number | boolean, columns: string) {
  return db()
    .from("employee_bank_accounts")
    .select(columns as "*")
    .eq("employee_id", employeeId)
    .eq("is_primary", true)
    .maybeSingle();
}

// @table employee_bank_accounts
export function insertEmployeeBankAccount(row: object) {
  return db().from("employee_bank_accounts").insert([row]);
}

// @table employee_bank_accounts
export function listEmployeeBankAccountsWithIsPrimary() {
  return db().from("employee_bank_accounts").select("employee_id").eq("is_primary", true);
}

// @table employee_bank_accounts
export function updateEmployeeBankAccountById(patch: object, id: string | number | boolean) {
  return db().from("employee_bank_accounts").update(patch).eq("id", id);
}

// ── employee_certifications ───────────────────────────────────────────────────

// @table employee_certifications
export function listEmployeeCertifications() {
  return db()
    .from("employee_certifications")
    .select("id, employee_id, certification_name, issuing_body, expiry_date, status");
}

// ── employee_documents ────────────────────────────────────────────────────────

// @table employee_documents
export function listEmployeeDocuments() {
  return db()
    .from("employee_documents")
    .select("id, employee_id, document_type, document_name, expiry_date, verified");
}

// ── employee_nssf_profiles ────────────────────────────────────────────────────

// @table employee_nssf_profiles
export function listEmployeeNssfProfiles() {
  return db()
    .from("employee_nssf_profiles")
    .select("employee_id")
    .order("effective_date", { ascending: false });
}

// @table employee_nssf_profiles
export function listEmployeeNssfProfilesOfEmployeeId() {
  return db().from("employee_nssf_profiles").select("employee_id");
}

// ── employee_payroll_profiles ─────────────────────────────────────────────────

// @table employee_payroll_profiles
export function listEmployeePayrollProfiles() {
  return db().from("employee_payroll_profiles").select("employee_id");
}

// @table employee_payroll_profiles
export function listEmployeePayrollProfilesOrderedByEffectiveDate() {
  return db()
    .from("employee_payroll_profiles")
    .select("employee_id, currency")
    .order("effective_date", { ascending: false });
}

// ── employee_project_assignments ──────────────────────────────────────────────

// @table employee_project_assignments
export function listEmployeeProjectAssignments() {
  return db().from("employee_project_assignments").select(`allocation_percent, profiles(id, full_name)`);
}

// ── employee_salary_structures ────────────────────────────────────────────────

// @table employee_salary_structures
export function insertEmployeeSalaryStructures(rows: object | object[]) {
  return db().from("employee_salary_structures").insert(rows);
}

// @table employee_salary_structures
export function listEmployeeSalaryStructuresByEmployeeIdWithEffectiveTo(employeeId: string | number | boolean) {
  return db()
    .from("employee_salary_structures")
    .select("component_type_id, amount, payroll_component_types(name, category, is_system)")
    .eq("employee_id", employeeId)
    .is("effective_to", null);
}

// @table employee_salary_structures
export function listEmployeeSalaryStructuresWithEffectiveTo(columns: string) {
  return db().from("employee_salary_structures").select(columns as "*").is("effective_to", null);
}

// @table employee_salary_structures
export function updateEmployeeSalaryStructuresByEmployeeIdWithEffectiveTo(patch: object, employeeId: string | number | boolean) {
  return db()
    .from("employee_salary_structures")
    .update(patch)
    .eq("employee_id", employeeId)
    .is("effective_to", null);
}

// ── employee_shift_assignments ────────────────────────────────────────────────

// @table employee_shift_assignments
export function insertEmployeeShiftAssignments(rows: object | object[]) {
  return db().from("employee_shift_assignments").insert(rows);
}

// ── employee_skills ───────────────────────────────────────────────────────────

// @table employee_skills
export function listEmployeeSkills() {
  return db()
    .from("employee_skills")
    .select(`
        id,
        proficiency_level,
        verified_date,
        profiles(full_name, employee_id),
        skills(skill_name, skill_category)
      `)
    .order("verified_date", { ascending: false })
    .limit(50);
}

// @table employee_skills
export function listEmployeeSkillsWithSkills() {
  return db()
    .from("employee_skills")
    .select(`
        skills(skill_name, skill_category),
        proficiency_level
      `);
}

// ── employee_tax_profiles ─────────────────────────────────────────────────────

// @table employee_tax_profiles
export function listEmployeeTaxProfiles(columns: string) {
  return db()
    .from("employee_tax_profiles")
    .select(columns as "*")
    .order("effective_date", { ascending: false });
}

// @table employee_tax_profiles
export function listEmployeeTaxProfilesOfEmployeeId() {
  return db().from("employee_tax_profiles").select("employee_id");
}

// ── interviews ────────────────────────────────────────────────────────────────

// @table interviews
export function listInterviews() {
  return db()
    .from("interviews")
    .select(`
        id,
        interview_type,
        interview_date,
        score,
        recommendation,
        status,
        candidates(candidate_name)
      `)
    .order("interview_date", { ascending: false })
    .limit(20);
}

// ── job_requisitions ──────────────────────────────────────────────────────────

// @table job_requisitions
export function listJobRequisitions() {
  return db().from("job_requisitions").select("status");
}

// @table job_requisitions
export function listJobRequisitionsOrderedByCreatedAt() {
  return db()
    .from("job_requisitions")
    .select(`
        id,
        job_title,
        status,
        created_at,
        target_hire_date,
        departments(dept_name)
      `)
    .order("created_at", { ascending: false })
    .limit(20);
}

// ── leave_approver_config ─────────────────────────────────────────────────────

// @table leave_approver_config
export function deleteLeaveApproverConfigByEmployeeIdWithConfigTypePersonal(employeeId: string | number | boolean) {
  return db()
    .from("leave_approver_config")
    .delete()
    .eq("config_type", "personal")
    .eq("employee_id", employeeId);
}

// @table leave_approver_config
export function insertLeaveApproverConfig(rows: object | object[]) {
  return db().from("leave_approver_config").insert(rows);
}

// @table leave_approver_config
export function listLeaveApproverConfigWithConfigTypePersonalAndIsActive() {
  return db()
    .from("leave_approver_config")
    .select("employee_id, approver_level, approver_id")
    .eq("config_type", "personal")
    .eq("is_active", true);
}

// ── leave_balances ────────────────────────────────────────────────────────────

// @table leave_balances
export function getLeaveBalanceByEmployeeIdAndLeaveTypeIdAndFiscalYear(employeeId: string | number | boolean, leaveTypeId: string | number | boolean, fiscalYear: string | number | boolean) {
  return db()
    .from("leave_balances")
    .select("id, carried_over_days, allocated_days, used_days, remaining_days")
    .eq("employee_id", employeeId)
    .eq("leave_type_id", leaveTypeId)
    .eq("fiscal_year", fiscalYear)
    .single();
}

// @table leave_balances
export function listLeaveBalancesByEmployeeIdAndFiscalYear(employeeId: string | number | boolean, fiscalYear: string | number | boolean) {
  return db()
    .from("leave_balances")
    .select("leave_type_id, remaining_days, carried_over_days")
    .eq("employee_id", employeeId)
    .eq("fiscal_year", fiscalYear);
}

// @table leave_balances
export function listLeaveBalancesByEmployeeIdAndFiscalYearOrderedByLeaveTypeId(employeeId: string | number | boolean, fiscalYear: string | number | boolean) {
  return db()
    .from("leave_balances")
    .select("id, leave_type_id, allocated_days, used_days, remaining_days, carried_over_days")
    .eq("employee_id", employeeId)
    .eq("fiscal_year", fiscalYear)
    .order("leave_type_id");
}

// @table leave_balances
export function listLeaveBalancesByEmployeeIdAndFiscalYearOrderedByLeaveTypesLeaveName(employeeId: string | number | boolean, fiscalYear: string | number | boolean) {
  return db()
    .from("leave_balances")
    .select(`
            *,
            leave_types(leave_name, leave_code, is_paid, carryover_allowed, carryover_expiry_month)
          `)
    .eq("employee_id", employeeId)
    .eq("fiscal_year", fiscalYear)
    .order("leave_types(leave_name)");
}

// @table leave_balances
export function listLeaveBalancesByFiscalYear(fiscalYear: string | number | boolean) {
  return db()
    .from("leave_balances")
    .select(`
          allocated_days, used_days, remaining_days, carried_over_days,
          profiles(full_name, employee_id, departments(name)),
          leave_types(leave_name)
        `)
    .eq("fiscal_year", fiscalYear);
}

// @table leave_balances
export function updateLeaveBalanceById(patch: object, id: string | number | boolean) {
  return db().from("leave_balances").update(patch).eq("id", id);
}

// ── leave_employment_policy ───────────────────────────────────────────────────

// @table leave_employment_policy
export function getLeaveEmploymentPolicyByEmploymentTypeAndProbationStatusAndLeaveTypeId(employmentType: string | number | boolean, probationStatus: string | number | boolean, leaveTypeId: string | number | boolean) {
  return db()
    .from("leave_employment_policy")
    .select("allowed, requires_hr, requires_attachment, monthly_accrual, usable")
    .eq("employment_type", employmentType)
    .eq("probation_status", probationStatus)
    .eq("leave_type_id", leaveTypeId)
    .maybeSingle();
}

// @table leave_employment_policy
export function listLeaveEmploymentPolicy() {
  return db().from("leave_employment_policy").select("*");
}

// @table leave_employment_policy
export function upsertLeaveEmploymentPolicy(rows: object | object[]) {
  return db()
    .from("leave_employment_policy")
    .upsert(rows, { onConflict: "employment_type, probation_status, leave_type_id" });
}

// ── leave_notifications ───────────────────────────────────────────────────────

// @table leave_notifications
export function insertLeaveNotification(row: object) {
  return db().from("leave_notifications").insert([row]);
}

// @table leave_notifications
export function listLeaveNotificationsByRecipientId(recipientId: string | number | boolean) {
  return db()
    .from("leave_notifications")
    .select(`
          id, event_type, body, subject, sent_at, queued_at,
          leave_requests(start_date, end_date, leave_types(leave_name))
        `)
    .eq("recipient_id", recipientId)
    .order("queued_at", { ascending: false })
    .limit(50);
}

// ── leave_public_holidays ─────────────────────────────────────────────────────

// @table leave_public_holidays
export function deleteLeavePublicHolidayById(id: string | number | boolean) {
  return db().from("leave_public_holidays").delete().eq("id", id);
}

// @table leave_public_holidays
export function insertLeavePublicHolidays(rows: object | object[]) {
  return db().from("leave_public_holidays").insert(rows);
}

// @table leave_public_holidays
export function listLeavePublicHolidaysByHolidayDateFromAndHolidayDateToWithIsActive(holidayDateFrom: string | number | boolean, holidayDateTo: string | number | boolean) {
  return db()
    .from("leave_public_holidays")
    .select("holiday_date, holiday_name")
    .gte("holiday_date", holidayDateFrom)
    .lte("holiday_date", holidayDateTo)
    .eq("is_active", true);
}

// @table leave_public_holidays
export function listLeavePublicHolidaysByYearsWithIsActive(years: readonly (string | number)[]) {
  return db()
    .from("leave_public_holidays")
    .select("holiday_date, holiday_name")
    .in("year", years)
    .eq("is_active", true);
}

// @table leave_public_holidays
export function listLeavePublicHolidaysByYearWithIsActive(year: string | number | boolean) {
  return db()
    .from("leave_public_holidays")
    .select("id, holiday_date, holiday_name, year, is_active, note")
    .eq("year", year)
    .eq("is_active", true)
    .order("holiday_date");
}

// @table leave_public_holidays
export function updateLeavePublicHolidayById(patch: object, id: string | number | boolean) {
  return db().from("leave_public_holidays").update(patch).eq("id", id);
}

// ── leave_request_comments ────────────────────────────────────────────────────

// @table leave_request_comments
export function insertLeaveRequestComment(row: object) {
  return db().from("leave_request_comments").insert([row]);
}

// @table leave_request_comments
export function listLeaveRequestCommentsByLeaveRequestId(leaveRequestId: string | number | boolean) {
  return db()
    .from("leave_request_comments")
    .select("*, profiles(full_name)")
    .eq("leave_request_id", leaveRequestId)
    .order("created_at");
}

// ── leave_requests ────────────────────────────────────────────────────────────

// @table leave_requests
export function countLeaveRequestsByEmployeeIdWithStatusSubmitted(employeeId: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select("id", { count: "exact", head: true })
    .eq("employee_id", employeeId)
    .eq("status", "submitted");
}

// @table leave_requests
export function getLeaveRequestById(id: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select(`
          *,
          profiles!leave_requests_employee_id_fkey(full_name, employee_id, email),
          leave_types(leave_name, is_paid)
        `)
    .eq("id", id)
    .single();
}

// @table leave_requests
export function insertLeaveRequest(row: object) {
  return db().from("leave_requests").insert([row]).select("id").single();
}

// @table leave_requests
export function listLeaveRequestsByEmployeeId(employeeId: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select("id, leave_type_id, start_date, end_date, days_requested, status, reason, submission_date, is_half_day, approver_1_id, approver_1_status, approver_2_id, approver_2_status, leave_types(leave_name)")
    .eq("employee_id", employeeId)
    .order("submission_date", { ascending: false })
    .limit(50);
}

// @table leave_requests
export function listLeaveRequestsByEmployeeIdAndLeaveTypeIds(employeeId: string | number | boolean, leaveTypeIds: readonly (string | number)[]) {
  return db()
    .from("leave_requests")
    .select("id, start_date, end_date, days_requested, status, reason, profiles(full_name)")
    .eq("employee_id", employeeId)
    .in("leave_type_id", leaveTypeIds)
    .order("start_date", { ascending: false });
}

// @table leave_requests
export function listLeaveRequestsByEmployeeIdAndStartDateFrom(employeeId: string | number | boolean, startDateFrom: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select("id, start_date, end_date, days_requested, status, leave_types(leave_name)")
    .eq("employee_id", employeeId)
    .gte("start_date", startDateFrom)
    .order("start_date", { ascending: false });
}

// @table leave_requests
export function listLeaveRequestsByEmployeeIdAndStartDateFromAndStartDateToWithStatusApprovedPendingCancellationSubmitted(employeeId: string | number | boolean, startDateFrom: string | number | boolean, startDateTo: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select("leave_type_id, days_requested, status")
    .eq("employee_id", employeeId)
    .in("status", ["approved", "pending_cancellation", "submitted"])
    .gte("start_date", startDateFrom)
    .lte("start_date", startDateTo);
}

// @table leave_requests
export function listLeaveRequestsByEmployeeIdAndStartDateFromWithStatusApproved(employeeId: string | number | boolean, startDateFrom: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select("id, start_date, end_date, days_requested, leave_types(leave_name)")
    .eq("employee_id", employeeId)
    .eq("status", "approved")
    .gte("start_date", startDateFrom)
    .order("start_date")
    .limit(5);
}

// @table leave_requests
export function listLeaveRequestsByEmployeeIdWithStatusSubmitted(employeeId: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select("id, start_date, end_date, days_requested, leave_types(leave_name)")
    .eq("employee_id", employeeId)
    .eq("status", "submitted")
    .order("submission_date", { ascending: false })
    .limit(5);
}

// @table leave_requests
export function listLeaveRequestsByEmployeeIdWithStatusSubmittedApprovedPendingCancellation(employeeId: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select("start_date, end_date")
    .eq("employee_id", employeeId)
    .in("status", ["submitted", "approved", "pending_cancellation"]);
}

// @table leave_requests
export function listLeaveRequestsByEndDateFromAndStartDateToWithStatusApproved(endDateFrom: string | number | boolean, startDateTo: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select("employee_id, start_date, end_date")
    .eq("status", "approved")
    .gte("end_date", endDateFrom)
    .lte("start_date", startDateTo);
}

// @table leave_requests
export function listLeaveRequestsByFilterWithStatusSubmittedPendingCancellation(filter: string) {
  return db()
    .from("leave_requests")
    .select("approver_1_id, approver_1_status, approver_2_id, approver_2_status, status")
    .or(filter)
    .in("status", ["submitted", "pending_cancellation"]);
}

// @table leave_requests
export function listLeaveRequestsByFilterWithStatusSubmittedPendingCancellationOrderedByStartDate(filter: string) {
  return db()
    .from("leave_requests")
    .select(`
        id, leave_type_id, employee_id, start_date, end_date, days_requested, status, reason,
        approver_1_id, approver_2_id, approver_1_status, approver_2_status,
        profiles!leave_requests_employee_id_fkey(full_name, employee_id),
        leave_types(leave_name)
      `)
    .or(filter)
    .in("status", ["submitted", "pending_cancellation"])
    .order("start_date", { ascending: true });
}

// @table leave_requests
export function listLeaveRequestsByStartDateToAndEndDateFromWithStatusApproved(startDateTo: string | number | boolean, endDateFrom: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select(`
        id,
        start_date,
        end_date,
        profiles!employee_id (full_name, department),
        leave_types (leave_name, color)
      `)
    .eq("status", "approved")
    .lte("start_date", startDateTo)
    .gte("end_date", endDateFrom)
    .order("start_date");
}

// @table leave_requests
export function listLeaveRequestsByStartDateToAndEndDateFromWithStatusSubmittedApproved(startDateTo: string | number | boolean, endDateFrom: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select("start_date, end_date, status, profiles!leave_requests_employee_id_fkey(full_name), leave_types(leave_name, color)")
    .in("status", ["submitted", "approved"])
    .lte("start_date", startDateTo)
    .gte("end_date", endDateFrom);
}

// @table leave_requests
export function listLeaveRequestsByStatusesAndStartDateToAndEndDateFrom(statuses: readonly (string | number)[], startDateTo: string | number | boolean, endDateFrom: string | number | boolean) {
  return db()
    .from("leave_requests")
    .select(`
          id, start_date, end_date, days_requested, status, is_half_day, half_day_period,
          profiles!leave_requests_employee_id_fkey(full_name, employee_id, department),
          leave_types(leave_name, color)
        `)
    .in("status", statuses)
    .lte("start_date", startDateTo)
    .gte("end_date", endDateFrom);
}

// @table leave_requests
export function listLeaveRequestsWithStatusApproved() {
  return db()
    .from("leave_requests")
    .select(`start_date, end_date, days_requested, status, employee_id, leave_types(leave_name), profiles(full_name)`)
    .eq("status", "approved");
}

// @table leave_requests
export function listLeaveRequestsWithStatusSubmitted() {
  return db().from("leave_requests").select("status").eq("status", "submitted");
}

// @table leave_requests
export function updateLeaveRequestById(patch: object, id: string | number | boolean) {
  return db().from("leave_requests").update(patch).eq("id", id);
}

// ── leave_seniority_rules ─────────────────────────────────────────────────────

// @table leave_seniority_rules
export function listLeaveSeniorityRules() {
  return db().from("leave_seniority_rules").select("*").order("min_years");
}

// ── leave_types ───────────────────────────────────────────────────────────────

// @table leave_types
export function listLeaveTypes() {
  return db().from("leave_types").select("id, leave_name").order("leave_name");
}

// @table leave_types
export function listLeaveTypesWithIsActive(columns: string) {
  return db().from("leave_types").select(columns as "*").eq("is_active", true).order("leave_name");
}

// @table leave_types
export function listLeaveTypesWithIsActiveOfIdAndLeaveNameAndColor() {
  return db().from("leave_types").select("id, leave_name, color").eq("is_active", true);
}

// @table leave_types
export function listLeaveTypesWithIsReplacementLeave() {
  return db().from("leave_types").select("id").eq("is_replacement_leave", true);
}

// ── leave_year_end_logs ───────────────────────────────────────────────────────

// @table leave_year_end_logs
export function listLeaveYearEndLogs() {
  return db()
    .from("leave_year_end_logs")
    .select("*, profiles(full_name)")
    .order("run_date", { ascending: false })
    .limit(20);
}

// ── nssf_rules ────────────────────────────────────────────────────────────────

// @table nssf_rules
export function insertNssfRules(rows: object | object[]) {
  return db().from("nssf_rules").insert(rows).select("id").single();
}

// @table nssf_rules
export function listNssfRules() {
  return db()
    .from("nssf_rules")
    .select("*")
    .order("contribution_type")
    .order("contributor")
    .order("effective_date", { ascending: false });
}

// @table nssf_rules
export function listNssfRulesWithStatusActive() {
  return db()
    .from("nssf_rules")
    .select("contribution_type, contributor, rate_percent, max_wage_base, apply_cap")
    .eq("status", "active");
}

// @table nssf_rules
export function listNssfRulesWithStatusActiveAndApplyCap() {
  return db()
    .from("nssf_rules")
    .select("max_wage_base, apply_cap")
    .eq("status", "active")
    .eq("apply_cap", true);
}

// @table nssf_rules
export function updateNssfRuleById(patch: object, id: string | number | boolean) {
  return db().from("nssf_rules").update(patch).eq("id", id);
}

// ── overtime_approvals ────────────────────────────────────────────────────────

// @table overtime_approvals
export function countOvertimeApprovalsByApproverIdWithStatusPending(approverId: string | number | boolean) {
  return db()
    .from("overtime_approvals")
    .select("id", { count: "exact", head: true })
    .eq("approver_id", approverId)
    .eq("status", "pending");
}

// @table overtime_approvals
export function listOvertimeApprovalsByApproverIdWithStatusPending(approverId: string | number | boolean) {
  return db()
    .from("overtime_approvals")
    .select(`
          ot_request_id,
          approval_id:id,
          status,
          approver_level,
          overtime_requests!inner(
            id, employee_id, ot_type, hours, reason, status, start_time,
            employee:profiles!overtime_requests_employee_id_fkey(full_name, employee_id)
          )
        `)
    .eq("approver_id", approverId)
    .eq("status", "pending")
    .order("created_at", { ascending: false });
}

// ── overtime_audit_log ────────────────────────────────────────────────────────

// @table overtime_audit_log
export function listOvertimeAuditLog() {
  return db()
    .from("overtime_audit_log")
    .select(`
        id, ot_request_id, action, performed_by, details, created_at,
        performer:profiles!overtime_audit_log_performed_by_fkey(full_name)
      `)
    .order("created_at", { ascending: false })
    .limit(200);
}

// ── overtime_level_config ─────────────────────────────────────────────────────

// @table overtime_level_config
export function listOvertimeLevelConfig() {
  return db().from("overtime_level_config").select("*").order("role_level");
}

// @table overtime_level_config
export function updateOvertimeLevelConfigById(patch: object, id: string | number | boolean) {
  return db().from("overtime_level_config").update(patch).eq("id", id);
}

// ── overtime_limits ───────────────────────────────────────────────────────────

// @table overtime_limits
export function listOvertimeLimits() {
  return db().from("overtime_limits").select("*").order("limit_type");
}

// @table overtime_limits
export function updateOvertimeLimitById(patch: object, id: string | number | boolean) {
  return db().from("overtime_limits").update(patch).eq("id", id);
}

// ── overtime_notifications ────────────────────────────────────────────────────

// @table overtime_notifications
export function countOvertimeNotificationsByRecipientIdWithIsRead(recipientId: string | number | boolean) {
  return db()
    .from("overtime_notifications")
    .select("id", { count: "exact", head: true })
    .eq("recipient_id", recipientId)
    .eq("is_read", false);
}

// @table overtime_notifications
export function listOvertimeNotificationsByRecipientId(recipientId: string | number | boolean) {
  return db()
    .from("overtime_notifications")
    .select(`
          id, event_type, body, subject, sent_at, queued_at, is_read,
          overtime_requests(id, ot_type, hours)
        `)
    .eq("recipient_id", recipientId)
    .order("queued_at", { ascending: false })
    .limit(50);
}

// @table overtime_notifications
export function listOvertimeNotificationsByRecipientIdAndOtRequestIdAndQueuedAtAfter(recipientId: string | number | boolean, otRequestId: string | number | boolean, queuedAtAfter: string | number | boolean) {
  return db()
    .from("overtime_notifications")
    .select("id")
    .eq("recipient_id", recipientId)
    .eq("ot_request_id", otRequestId)
    .gt("queued_at", queuedAtAfter);
}

// @table overtime_notifications
export function updateOvertimeNotificationsByIds(patch: object, ids: readonly (string | number)[]) {
  return db().from("overtime_notifications").update(patch).in("id", ids);
}

// ── overtime_records ──────────────────────────────────────────────────────────

// @table overtime_records
export function countOvertimeRecordsByOvertimeDateFromAndOvertimeDateToWithApproved(overtimeDateFrom: string | number | boolean, overtimeDateTo: string | number | boolean) {
  return db()
    .from("overtime_records")
    .select("id", { count: "exact", head: true })
    .eq("approved", false)
    .gte("overtime_date", overtimeDateFrom)
    .lte("overtime_date", overtimeDateTo);
}

// ── overtime_requests ─────────────────────────────────────────────────────────

// @table overtime_requests
export function listOvertimeRequestsByEmployeeId(employeeId: string | number | boolean) {
  return db()
    .from("overtime_requests")
    .select("*, approvals:overtime_approvals(approver_level, status, label, approver_id, approver:profiles!overtime_approvals_approver_id_fkey(full_name))")
    .eq("employee_id", employeeId)
    .order("created_at", { ascending: false });
}

// ── payroll_audit_log ─────────────────────────────────────────────────────────

// @table payroll_audit_log
export function insertPayrollAuditLog(row: object) {
  return db().from("payroll_audit_log").insert([row]);
}

// @table payroll_audit_log
export function listPayrollAuditLog() {
  return db()
    .from("payroll_audit_log")
    .select("id, period_id, user_id, role_at_time, action, record_type, old_value, new_value, reason, ip_address, created_at, profiles!user_id(full_name), payroll_periods!period_id(label, period_year, period_month)")
    .order("created_at", { ascending: false })
    .limit(200);
}

// ── payroll_component_types ───────────────────────────────────────────────────

// @table payroll_component_types
export function listPayrollComponentTypeCodes() {
  return db().from("payroll_component_types").select("id, code, category, is_system, name");
}

// @table payroll_component_types
export function listPayrollComponentTypes() {
  return db().from("payroll_component_types").select("*").order("sort_order");
}

// ── payroll_cost_allocations ──────────────────────────────────────────────────

// @table payroll_cost_allocations
export function insertPayrollCostAllocations(rows: object | object[]) {
  return db().from("payroll_cost_allocations").insert(rows).select("id").single();
}

// @table payroll_cost_allocations
export function listPayrollCostAllocationsWithStatusPendingConfirmedLocked() {
  return db()
    .from("payroll_cost_allocations")
    .select("id, payroll_entry_id, project_id, wbs_element_id, task_id, department, allocation_method, allocation_percent, allocated_amount, is_overhead, status, note")
    .in("status", ["pending", "confirmed", "locked"]);
}

// @table payroll_cost_allocations
export function updatePayrollCostAllocationById(patch: object, id: string | number | boolean) {
  return db().from("payroll_cost_allocations").update(patch).eq("id", id);
}

// ── payroll_entries ───────────────────────────────────────────────────────────

// @table payroll_entries
export function getPayrollEntryById(id: string | number | boolean) {
  return db()
    .from("payroll_entries")
    .select("*, profiles!payroll_entries_employee_id_fkey(full_name, department, job_title), payroll_periods!period_id(label, period_year, period_month)")
    .eq("id", id)
    .maybeSingle();
}

// @table payroll_entries
export function getPayrollEntryByPeriodIdAndEmployeeId(periodId: string | number | boolean, employeeId: string | number | boolean) {
  return db()
    .from("payroll_entries")
    .select(`
        id, gross_salary, total_deductions, net_salary,
        working_days, present_days, leave_days, ot_hours,
        total_tos, total_nssf_ee, total_nssf_er,
        tax_relief_khr, taxable_income, exchange_rate, status,
        payroll_entry_lines (
          amount, note,
          payroll_component_types (name, category)
        )
      `)
    .eq("period_id", periodId)
    .eq("employee_id", employeeId)
    .single();
}

// @table payroll_entries
export function listPayrollEntries() {
  return db()
    .from("payroll_entries")
    .select("period_id, gross_salary, total_tos, total_nssf_ee, total_nssf_er, net_salary");
}

// @table payroll_entries
export function listPayrollEntriesByEmployeeIdWithStatusDraft(employeeId: string | number | boolean) {
  return db()
    .from("payroll_entries")
    .select("period_id")
    .eq("employee_id", employeeId)
    .neq("status", "draft");
}

// @table payroll_entries
export function listPayrollEntriesByPeriodId(periodId: string | number | boolean) {
  return db()
    .from("payroll_entries")
    .select("id, gross_salary, total_nssf_er, employer_contributions, profiles!employee_id(full_name, department)")
    .eq("period_id", periodId);
}

// @table payroll_entries
export function listPayrollEntriesByPeriodIdOrderedByGrossSalary(periodId: string | number | boolean, columns: string) {
  return db()
    .from("payroll_entries")
    .select(columns as "*")
    .eq("period_id", periodId)
    .order("gross_salary", { ascending: false });
}

// @table payroll_entries
export function listPayrollEntriesByPeriodIds(periodIds: readonly (string | number)[]) {
  return db().from("payroll_entries").select("period_id, net_salary").in("period_id", periodIds);
}

// @table payroll_entries
export function updatePayrollEntriesByPeriodId(patch: object, periodId: string | number | boolean) {
  return db().from("payroll_entries").update(patch).eq("period_id", periodId);
}

// @table payroll_entries
export function upsertPayrollEntry(row: object) {
  return db()
    .from("payroll_entries")
    .upsert([row], { onConflict: "period_id,employee_id" })
    .select("id")
    .single();
}

// ── payroll_entry_lines ───────────────────────────────────────────────────────

// @table payroll_entry_lines
export function deletePayrollEntryLinesByEntryId(entryId: string | number | boolean) {
  return db().from("payroll_entry_lines").delete().eq("entry_id", entryId);
}

// @table payroll_entry_lines
export function insertPayrollEntryLines(rows: object | object[]) {
  return db().from("payroll_entry_lines").insert(rows);
}

// @table payroll_entry_lines
export function listPayrollEntryLinesByEntryId(entryId: string | number | boolean) {
  return db()
    .from("payroll_entry_lines")
    .select("id, amount, note, payroll_component_types(code, name, category)")
    .eq("entry_id", entryId);
}

// @table payroll_entry_lines
export function listPayrollEntryLinesByEntryIds(entryIds: readonly (string | number)[]) {
  return db()
    .from("payroll_entry_lines")
    .select("entry_id, amount, payroll_component_types(code)")
    .in("entry_id", entryIds);
}

// ── payroll_notifications ─────────────────────────────────────────────────────

// @table payroll_notifications
export function countPayrollNotificationsByRecipientIdWithSentAt(recipientId: string | number | boolean) {
  return db()
    .from("payroll_notifications")
    .select("id", { count: "exact", head: true })
    .eq("recipient_id", recipientId)
    .is("sent_at", null);
}

// @table payroll_notifications
export function listPayrollNotificationsByRecipientId(recipientId: string | number | boolean) {
  return db()
    .from("payroll_notifications")
    .select("id, period_id, event_type, subject, body, queued_at, sent_at")
    .eq("recipient_id", recipientId)
    .order("queued_at", { ascending: false })
    .limit(50);
}

// @table payroll_notifications
export function updatePayrollNotificationById(patch: object, id: string | number | boolean) {
  return db().from("payroll_notifications").update(patch).eq("id", id);
}

// @table payroll_notifications
export function updatePayrollNotificationsByIds(patch: object, ids: readonly (string | number)[]) {
  return db().from("payroll_notifications").update(patch).in("id", ids);
}

// ── payroll_periods ───────────────────────────────────────────────────────────

// @table payroll_periods
export function insertPayrollPeriod(row: object) {
  return db().from("payroll_periods").insert([row]);
}

// @table payroll_periods
export function listPayrollPeriods(columns: string) {
  return db()
    .from("payroll_periods")
    .select(columns as "*")
    .order("period_year", { ascending: false })
    .order("period_month", { ascending: false });
}

// @table payroll_periods
export function listPayrollPeriodsByStatuses(statuses: readonly (string | number)[]) {
  return db()
    .from("payroll_periods")
    .select("id, label, period_year, period_month, start_date, end_date, status, rejection_comment")
    .in("status", statuses)
    .order("period_year", { ascending: false })
    .order("period_month", { ascending: false });
}

// @table payroll_periods
export function updatePayrollPeriodById(patch: object, id: string | number | boolean) {
  return db().from("payroll_periods").update(patch).eq("id", id);
}

// ── payroll_seniority_rules ───────────────────────────────────────────────────

// @table payroll_seniority_rules
export function insertPayrollSeniorityRules(rows: object | object[]) {
  return db().from("payroll_seniority_rules").insert(rows).select("id").single();
}

// @table payroll_seniority_rules
export function listPayrollSeniorityRules() {
  return db().from("payroll_seniority_rules").select("*").order("effective_date", { ascending: false });
}

// @table payroll_seniority_rules
export function updatePayrollSeniorityRuleById(patch: object, id: string | number | boolean) {
  return db().from("payroll_seniority_rules").update(patch).eq("id", id);
}

// ── payroll_settings ──────────────────────────────────────────────────────────

// @table payroll_settings
export function getPayrollSettingWithKeyWorkingTime() {
  return db().from("payroll_settings").select("value").eq("key", "working_time").maybeSingle();
}

// @table payroll_settings
export function listPayrollSettingsWithKeyWorkingTimeOtMultipliers() {
  return db().from("payroll_settings").select("key, value").in("key", ["working_time", "ot_multipliers"]);
}

// @table payroll_settings
export function upsertPayrollSettings(rows: object | object[]) {
  return db().from("payroll_settings").upsert(rows, { onConflict: "key" });
}

// ── performance_reviews ───────────────────────────────────────────────────────

// @table performance_reviews
export function listPerformanceReviews() {
  return db().from("performance_reviews").select("status, overall_score");
}

// @table performance_reviews
export function listPerformanceReviewsOrderedByReviewPeriodStart() {
  return db()
    .from("performance_reviews")
    .select(`
        id,
        review_period_start,
        review_period_end,
        review_type,
        overall_score,
        status,
        profiles!inner(full_name, employee_id)
      `)
    .order("review_period_start", { ascending: false })
    .limit(50);
}

// ── positions ─────────────────────────────────────────────────────────────────

// @table positions
export function listPositions() {
  return db().from("positions").select("id, position_name, department_id, grade").order("position_name");
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function countProfilesWithStatusActive() {
  return db().from("profiles").select("id", { count: "exact", head: true }).eq("status", "active");
}

// @table profiles
export function getProfileById(id: string | number | boolean, columns: string) {
  return db().from("profiles").select(columns as "*").eq("id", id).single();
}

// @table profiles
export function getProfileByIdOfRole(id: string | number | boolean) {
  return db().from("profiles").select("role").eq("id", id).maybeSingle();
}

// @table profiles
export function listProfiles(columns: string) {
  return db().from("profiles").select(columns as "*");
}

// @table profiles
export function listProfilesByDepartment(department: string | number | boolean) {
  return db().from("profiles").select("id").eq("department", department);
}

// @table profiles
export function listProfilesByExceptId(exceptId: string | number | boolean) {
  return db().from("profiles").select("id, full_name, department").neq("id", exceptId).order("full_name");
}

// @table profiles
export function listProfilesByIds(ids: readonly (string | number)[]) {
  return db().from("profiles").select("id, full_name, employee_id").in("id", ids);
}

// @table profiles
export function listProfilesOfDepartment() {
  return db().from("profiles").select("department").not("department", "is", null);
}

// @table profiles
export function listProfilesOrderedByEmployeeId(columns: string) {
  return db().from("profiles").select(columns).order("employee_id", { ascending: true, nullsFirst: false });
}

// @table profiles
export function listProfilesOrderedByFullName(columns: string) {
  return db().from("profiles").select(columns as "*").order("full_name");
}

// @table profiles
export function listProfilesWithStatusActive() {
  return db().from("profiles").select("department").eq("status", "active").not("department", "is", null);
}

// @table profiles
export function listProfilesWithStatusActiveOfIdAndFullNameAndDepartment() {
  return db().from("profiles").select("id, full_name, department").eq("status", "active");
}

// @table profiles
export function listProfilesWithStatusActiveOrderedByFullName(columns: string) {
  return db().from("profiles").select(columns as "*").eq("status", "active").order("full_name");
}

// @table profiles
export function updateProfileById(patch: object, id: string | number | boolean) {
  return db().from("profiles").update(patch).eq("id", id);
}

// @table profiles
export function updateProfilesByIds(patch: object, ids: readonly (string | number)[]) {
  return db().from("profiles").update(patch).in("id", ids);
}

// ── projects ──────────────────────────────────────────────────────────────────

// @table projects
export function listProjects() {
  return db().from("projects").select("id, project_name").order("project_name").limit(100);
}

// ── site_locations ────────────────────────────────────────────────────────────

// @table site_locations
export function deleteSiteLocationById(id: string | number | boolean) {
  return db().from("site_locations").delete().eq("id", id);
}

// @table site_locations
export function insertSiteLocation(row: object) {
  return db().from("site_locations").insert([row]);
}

// @table site_locations
export function listSiteLocations() {
  return db().from("site_locations").select("*").order("name");
}

// ── skills ────────────────────────────────────────────────────────────────────

// @table skills
export function listSkills() {
  return db().from("skills").select("id, skill_category");
}

// ── teams ─────────────────────────────────────────────────────────────────────

// @table teams
export function listTeams() {
  return db().from("teams").select("id, team_name, department_id").order("team_name");
}

// ── timesheet_entries ─────────────────────────────────────────────────────────

// @table timesheet_entries
export function listTimesheetEntriesByWeekStartDateFromAndWeekEndDateToWithStatusApproved(weekStartDateFrom: string | number | boolean, weekEndDateTo: string | number | boolean) {
  return db()
    .from("timesheet_entries")
    .select("employee_id, ot_hours, ot_type, timesheets!inner(week_start_date, week_end_date, status)")
    .gte("timesheets.week_start_date", weekStartDateFrom)
    .lte("timesheets.week_end_date", weekEndDateTo)
    .in("timesheets.status", ["approved"]);
}

// ── timesheets ────────────────────────────────────────────────────────────────

// @table timesheets
export function countTimesheetsByWeekStartDateFromAndWeekEndDateToWithStatusApproved(weekStartDateFrom: string | number | boolean, weekEndDateTo: string | number | boolean) {
  return db()
    .from("timesheets")
    .select("id", { count: "exact", head: true })
    .neq("status", "approved")
    .gte("week_start_date", weekStartDateFrom)
    .lte("week_end_date", weekEndDateTo);
}

// @table timesheets
export function listTimesheets(columns: string) {
  return db().from("timesheets").select(columns as "*");
}

// @table timesheets
export function listTimesheetsOrderedByWeekStartDate() {
  return db()
    .from("timesheets")
    .select(`id, week_start_date, total_hours, total_ot_hours, employee_id, profiles(full_name, employee_id)`)
    .order("week_start_date", { ascending: false });
}

// @table timesheets
export function listTimesheetsWithProfiles() {
  return db()
    .from("timesheets")
    .select(`
        id,
        week_start_date,
        week_end_date,
        status,
        total_hours,
        total_ot_hours,
        submission_date,
        profiles!inner(full_name, employee_id)
      `)
    .order("week_start_date", { ascending: false })
    .limit(50);
}

// ── tos_brackets ──────────────────────────────────────────────────────────────

// @table tos_brackets
export function countTosBracketsWithStatusActive() {
  return db().from("tos_brackets").select("id", { count: "exact", head: true }).eq("status", "active");
}

// @table tos_brackets
export function insertTosBrackets(rows: object | object[]) {
  return db().from("tos_brackets").insert(rows).select("id").single();
}

// @table tos_brackets
export function listTosBrackets() {
  return db()
    .from("tos_brackets")
    .select("*")
    .order("effective_date", { ascending: false })
    .order("from_khr");
}

// @table tos_brackets
export function listTosBracketsWithStatusActive() {
  return db()
    .from("tos_brackets")
    .select("from_khr, to_khr, rate_percent, tolerance_khr")
    .eq("status", "active")
    .order("from_khr");
}

// @table tos_brackets
export function updateTosBracketById(patch: object, id: string | number | boolean) {
  return db().from("tos_brackets").update(patch).eq("id", id);
}

// ── tos_dependent_relief ──────────────────────────────────────────────────────

// @table tos_dependent_relief
export function insertTosDependentRelief(rows: object | object[]) {
  return db().from("tos_dependent_relief").insert(rows).select("id").single();
}

// @table tos_dependent_relief
export function listTosDependentRelief() {
  return db().from("tos_dependent_relief").select("*").order("effective_date", { ascending: false });
}

// @table tos_dependent_relief
export function listTosDependentReliefWithStatusActive() {
  return db().from("tos_dependent_relief").select("relief_type, amount_khr").eq("status", "active");
}

// @table tos_dependent_relief
export function updateTosDependentReliefById(patch: object, id: string | number | boolean) {
  return db().from("tos_dependent_relief").update(patch).eq("id", id);
}

// ── tos_exchange_rates ────────────────────────────────────────────────────────

// @table tos_exchange_rates
export function getTosExchangeRateByPeriodYearAndPeriodMonth(periodYear: string | number | boolean, periodMonth: string | number | boolean, columns: string) {
  return db()
    .from("tos_exchange_rates")
    .select(columns as "*")
    .eq("period_year", periodYear)
    .eq("period_month", periodMonth)
    .maybeSingle();
}

// @table tos_exchange_rates
export function listTosExchangeRates() {
  return db()
    .from("tos_exchange_rates")
    .select("*")
    .order("period_year", { ascending: false })
    .order("period_month", { ascending: false });
}

// @table tos_exchange_rates
export function updateTosExchangeRateById(patch: object, id: string | number | boolean) {
  return db().from("tos_exchange_rates").update(patch).eq("id", id);
}

// @table tos_exchange_rates
export function upsertTosExchangeRates(rows: object | object[]) {
  return db()
    .from("tos_exchange_rates")
    .upsert(rows, { onConflict: "period_year,period_month" })
    .select("id")
    .single();
}

// ── tos_flat_rates ────────────────────────────────────────────────────────────

// @table tos_flat_rates
export function listTosFlatRates() {
  return db().from("tos_flat_rates").select("*").order("effective_date", { ascending: false });
}

// @table tos_flat_rates
export function updateTosFlatRateById(patch: object, id: string | number | boolean) {
  return db().from("tos_flat_rates").update(patch).eq("id", id);
}

// ── training_certificates ─────────────────────────────────────────────────────

// @table training_certificates
export function listTrainingCertificatesByExpiryDateToAndExpiryDateFrom(expiryDateTo: string | number | boolean, expiryDateFrom: string | number | boolean, columns: string) {
  return db()
    .from("training_certificates")
    .select(columns as "*")
    .lte("expiry_date", expiryDateTo)
    .gte("expiry_date", expiryDateFrom);
}

// ── training_records ──────────────────────────────────────────────────────────

// @table training_records
export function listTrainingRecords() {
  return db().from("training_records").select("status");
}

// @table training_records
export function listTrainingRecordsOrderedByEnrollmentDate() {
  return db()
    .from("training_records")
    .select(`
        id,
        enrollment_date,
        completion_date,
        status,
        score,
        profiles(full_name, employee_id),
        training_courses(course_name, provider, duration_hours)
      `)
    .order("enrollment_date", { ascending: false })
    .limit(50);
}

// ── user_roles ────────────────────────────────────────────────────────────────

// @table user_roles
export function listUserRoles() {
  return db().from("user_roles").select("user_id, role_code, roles(code, name, level, type)");
}

// @table user_roles
export function listUserRolesByUserIdWithRoleCodeHRManagerAdmin(userId: string | number | boolean) {
  return db()
    .from("user_roles")
    .select("role_code")
    .eq("user_id", userId)
    .in("role_code", ["HR_Manager", "admin"]);
}

// ── work_shifts ───────────────────────────────────────────────────────────────

// @table work_shifts
export function deleteWorkShiftById(id: string | number | boolean) {
  return db().from("work_shifts").delete().eq("id", id);
}

// @table work_shifts
export function insertWorkShifts(rows: object | object[]) {
  return db().from("work_shifts").insert(rows);
}

// @table work_shifts
export function listWorkShifts() {
  return db().from("work_shifts").select("*").order("name");
}
