// Data access for the construction-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── check_task_quality_holdpoints ─────────────────────────────────────────────

// @table check_task_quality_holdpoints
export function checkTaskQualityHoldpoints(args: object) {
  return db().rpc("check_task_quality_holdpoints", args);
}

// ── get_site_manpower_variance ────────────────────────────────────────────────

// @table get_site_manpower_variance
export function getSiteManpowerVariance(args: object) {
  return db().rpc("get_site_manpower_variance", args);
}

// ── hse_incidents ─────────────────────────────────────────────────────────────

// @table hse_incidents
export function countHseIncidents() {
  return db().from("hse_incidents").select("*", { count: "exact", head: true });
}

// @table hse_incidents
export function insertHseIncident(row: object) {
  return db().from("hse_incidents").insert([row]);
}

// @table hse_incidents
export function listHseIncidents() {
  return db().from("hse_incidents").select("*").order("incident_date", { ascending: false }).limit(200);
}

// @table hse_incidents
export function updateHseIncidentById(patch: object, id: string | number | boolean) {
  return db().from("hse_incidents").update(patch).eq("id", id);
}

// ── hse_observations ──────────────────────────────────────────────────────────

// @table hse_observations
export function countHseObservations() {
  return db().from("hse_observations").select("*", { count: "exact", head: true });
}

// @table hse_observations
export function insertHseObservation(row: object) {
  return db().from("hse_observations").insert([row]);
}

// @table hse_observations
export function listHseObservations() {
  return db().from("hse_observations").select("*").order("observation_date", { ascending: false }).limit(200);
}

// @table hse_observations
export function updateHseObservationById(patch: object, id: string | number | boolean) {
  return db().from("hse_observations").update(patch).eq("id", id);
}

// ── hse_permits ───────────────────────────────────────────────────────────────

// @table hse_permits
export function countHsePermits() {
  return db().from("hse_permits").select("*", { count: "exact", head: true });
}

// @table hse_permits
export function insertHsePermit(row: object) {
  return db().from("hse_permits").insert([row]);
}

// @table hse_permits
export function listHsePermits() {
  return db().from("hse_permits").select("*").order("created_at", { ascending: false }).limit(200);
}

// @table hse_permits
export function updateHsePermitById(patch: object, id: string | number | boolean) {
  return db().from("hse_permits").update(patch).eq("id", id);
}

// ── hse_risk_assessments ──────────────────────────────────────────────────────

// @table hse_risk_assessments
export function countHseRiskAssessments() {
  return db().from("hse_risk_assessments").select("*", { count: "exact", head: true });
}

// @table hse_risk_assessments
export function insertHseRiskAssessment(row: object) {
  return db().from("hse_risk_assessments").insert([row]);
}

// @table hse_risk_assessments
export function listHseRiskAssessments() {
  return db().from("hse_risk_assessments").select("*").order("created_at", { ascending: false }).limit(200);
}

// @table hse_risk_assessments
export function updateHseRiskAssessmentById(patch: object, id: string | number | boolean) {
  return db().from("hse_risk_assessments").update(patch).eq("id", id);
}

// ── hse_toolbox_talks ─────────────────────────────────────────────────────────

// @table hse_toolbox_talks
export function countHseToolboxTalks() {
  return db().from("hse_toolbox_talks").select("*", { count: "exact", head: true });
}

// @table hse_toolbox_talks
export function insertHseToolboxTalk(row: object) {
  return db().from("hse_toolbox_talks").insert([row]);
}

// @table hse_toolbox_talks
export function listHseToolboxTalks() {
  return db().from("hse_toolbox_talks").select("*").order("talk_date", { ascending: false }).limit(200);
}

// @table hse_toolbox_talks
export function updateHseToolboxTalkById(patch: object, id: string | number | boolean) {
  return db().from("hse_toolbox_talks").update(patch).eq("id", id);
}

// ── inspection_requests ───────────────────────────────────────────────────────

// @table inspection_requests
export function countInspectionRequests() {
  return db().from("inspection_requests").select("*", { count: "exact", head: true });
}

// @table inspection_requests
export function insertInspectionRequest(row: object) {
  return db().from("inspection_requests").insert([row]);
}

// @table inspection_requests
export function listInspectionRequestsByProjectId(projectId: string | number | boolean) {
  return db()
    .from("inspection_requests")
    .select("*, wbs_tasks(task_code, task_name)")
    .eq("project_id", projectId)
    .order("request_date", { ascending: false })
    .limit(200);
}

// @table inspection_requests
export function updateInspectionRequestById(patch: object, id: string | number | boolean) {
  return db().from("inspection_requests").update(patch).eq("id", id);
}

// ── ncrs ──────────────────────────────────────────────────────────────────────

// @table ncrs
export function countNcrs() {
  return db().from("ncrs").select("*", { count: "exact", head: true });
}

// @table ncrs
export function insertNcr(row: object) {
  return db().from("ncrs").insert([row]);
}

// @table ncrs
export function listNcrsByProjectId(projectId: string | number | boolean) {
  return db()
    .from("ncrs")
    .select("*")
    .eq("project_id", projectId)
    .order("created_at", { ascending: false })
    .limit(200);
}

// @table ncrs
export function updateNcrById(patch: object, id: string | number | boolean) {
  return db().from("ncrs").update(patch).eq("id", id);
}

// ── push_equipment_standby_to_delay ───────────────────────────────────────────

// @table push_equipment_standby_to_delay
export function pushEquipmentStandbyToDelay(args: object) {
  return db().rpc("push_equipment_standby_to_delay", args);
}

// ── site_daily_reports ────────────────────────────────────────────────────────

// @table site_daily_reports
export function countSiteDailyReports() {
  return db().from("site_daily_reports").select("*", { count: "exact", head: true });
}

// ── site_equipment ────────────────────────────────────────────────────────────

// @table site_equipment
export function countSiteEquipment() {
  return db().from("site_equipment").select("*", { count: "exact", head: true });
}

// @table site_equipment
export function insertSiteEquipment(row: object) {
  return db().from("site_equipment").insert([row]);
}

// @table site_equipment
export function listSiteEquipmentByProjectId(projectId: string | number | boolean) {
  return db()
    .from("site_equipment")
    .select("*, wbs_tasks(task_code, task_name)")
    .eq("project_id", projectId)
    .order("date", { ascending: false })
    .limit(300);
}

// @table site_equipment
export function updateSiteEquipmentById(patch: object, id: string | number | boolean) {
  return db().from("site_equipment").update(patch).eq("id", id);
}

// ── site_manpower ─────────────────────────────────────────────────────────────

// @table site_manpower
export function countSiteManpower() {
  return db().from("site_manpower").select("*", { count: "exact", head: true });
}

// @table site_manpower
export function insertSiteManpower(row: object) {
  return db().from("site_manpower").insert([row]);
}

// @table site_manpower
export function listSiteManpowerByProjectId(projectId: string | number | boolean) {
  return db()
    .from("site_manpower")
    .select("*, wbs_tasks(task_code, task_name), subcontracts(subcontract_no, scope_of_work)")
    .eq("project_id", projectId)
    .order("report_date", { ascending: false })
    .limit(300);
}

// @table site_manpower
export function updateSiteManpowerById(patch: object, id: string | number | boolean) {
  return db().from("site_manpower").update(patch).eq("id", id);
}

// ── site_progress_photos ──────────────────────────────────────────────────────

// @table site_progress_photos
export function countSiteProgressPhotos() {
  return db().from("site_progress_photos").select("*", { count: "exact", head: true });
}

// @table site_progress_photos
export function deleteSiteProgressPhotoById(id: string | number | boolean) {
  return db().from("site_progress_photos").delete().eq("id", id);
}

// @table site_progress_photos
export function insertSiteProgressPhoto(row: object) {
  return db().from("site_progress_photos").insert([row]);
}

// @table site_progress_photos
export function listSiteProgressPhotosByProjectId(projectId: string | number | boolean) {
  return db()
    .from("site_progress_photos")
    .select("*, wbs_tasks(task_code, task_name)")
    .eq("project_id", projectId)
    .order("taken_at", { ascending: false })
    .limit(300);
}

// ── subcontract_back_charges ──────────────────────────────────────────────────

// @table subcontract_back_charges
export function insertSubcontractBackCharge(row: object) {
  return db().from("subcontract_back_charges").insert([row]);
}

// ── subcontracts ──────────────────────────────────────────────────────────────

// @table subcontracts
export function listSubcontractsByProjectId(projectId: string | number | boolean) {
  return db()
    .from("subcontracts")
    .select("id, subcontract_no, scope_of_work")
    .eq("project_id", projectId)
    .order("subcontract_no", { ascending: true });
}

// ── wbs_tasks ─────────────────────────────────────────────────────────────────

// @table wbs_tasks
export function listWbsTasksByProjectId(projectId: string | number | boolean) {
  return db()
    .from("wbs_tasks")
    .select("id, task_code, task_name")
    .eq("project_id", projectId)
    .order("task_code", { ascending: true })
    .limit(200);
}
