// Data access for the mobile-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── mobile_device_registrations ───────────────────────────────────────────────

// @table mobile_device_registrations
export function countMobileDeviceRegistrations() {
  return db().from("mobile_device_registrations").select("id", { count: "exact", head: true });
}

// @table mobile_device_registrations
export function countMobileDeviceRegistrationsWithIsActive() {
  return db()
    .from("mobile_device_registrations")
    .select("id", { count: "exact", head: true })
    .eq("is_active", true);
}

// @table mobile_device_registrations
export function listMobileDeviceRegistrations() {
  return db().from("mobile_device_registrations").select("*").order("registered_at", { ascending: false });
}

// ── mobile_sync_queue ─────────────────────────────────────────────────────────

// @table mobile_sync_queue
export function countMobileSyncQueueWithStatusPending() {
  return db().from("mobile_sync_queue").select("id", { count: "exact", head: true }).eq("status", "pending");
}

// @table mobile_sync_queue
export function listMobileSyncQueue() {
  return db().from("mobile_sync_queue").select("*").order("created_at", { ascending: false }).limit(20);
}

// ── mobile_sync_sessions ──────────────────────────────────────────────────────

// @table mobile_sync_sessions
export function countMobileSyncSessionsByStartedAtFrom(startedAtFrom: string | number | boolean) {
  return db()
    .from("mobile_sync_sessions")
    .select("id", { count: "exact", head: true })
    .gte("started_at", startedAtFrom);
}

// @table mobile_sync_sessions
export function listMobileSyncSessions() {
  return db().from("mobile_sync_sessions").select("*").order("started_at", { ascending: false }).limit(20);
}
