// Data access for the tasks-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── departments ───────────────────────────────────────────────────────────────

// @table departments
export function getDepartmentById(id: string | number | boolean) {
  return db().from("departments").select("department_head").eq("id", id).maybeSingle();
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function listProfilesByDepartmentIds(departmentIds: readonly (string | number)[]) {
  return db()
    .from("profiles")
    .select("id, full_name, job_title, avatar_url")
    .in("department_id", departmentIds)
    .order("full_name");
}

// ── wbs_audit_log ─────────────────────────────────────────────────────────────

// @table wbs_audit_log
export function listWbsAuditLog() {
  return db()
    .from("wbs_audit_log")
    .select("id, action, new_value, created_at, wbs_task_id")
    .order("created_at", { ascending: false })
    .limit(150);
}

// @table wbs_audit_log
export function listWbsAuditLogWithFieldNameOwnerName() {
  return db()
    .from("wbs_audit_log")
    .select("*")
    .eq("field_name", "owner_name")
    .order("created_at", { ascending: false })
    .limit(500);
}

// ── wbs_nodes ─────────────────────────────────────────────────────────────────

// @table wbs_nodes
export function listWbsNodesByProjectId(projectId: string | number | boolean) {
  return db().from("wbs_nodes").select("*").eq("project_id", projectId);
}

// ── wbs_tasks ─────────────────────────────────────────────────────────────────

// @table wbs_tasks
export function deleteWbsTaskByIdReturning(id: string | number | boolean) {
  return db().from("wbs_tasks").delete().eq("id", id).select("id").maybeSingle();
}

// @table wbs_tasks
export function getWbsTaskById(id: string | number | boolean) {
  return db().from("wbs_tasks").select("*").eq("id", id).single();
}

// @table wbs_tasks
export function listWbsTasks() {
  return db()
    .from("wbs_tasks")
    .select("*, projects(project_code, project_name)")
    .order("end_date", { ascending: true, nullsFirst: false })
    .limit(500);
}

// @table wbs_tasks
export function listWbsTasksByDepartmentIds(departmentIds: readonly (string | number)[]) {
  return db().from("wbs_tasks").select("*").in("department_id", departmentIds);
}

// @table wbs_tasks
export function updateWbsTaskById(patch: object, id: string | number | boolean) {
  return db().from("wbs_tasks").update(patch).eq("id", id);
}
