// Data access for the settings-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── approval_thresholds ───────────────────────────────────────────────────────

// @table approval_thresholds
export function listApprovalThresholds() {
  return db().from("approval_thresholds").select("*").order("module").order("tier");
}

// @table approval_thresholds
export function upsertApprovalThresholds(rows: object | object[]) {
  return db().from("approval_thresholds").upsert(rows, { onConflict: "module, tier" });
}

// ── companies ─────────────────────────────────────────────────────────────────

// @table companies
export function getCompany() {
  return db().from("companies").select("*").limit(1).single();
}

// @table companies
export function updateCompanyById(patch: object, id: string | number | boolean) {
  return db().from("companies").update(patch).eq("id", id);
}

// ── departments ───────────────────────────────────────────────────────────────

// @table departments
export function listDepartments() {
  return db().from("departments").select("id, department_name").order("department_name", { ascending: true });
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function getProfileById(id: string | number | boolean, columns: string) {
  return db().from("profiles").select(columns as "*").eq("id", id).single();
}

// @table profiles
export function listProfiles() {
  return db()
    .from("profiles")
    .select("id, employee_id, full_name, email, job_title, department, department_id, level, role, status, report_to, account_status, last_login_at, password_changed_at, first_login_at")
    .order("employee_id", { ascending: true, nullsFirst: false });
}

// @table profiles
export function updateProfileById(patch: object, id: string | number | boolean) {
  return db().from("profiles").update(patch).eq("id", id);
}

// ── role_permissions ──────────────────────────────────────────────────────────

// @table role_permissions
export function listRolePermissions() {
  return db().from("role_permissions").select("module, action");
}

// @table role_permissions
export function listRolePermissionsByRoleCode(roleCode: string | number | boolean) {
  return db().from("role_permissions").select("*").eq("role_code", roleCode);
}

// @table role_permissions
export function upsertRolePermissions(rows: object | object[]) {
  return db().from("role_permissions").upsert(rows, { onConflict: "role_code, module, action" });
}

// ── roles ─────────────────────────────────────────────────────────────────────

// @table roles
export function listRoles() {
  return db().from("roles").select("*").order("level", { ascending: true, nullsFirst: false });
}

// @table roles
export function listRolesOfCodeAndNameAndType() {
  return db().from("roles").select("code, name, type");
}

// ── user_roles ────────────────────────────────────────────────────────────────

// @table user_roles
export function deleteUserRolesByUserIdAndRoleCodes(userId: string | number | boolean, roleCodes: readonly (string | number)[]) {
  return db().from("user_roles").delete().eq("user_id", userId).in("role_code", roleCodes);
}

// @table user_roles
export function insertUserRoles(rows: object | object[]) {
  return db().from("user_roles").insert(rows);
}

// @table user_roles
export function listUserRolesByUserId(userId: string | number | boolean) {
  return db().from("user_roles").select("role_code").eq("user_id", userId);
}
