// Data access for the stakeholders-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function getProfileById(id: string | number | boolean) {
  return db().from("profiles").select("role").eq("id", id).single();
}

// @table profiles
export function listProfiles() {
  return db().from("profiles").select("id, full_name, job_title, email, department").order("full_name");
}

// @table profiles
export function listProfilesWithStatusActive() {
  return db()
    .from("profiles")
    .select("id, employee_id, full_name, email, job_title, department, status")
    .eq("status", "active")
    .order("full_name");
}

// ── project_stakeholder_teams ─────────────────────────────────────────────────

// @table project_stakeholder_teams
export function insertProjectStakeholderTeamReturning(row: object) {
  return db().from("project_stakeholder_teams").insert([row]).select("id").single();
}

// @table project_stakeholder_teams
export function listProjectStakeholderTeamsByProjectIdAndStakeholderId(projectId: string | number | boolean, stakeholderId: string | number | boolean) {
  return db()
    .from("project_stakeholder_teams")
    .select("id")
    .eq("project_id", projectId)
    .eq("stakeholder_id", stakeholderId);
}

// @table project_stakeholder_teams
export function listProjectStakeholderTeamsByProjectIdAndStakeholderIdOfId(projectId: string | number | boolean, stakeholderId: string | number | boolean) {
  return db()
    .from("project_stakeholder_teams")
    .select("id")
    .eq("project_id", projectId)
    .eq("stakeholder_id", stakeholderId)
    .limit(1);
}

// ── project_stakeholders ──────────────────────────────────────────────────────

// @table project_stakeholders
export function listProjectStakeholders() {
  return db().from("project_stakeholders").select("stakeholder_id, project_id, created_at");
}

// ── project_team_members ──────────────────────────────────────────────────────

// @table project_team_members
export function listProjectTeamMembersByProjectStakeholderTeamIds(projectStakeholderTeamIds: readonly (string | number)[]) {
  return db()
    .from("project_team_members")
    .select("stakeholder_staff_id")
    .in("project_stakeholder_team_id", projectStakeholderTeamIds);
}

// @table project_team_members
export function upsertProjectTeamMembers(rows: object | object[]) {
  return db()
    .from("project_team_members")
    .upsert(rows, { onConflict: "project_stakeholder_team_id,stakeholder_staff_id", ignoreDuplicates: true });
}

// ── roles ─────────────────────────────────────────────────────────────────────

// @table roles
export function listRoles() {
  return db().from("roles").select("code, name").order("level");
}

// ── stakeholder_staff ─────────────────────────────────────────────────────────

// @table stakeholder_staff
export function deleteStakeholderStaffById(id: string | number | boolean) {
  return db().from("stakeholder_staff").delete().eq("id", id);
}

// @table stakeholder_staff
export function insertStakeholderStaff(rows: object | object[]) {
  return db().from("stakeholder_staff").insert(rows);
}

// @table stakeholder_staff
export function insertStakeholderStaffReturning(row: object) {
  return db().from("stakeholder_staff").insert([row]).select("id").single();
}

// @table stakeholder_staff
export function insertStakeholderStaffRow(row: object) {
  return db().from("stakeholder_staff").insert([row]);
}

// @table stakeholder_staff
export function listStakeholderStaff() {
  return db().from("stakeholder_staff").select("*");
}

// @table stakeholder_staff
export function listStakeholderStaffByStakeholderId(stakeholderId: string | number | boolean) {
  return db()
    .from("stakeholder_staff")
    .select("id, profile_id, full_name, job_title, email")
    .eq("stakeholder_id", stakeholderId);
}

// @table stakeholder_staff
export function listStakeholderStaffByStakeholderIdOrderedByIsPrimaryContactAndFullName(stakeholderId: string | number | boolean) {
  return db()
    .from("stakeholder_staff")
    .select("*")
    .eq("stakeholder_id", stakeholderId)
    .order("is_primary_contact", { ascending: false })
    .order("full_name");
}

// @table stakeholder_staff
export function updateStakeholderStaffById(patch: object, id: string | number | boolean) {
  return db().from("stakeholder_staff").update(patch).eq("id", id);
}

// @table stakeholder_staff
export function updateStakeholderStaffByStakeholderIdAndExceptId(patch: object, stakeholderId: string | number | boolean, exceptId: string | number | boolean) {
  return db().from("stakeholder_staff").update(patch).eq("stakeholder_id", stakeholderId).neq("id", exceptId);
}

// @table stakeholder_staff
export function updateStakeholderStaffByStakeholderIdWithId(patch: object, stakeholderId: string | number | boolean) {
  return db().from("stakeholder_staff").update(patch).eq("stakeholder_id", stakeholderId).neq("id", "");
}

// ── stakeholder_teams ─────────────────────────────────────────────────────────

// @table stakeholder_teams
export function deleteStakeholderTeamById(id: string | number | boolean) {
  return db().from("stakeholder_teams").delete().eq("id", id);
}

// @table stakeholder_teams
export function insertStakeholderTeam(row: object) {
  return db().from("stakeholder_teams").insert([row]);
}

// @table stakeholder_teams
export function listStakeholderTeamsByStakeholderId(stakeholderId: string | number | boolean) {
  return db().from("stakeholder_teams").select("*").eq("stakeholder_id", stakeholderId).order("team_name");
}

// @table stakeholder_teams
export function updateStakeholderTeamById(patch: object, id: string | number | boolean) {
  return db().from("stakeholder_teams").update(patch).eq("id", id);
}

// ── stakeholder_templates ─────────────────────────────────────────────────────

// @table stakeholder_templates
export function insertStakeholderTemplatesReturning(rows: object | object[]) {
  return db().from("stakeholder_templates").insert(rows).select().single();
}

// @table stakeholder_templates
export function listStakeholderTemplates() {
  return db().from("stakeholder_templates").select("*").order("name", { ascending: true });
}

// @table stakeholder_templates
export function updateStakeholderTemplateByIdReturning(patch: object, id: string | number | boolean) {
  return db().from("stakeholder_templates").update(patch).eq("id", id).select().single();
}

// ── stakeholders ──────────────────────────────────────────────────────────────

// @table stakeholders
export function deleteStakeholderById(id: string | number | boolean) {
  return db().from("stakeholders").delete().eq("id", id);
}

// @table stakeholders
export function insertStakeholdersReturning(rows: object | object[]) {
  return db().from("stakeholders").insert(rows).select().single();
}

// @table stakeholders
export function listStakeholders() {
  return db().from("stakeholders").select("*").order("organization_name");
}

// @table stakeholders
export function updateStakeholderById(patch: object, id: string | number | boolean) {
  return db().from("stakeholders").update(patch).eq("id", id);
}

// ── template_placeholder_teams ────────────────────────────────────────────────

// @table template_placeholder_teams
export function insertTemplatePlaceholderTeams(rows: object | object[]) {
  return db().from("template_placeholder_teams").insert(rows);
}

// @table template_placeholder_teams
export function updateTemplatePlaceholderTeamById(patch: object, id: string | number | boolean) {
  return db().from("template_placeholder_teams").update(patch).eq("id", id);
}

// ── template_placeholders ─────────────────────────────────────────────────────

// @table template_placeholders
export function deleteTemplatePlaceholderById(id: string | number | boolean) {
  return db().from("template_placeholders").delete().eq("id", id);
}

// @table template_placeholders
export function insertTemplatePlaceholdersReturning(rows: object | object[]) {
  return db().from("template_placeholders").insert(rows).select().single();
}

// @table template_placeholders
export function listTemplatePlaceholders() {
  return db().from("template_placeholders").select("id, template_id");
}

// @table template_placeholders
export function updateTemplatePlaceholderById(patch: object, id: string | number | boolean) {
  return db().from("template_placeholders").update(patch).eq("id", id);
}
