// Data access for the wbs-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── clone_wbs_template_to_project ─────────────────────────────────────────────

// @table clone_wbs_template_to_project
export function cloneWbsTemplateToProject(args: object) {
  return db().rpc("clone_wbs_template_to_project", args);
}

// ── close_weekly_plan ─────────────────────────────────────────────────────────

// @table close_weekly_plan
export function closeWeeklyPlan(args: object) {
  return db().rpc("close_weekly_plan", args);
}

// ── departments ───────────────────────────────────────────────────────────────

// @table departments
export function getDepartmentById(id: string | number | boolean) {
  return db().from("departments").select("department_head").eq("id", id).maybeSingle();
}

// @table departments
export function listDepartments() {
  return db().from("departments").select("id, department_code, department_name").order("department_name");
}

// ── generate_wbs_from_master_library_items ────────────────────────────────────

// @table generate_wbs_from_master_library_items
export function generateWbsFromMasterLibraryItems(args: object) {
  return db().rpc("generate_wbs_from_master_library_items", args);
}

// ── import_master_wbs ─────────────────────────────────────────────────────────

// @table import_master_wbs
export function importMasterWbs(args: object) {
  return db().rpc("import_master_wbs", args);
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function getProfileById(id: string | number | boolean, columns: string) {
  return db().from("profiles").select(columns as "*").eq("id", id).maybeSingle();
}

// @table profiles
export function getProfileByIdOfRole(id: string | number | boolean) {
  return db().from("profiles").select("role").eq("id", id).single();
}

// @table profiles
export function listProfiles() {
  return db().from("profiles").select("id, full_name, role, avatar_url, department").order("full_name");
}

// @table profiles
export function listProfilesOfIdAndFullName() {
  return db().from("profiles").select("id, full_name");
}

// ── task_constraints ──────────────────────────────────────────────────────────

// @table task_constraints
export function listTaskConstraintsByTaskIds(taskIds: readonly (string | number)[]) {
  return db()
    .from("task_constraints")
    .select("task_id, constraint_type, status, source, notes")
    .in("task_id", taskIds);
}

// @table task_constraints
export function upsertTaskConstraint(row: object) {
  return db().from("task_constraints").upsert([row], { onConflict: "task_id,constraint_type" });
}

// ── task_recurrences ──────────────────────────────────────────────────────────

// @table task_recurrences
export function insertTaskRecurrence(row: object) {
  return db().from("task_recurrences").insert([row]);
}

// ── wbs_audit_log ─────────────────────────────────────────────────────────────

// @table wbs_audit_log
export function insertWbsAuditLog(row: object) {
  return db().from("wbs_audit_log").insert([row]);
}

// @table wbs_audit_log
export function insertWbsAuditLogReturning(row: object) {
  return db().from("wbs_audit_log").insert([row]).select("id").single();
}

// @table wbs_audit_log
export function listWbsAuditLogByProjectIdWithActionProgressUpdatedApprovedRejected(projectId: string | number | boolean) {
  return db()
    .from("wbs_audit_log")
    .select("wbs_task_id, action, created_at")
    .eq("project_id", projectId)
    .in("action", ["Progress Updated", "Approved", "Rejected"])
    .order("created_at", { ascending: true });
}

// @table wbs_audit_log
export function listWbsAuditLogByProjectIdWithFieldNameOwnerName(projectId: string | number | boolean) {
  return db()
    .from("wbs_audit_log")
    .select("*")
    .eq("project_id", projectId)
    .eq("field_name", "owner_name")
    .order("created_at", { ascending: false });
}

// @table wbs_audit_log
export function listWbsAuditLogByWbsTaskId(wbsTaskId: string | number | boolean) {
  return db()
    .from("wbs_audit_log")
    .select("*")
    .eq("wbs_task_id", wbsTaskId)
    .order("created_at", { ascending: false });
}

// ── wbs_node_quantities ───────────────────────────────────────────────────────

// @table wbs_node_quantities
export function listWbsNodeQuantitiesByWbsNodeIds(wbsNodeIds: readonly (string | number)[]) {
  return db().from("wbs_node_quantities").select("wbs_node_id, value").in("wbs_node_id", wbsNodeIds);
}

// @table wbs_node_quantities
export function listWbsNodeQuantitiesByWbsNodeIdsWithMetricCodeGFA(wbsNodeIds: readonly (string | number)[]) {
  return db()
    .from("wbs_node_quantities")
    .select("wbs_node_id, value")
    .eq("metric_code", "GFA")
    .in("wbs_node_id", wbsNodeIds);
}

// ── wbs_nodes ─────────────────────────────────────────────────────────────────

// @table wbs_nodes
export function deleteWbsNodeById(id: string | number | boolean) {
  return db().from("wbs_nodes").delete().eq("id", id);
}

// @table wbs_nodes
export function deleteWbsNodeByIdReturning(id: string | number | boolean) {
  return db().from("wbs_nodes").delete().eq("id", id).select("id").maybeSingle();
}

// @table wbs_nodes
export function deleteWbsNodesByProjectIdWithStatusActive(projectId: string | number | boolean) {
  return db().from("wbs_nodes").delete().eq("project_id", projectId).eq("status", "active");
}

// @table wbs_nodes
export function getWbsNodeById(id: string | number | boolean) {
  return db().from("wbs_nodes").select("wbs_code, wbs_name, full_path").eq("id", id).single();
}

// @table wbs_nodes
export function insertWbsNode(row: object) {
  return db().from("wbs_nodes").insert([row]);
}

// @table wbs_nodes
export function insertWbsNodeReturning(row: object, columns: string) {
  return db().from("wbs_nodes").insert([row]).select(columns).single();
}

// @table wbs_nodes
export function insertWbsNodes(rows: object | object[]) {
  return db().from("wbs_nodes").insert(rows);
}

// @table wbs_nodes
export function listWbsNodesByProjectId(columns: string, projectId: string | number | boolean) {
  return db()
    .from("wbs_nodes")
    .select(columns)
    .eq("project_id", projectId)
    .order("sort_order", { ascending: true, nullsFirst: false });
}

// @table wbs_nodes
export function listWbsNodesByProjectIdAndParentId(projectId: string | number | boolean | null, parentId: string | number | boolean | null) {
  return db()
    .from("wbs_nodes")
    .select("wbs_code, sort_order")
    .eq("project_id", projectId)
    .eq("parent_id", parentId);
}

// @table wbs_nodes
export function listWbsNodesByProjectIdNullsLast(projectId: string | number | boolean) {
  return db()
    .from("wbs_nodes")
    .select("*")
    .eq("project_id", projectId)
    .order("sort_order", { ascending: true, nullsFirst: false });
}

// @table wbs_nodes
export function listWbsNodesByProjectIdOfIdAndWbsCode(projectId: string | number | boolean, columns: string) {
  return db().from("wbs_nodes").select(columns as "*").eq("project_id", projectId);
}

// @table wbs_nodes
export function listWbsNodesByProjectIdOrderedByFullPath(projectId: string | number | boolean) {
  return db()
    .from("wbs_nodes")
    .select("*")
    .eq("project_id", projectId)
    .order("full_path", { ascending: true, nullsFirst: false });
}

// @table wbs_nodes
export function listWbsNodesByProjectIdOrderedBySortOrder(projectId: string | number | boolean) {
  return db().from("wbs_nodes").select("*").eq("project_id", projectId).order("sort_order");
}

// @table wbs_nodes
export function updateWbsNodeById(patch: object, id: string | number | boolean) {
  return db().from("wbs_nodes").update(patch).eq("id", id);
}

// ── wbs_subscriptions ─────────────────────────────────────────────────────────

// @table wbs_subscriptions
export function deleteWbsSubscriptionsByWbsNodeIdAndUserId(wbsNodeId: string | number | boolean, userId: string | number | boolean) {
  return db().from("wbs_subscriptions").delete().eq("wbs_node_id", wbsNodeId).eq("user_id", userId);
}

// @table wbs_subscriptions
export function getWbsSubscriptionByWbsNodeIdAndUserId(wbsNodeId: string | number | boolean, userId: string | number | boolean) {
  return db()
    .from("wbs_subscriptions")
    .select("id")
    .eq("wbs_node_id", wbsNodeId)
    .eq("user_id", userId)
    .maybeSingle();
}

// @table wbs_subscriptions
export function insertWbsSubscription(row: object) {
  return db().from("wbs_subscriptions").insert([row]);
}

// ── wbs_tasks ─────────────────────────────────────────────────────────────────

// @table wbs_tasks
export function deleteWbsTaskByIdReturning(id: string | number | boolean) {
  return db().from("wbs_tasks").delete().eq("id", id).select("id").maybeSingle();
}

// @table wbs_tasks
export function getWbsTaskById(id: string | number | boolean) {
  return db().from("wbs_tasks").select("dependency_task_id").eq("id", id).maybeSingle();
}

// @table wbs_tasks
export function getWbsTaskByProjectIdAndTaskCode(projectId: string | number | boolean, taskCode: string | number | boolean) {
  return db()
    .from("wbs_tasks")
    .select("id")
    .eq("project_id", projectId)
    .eq("task_code", taskCode)
    .maybeSingle();
}

// @table wbs_tasks
export function insertWbsTask(row: object) {
  return db().from("wbs_tasks").insert([row]);
}

// @table wbs_tasks
export function insertWbsTasksReturning(rows: object | object[]) {
  return db().from("wbs_tasks").insert(rows).select("id").single();
}

// @table wbs_tasks
export function listWbsTasksByProjectId(projectId: string | number | boolean, columns: string) {
  return db().from("wbs_tasks").select(columns as "*").eq("project_id", projectId);
}

// @table wbs_tasks
export function listWbsTasksByProjectIdAndExceptId(projectId: string | number | boolean, exceptId: string | number | boolean) {
  return db()
    .from("wbs_tasks")
    .select("id, task_code, task_name")
    .eq("project_id", projectId)
    .neq("id", exceptId)
    .order("task_code")
    .limit(200);
}

// @table wbs_tasks
export function listWbsTasksByProjectIdOrderedBySortOrder(projectId: string | number | boolean) {
  return db()
    .from("wbs_tasks")
    .select("*")
    .eq("project_id", projectId)
    .order("sort_order", { ascending: true, nullsFirst: false });
}

// @table wbs_tasks
export function listWbsTasksByProjectIdOrderedByTaskCode(projectId: string | number | boolean) {
  return db()
    .from("wbs_tasks")
    .select("id, task_code, task_name, owner_name, progress, status")
    .eq("project_id", projectId)
    .not("status", "in", "(closed,completed,cancelled)")
    .order("task_code")
    .limit(500);
}

// @table wbs_tasks
export function updateWbsTaskById(patch: object, id: string | number | boolean) {
  return db().from("wbs_tasks").update(patch).eq("id", id);
}

// ── wbs_template_nodes ────────────────────────────────────────────────────────

// @table wbs_template_nodes
export function deleteWbsTemplateNodeById(id: string | number | boolean) {
  return db().from("wbs_template_nodes").delete().eq("id", id);
}

// @table wbs_template_nodes
export function insertWbsTemplateNode(row: object) {
  return db().from("wbs_template_nodes").insert([row]);
}

// @table wbs_template_nodes
export function listWbsTemplateNodesByTemplateId(templateId: string | number | boolean) {
  return db().from("wbs_template_nodes").select("*").eq("template_id", templateId).order("sort_order");
}

// @table wbs_template_nodes
export function updateWbsTemplateNodeById(patch: object, id: string | number | boolean) {
  return db().from("wbs_template_nodes").update(patch).eq("id", id);
}

// ── wbs_templates ─────────────────────────────────────────────────────────────

// @table wbs_templates
export function deleteWbsTemplateById(id: string | number | boolean) {
  return db().from("wbs_templates").delete().eq("id", id);
}

// @table wbs_templates
export function insertWbsTemplateReturning(row: object) {
  return db().from("wbs_templates").insert([row]).select("id").single();
}

// @table wbs_templates
export function listWbsTemplates() {
  return db().from("wbs_templates").select("*").order("template_name");
}

// @table wbs_templates
export function listWbsTemplatesWithIsActive() {
  return db().from("wbs_templates").select("*").eq("is_active", true).order("template_name");
}

// @table wbs_templates
export function updateWbsTemplateById(patch: object, id: string | number | boolean) {
  return db().from("wbs_templates").update(patch).eq("id", id);
}

// ── weekly_plan_tasks ─────────────────────────────────────────────────────────

// @table weekly_plan_tasks
export function insertWeeklyPlanTasks(rows: object | object[]) {
  return db().from("weekly_plan_tasks").insert(rows);
}

// @table weekly_plan_tasks
export function listWeeklyPlanTasksByWeeklyPlanId(weeklyPlanId: string | number | boolean) {
  return db()
    .from("weekly_plan_tasks")
    .select(`
        id, weekly_plan_id, wbs_task_id, target_progress, responsible_name, notes, actual_progress, met,
        wbs_tasks (task_code, task_name, progress)
      `)
    .eq("weekly_plan_id", weeklyPlanId);
}

// ── weekly_plans ──────────────────────────────────────────────────────────────

// @table weekly_plans
export function deleteWeeklyPlanById(id: string | number | boolean) {
  return db().from("weekly_plans").delete().eq("id", id);
}

// @table weekly_plans
export function insertWeeklyPlanReturning(row: object) {
  return db().from("weekly_plans").insert([row]).select("id").single();
}

// @table weekly_plans
export function listWeeklyPlansByProjectId(projectId: string | number | boolean) {
  return db()
    .from("weekly_plans")
    .select("*")
    .eq("project_id", projectId)
    .order("week_start_date", { ascending: false });
}

// @table weekly_plans
export function updateWeeklyPlanById(patch: object, id: string | number | boolean) {
  return db().from("weekly_plans").update(patch).eq("id", id);
}
