-- Staff List Seed Data
-- Password for all demo users: dcosdemo#2026
-- Run this AFTER the migration: 20260527000001_add_staff_fields.sql
-- Employee IDs are auto-generated by trigger in EMP-YYYY-00001 format based on join_date.
-- Rows ordered by join_date ASC so the sequence numbers are chronological.

do $$
declare
  rec record;
  uid uuid;
  l_role text;
begin
  -- Phase 1: Insert all users and profiles (without report_to)
  -- Ordered by join_date ASC so EMP-YYYY-NNNNN sequence is chronological
  for rec in (
    select * from (values
      ('Pepsi',         'HR Senior',                 'hr',            'L5', 'pepsi@dcos.com',        'Kimseng',  'female','2014-02-25'::date),
      ('The',           'Structure Design-01',       'structural',    'L6', 'the@dcos.com',          'Dara',     'male',  '2015-10-26'::date),
      ('Tangkea',       'Structure Manager',         'structural',    'L4', 'tangkea@dcos.com',      'Vuthy',    'male',  '2015-11-19'::date),
      ('Bophea',        'Site Engineer - MEP',       'construction',  'L6', 'bophea@dcos.com',       'Ratanak',  'female','2015-12-22'::date),
      ('Vannara',       'Site Engineer - C&S',       'construction',  'L6', 'vannara@dcos.com',      'Ratanak',  'male',  '2016-05-07'::date),
      ('Sreymom',       'Account Senior',            'accounting',    'L5', 'sreymom@dcos.com',      'Sovanarith','female','2017-03-27'::date),
      ('Soklay',        'Architectural',             'architecture',  'L6', 'soklay@dcos.com',       'Chenda',   'female','2017-11-26'::date),
      ('Vuthy',         'Project Manager',           'management',    'L3', 'vuthy@dcos.com',        'Sophat',   'male',  '2018-10-17'::date),
      ('Daros',         'Procurement-01',            'procurement',   'L6', 'daros@dcos.com',        'Anna',     'male',  '2018-10-24'::date),
      ('Sophal',        'Construction Manager',      'construction',  'L4', 'sophal@dcos.com',       'Vuthy',    'female','2019-03-11'::date),
      ('Sovvan',        'Procurement-02',            'procurement',   'L6', 'sovvan@dcos.com',       'Anna',     'male',  '2019-04-28'::date),
      ('Seyha',         'MEP Senior',                'mep',           'L5', 'seyha@dcos.com',        'Hanko',    'male',  '2019-06-09'::date),
      ('Sophat',        'General Manager',           'management',    'L2', 'sophat@dcos.com',       'Liheng',   'male',  '2019-07-17'::date),
      ('Sophea',        'MEP Design',                'mep',           'L6', 'sophea@dcos.com',       'Seyha',    'female','2019-12-15'::date),
      ('Samnang',       'MEP Design',                'mep',           'L6', 'samnang@dcos.com',      'Seyha',    'male',  '2020-03-12'::date),
      ('Rithy',         'Account',                   'accounting',    'L6', 'rithy@dcos.com',        'Sovanarith','male', '2020-03-20'::date),
      ('Sovanarith',    'Account Manager',           'accounting',    'L4', 'sovanarith@dcos.com',   'Sophat',   'male',  '2020-07-27'::date),
      ('Pheara',        'Architectural Senior',      'architecture',  'L5', 'pheara@dcos.com',       'Chenda',   'female','2020-11-13'::date),
      ('nisa',          'Accountant',                'accounting',    'L6', 'nisa@dcos.com',         'Sovanarith','female','2020-12-17'::date),
      ('Sokun',         'Site Engineer - Architect', 'construction',  'L6', 'sokun@dcos.com',        'Ratanak',  'male',  '2022-06-27'::date),
      ('Dany',          'Architectural Design-01',   'architecture',  'L6', 'dany@dcos.com',         'Pheara',   'male',  '2022-07-18'::date),
      ('Nita',          'MEP Design',                'mep',           'L6', 'nita@dcos.com',         'Seyha',    'female','2023-01-03'::date),
      ('Nalin',         'HR-01',                     'hr',            'L6', 'nalin@dcos.com',        'Pepsi',    'female','2023-01-15'::date),
      ('Hanko',         'MEP Manager',               'mep',           'L4', 'hanko@dcos.com',        'Vuthy',    'male',  '2023-06-02'::date),
      ('Ratanak',       'Construction Senior',       'construction',  'L5', 'ratanak@dcos.com',      'Sophal',   'male',  '2024-03-27'::date),
      ('Kosal',         'Structure Design-02',       'structural',    'L6', 'kosal@dcos.com',        'Dara',     'male',  '2024-04-12'::date),
      ('Vanchhouy',     'MEP Design',                'mep',           'L6', 'vanchhouy@dcos.com',    'Seyha',    'female','2024-04-26'::date),
      ('Dara',          'Structure Senior',          'structural',    'L5', 'dara@dcos.com',         'Tangkea',  'male',  '2024-09-24'::date),
      ('Visal',         'Procurement Manager',       'procurement',   'L4', 'visal@dcos.com',        'Vuthy',    'male',  '2024-12-07'::date),
      ('Chenda',        'Architect Manager',         'architecture',  'L4', 'chenda@dcos.com',       'Vuthy',    'female','2024-12-12'::date),
      ('Liheng',        'Managing Director',         'management',    'L1', 'liheng@dcos.com',       null,       'male',  '2025-06-12'::date),
      ('Kimseng',       'HR Manager',                'hr',            'L4', 'kimseng@dcos.com',      'Sophat',   'male',  '2026-01-28'::date),
      ('Thida',         'Architectural Design-02',   'architecture',  'L6', 'thida@dcos.com',        'Pheara',   'female','2026-04-11'::date),
      ('Kimly',         'HR-02',                     'hr',            'L6', 'kimly@dcos.com',        'Pepsi',    'female','2026-04-12'::date),
      ('Anna',          'Procurement Senior',        'procurement',   'L5', 'anna@dcos.com',         'Visal',    'female','2026-05-17'::date)
    ) as t(full_name, job_title, department, level, email, report_to_name, gender, join_date)
  ) loop
    if not exists (select 1 from auth.users where email = rec.email) then
      uid := gen_random_uuid();

      l_role := case
        when rec.level in ('L1', 'L2') then 'admin'
        when rec.level = 'L3' then 'project_manager'
        when rec.level = 'L4' then 'department_manager'
        else 'viewer'
      end;

      insert into auth.users (
        instance_id, id, aud, role, email, encrypted_password,
        email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
        created_at, updated_at, confirmation_token,
        email_change, email_change_token_new, recovery_token
      ) values (
        '00000000-0000-0000-0000-000000000000',
        uid,
        'authenticated',
        'authenticated',
        rec.email,
        crypt('dcosdemo#2026', gen_salt('bf', 10)),
        now(),
        '{"provider":"email","providers":["email"]}',
        jsonb_build_object('full_name', rec.full_name),
        now(),
        now(),
        '',
        '',
        '',
        ''
      );

      -- The trigger on_auth_user_created auto-creates a profile row.
      -- Update it with the additional fields.
      -- employee_id is left NULL so the trg_assign_employee_id trigger
      -- generates EMP-YYYY-00001 from join_date.
      update public.profiles
        set full_name   = rec.full_name,
            email       = rec.email,
            join_date   = rec.join_date,
            job_title   = rec.job_title,
            department  = rec.department,
            level       = rec.level,
            role        = l_role,
            gender      = rec.gender
        where id = uid;
    end if;

    -- Assign user_roles (level-based role + functional role for specific depts)
    insert into public.user_roles (user_id, role_code) values
      (uid, rec.level)
    on conflict do nothing;

    if rec.department in ('hr') then
      insert into public.user_roles (user_id, role_code) values (uid, 'HR') on conflict do nothing;
    end if;
    if rec.department in ('accounting') then
      insert into public.user_roles (user_id, role_code) values (uid, 'AC') on conflict do nothing;
    end if;
    if rec.department in ('procurement') then
      insert into public.user_roles (user_id, role_code) values (uid, 'PO') on conflict do nothing;
    end if;
    if rec.job_title ilike '%accountant%' and rec.department != 'accounting' then
      insert into public.user_roles (user_id, role_code) values (uid, 'AC') on conflict do nothing;
    end if;
  end loop;

  -- Phase 2: Resolve report_to references (map manager name -> profile UUID)
  for rec in (
    select * from (values
      ('sophat@dcos.com',       'liheng@dcos.com'),
      ('vuthy@dcos.com',        'sophat@dcos.com'),
      ('chenda@dcos.com',       'vuthy@dcos.com'),
      ('pheara@dcos.com',       'chenda@dcos.com'),
      ('dany@dcos.com',         'pheara@dcos.com'),
      ('thida@dcos.com',        'pheara@dcos.com'),
      ('tangkea@dcos.com',      'vuthy@dcos.com'),
      ('dara@dcos.com',         'tangkea@dcos.com'),
      ('the@dcos.com',          'dara@dcos.com'),
      ('kosal@dcos.com',        'dara@dcos.com'),
      ('visal@dcos.com',        'vuthy@dcos.com'),
      ('anna@dcos.com',         'visal@dcos.com'),
      ('daros@dcos.com',        'anna@dcos.com'),
      ('sovvan@dcos.com',       'anna@dcos.com'),
      ('sophal@dcos.com',       'vuthy@dcos.com'),
      ('ratanak@dcos.com',      'sophal@dcos.com'),
      ('sokun@dcos.com',        'ratanak@dcos.com'),
      ('vannara@dcos.com',      'ratanak@dcos.com'),
      ('bophea@dcos.com',       'ratanak@dcos.com'),
      ('kimseng@dcos.com',      'sophat@dcos.com'),
      ('pepsi@dcos.com',        'kimseng@dcos.com'),
      ('nalin@dcos.com',        'pepsi@dcos.com'),
      ('kimly@dcos.com',        'pepsi@dcos.com'),
      ('sovanarith@dcos.com',   'sophat@dcos.com'),
      ('sreymom@dcos.com',      'sovanarith@dcos.com'),
      ('rithy@dcos.com',        'sovanarith@dcos.com'),
      ('hanko@dcos.com',        'vuthy@dcos.com'),
      ('seyha@dcos.com',        'hanko@dcos.com'),
      ('samnang@dcos.com',      'seyha@dcos.com'),
      ('sophea@dcos.com',       'seyha@dcos.com'),
      ('nita@dcos.com',         'seyha@dcos.com'),
      ('vanchhouy@dcos.com',    'seyha@dcos.com'),
      ('nisa@dcos.com',         'sovanarith@dcos.com'),
      ('soklay@dcos.com',       'chenda@dcos.com')
    ) as t(employee_email, manager_email)
  ) loop
    update public.profiles p
      set report_to = m.id::text
    from public.profiles m
    where p.email = rec.employee_email
      and m.email = rec.manager_email;
  end loop;
end;
$$;
