// Data access for the naming-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── budget_package_sections ───────────────────────────────────────────────────

// @table budget_package_sections
export function deleteBudgetPackageSectionById(id: string | number | boolean) {
  return db().from("budget_package_sections").delete().eq("id", id);
}

// @table budget_package_sections
export function insertBudgetPackageSectionReturning(row: object) {
  return db().from("budget_package_sections").insert([row]).select().single();
}

// @table budget_package_sections
export function listBudgetPackageSections() {
  return db().from("budget_package_sections").select("*").order("sort_order");
}

// @table budget_package_sections
export function listBudgetPackageSectionsWithIsActive() {
  return db().from("budget_package_sections").select("*").eq("is_active", true).order("sort_order");
}

// @table budget_package_sections
export function updateBudgetPackageSectionById(patch: object, id: string | number | boolean) {
  return db().from("budget_package_sections").update(patch).eq("id", id);
}

// ── building_codes ────────────────────────────────────────────────────────────

// @table building_codes
export function listBuildingCodesWithIsActive(columns: string) {
  return db().from("building_codes").select(columns as "*").eq("is_active", true).order("sort_order");
}

// ── companies ─────────────────────────────────────────────────────────────────

// @table companies
export function getCompanyById(id: string | number | boolean, columns: string) {
  return db().from("companies").select(columns as "*").eq("id", id).single();
}

// @table companies
export function listCompanies() {
  return db().from("companies").select("id, name, code").order("name");
}

// @table companies
export function listCompaniesByIds(ids: readonly (string | number)[]) {
  return db().from("companies").select("id, code").in("id", ids);
}

// @table companies
export function listCompaniesOrderedByCode() {
  return db().from("companies").select("id, code, name").order("code");
}

// @table companies
export function updateCompanyById(patch: object, id: string | number | boolean) {
  return db().from("companies").update(patch).eq("id", id);
}

// ── discipline_codes ──────────────────────────────────────────────────────────

// @table discipline_codes
export function deleteDisciplineCodeById(id: string | number | boolean) {
  return db().from("discipline_codes").delete().eq("id", id);
}

// @table discipline_codes
export function insertDisciplineCodeReturning(row: object) {
  return db().from("discipline_codes").insert([row]).select().single();
}

// @table discipline_codes
export function listDisciplineCodes() {
  return db().from("discipline_codes").select("*").order("sort_order");
}

// @table discipline_codes
export function listDisciplineCodesWithIsActive() {
  return db().from("discipline_codes").select("code, name").eq("is_active", true).order("sort_order");
}

// @table discipline_codes
export function updateDisciplineCodeById(patch: object, id: string | number | boolean) {
  return db().from("discipline_codes").update(patch).eq("id", id);
}

// ── document_revisions ────────────────────────────────────────────────────────

// @table document_revisions
export function listDocumentRevisionsByDocumentIdsWithIsLatest(documentIds: readonly (string | number)[]) {
  return db()
    .from("document_revisions")
    .select("document_id, sheet_size, revision_code")
    .in("document_id", documentIds)
    .eq("is_latest", true);
}

// ── document_running_numbers ──────────────────────────────────────────────────

// @table document_running_numbers
export function getDocumentRunningNumberByProjectIdAndDisciplineCodeAndDocumentTypeCode(projectId: string | number | boolean, disciplineCode: string | number | boolean, documentTypeCode: string | number | boolean) {
  return db()
    .from("document_running_numbers")
    .select("last_sequence")
    .eq("project_id", projectId)
    .eq("discipline_code", disciplineCode)
    .eq("document_type_code", documentTypeCode)
    .maybeSingle();
}

// @table document_running_numbers
export function upsertDocumentRunningNumber(row: object) {
  return db()
    .from("document_running_numbers")
    .upsert([row], { onConflict: "project_id,discipline_code,document_type_code" });
}

// ── document_types ────────────────────────────────────────────────────────────

// @table document_types
export function getDocumentTypeByCode(code: string | number | boolean) {
  return db().from("document_types").select("id").eq("code", code).single();
}

// @table document_types
export function insertDocumentTypes(rows: object | object[]) {
  return db().from("document_types").insert(rows);
}

// @table document_types
export function listDocumentTypes() {
  return db().from("document_types").select("*").order("code");
}

// @table document_types
export function listDocumentTypesWithIsActive() {
  return db().from("document_types").select("code, name").eq("is_active", true).order("code");
}

// ── documents ─────────────────────────────────────────────────────────────────

// @table documents
export function insertDocuments(rows: object | object[]) {
  return db().from("documents").insert(rows);
}

// @table documents
export function listDocumentsByProjectId(projectId: string | number | boolean) {
  return db()
    .from("documents")
    .select("id, document_number, title")
    .eq("project_id", projectId)
    .order("document_number");
}

// ── level_naming_templates ────────────────────────────────────────────────────

// @table level_naming_templates
export function deleteLevelNamingTemplateById(id: string | number | boolean) {
  return db().from("level_naming_templates").delete().eq("id", id);
}

// @table level_naming_templates
export function insertLevelNamingTemplateReturning(row: object) {
  return db().from("level_naming_templates").insert([row]).select().single();
}

// @table level_naming_templates
export function listLevelNamingTemplates() {
  return db().from("level_naming_templates").select("*").order("template_name");
}

// @table level_naming_templates
export function listLevelNamingTemplatesWithIsActive() {
  return db().from("level_naming_templates").select("*").eq("is_active", true).order("template_name");
}

// @table level_naming_templates
export function updateLevelNamingTemplateById(patch: object, id: string | number | boolean) {
  return db().from("level_naming_templates").update(patch).eq("id", id);
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function getProfileById(id: string | number | boolean) {
  return db().from("profiles").select("company_id").eq("id", id).single();
}

// @table profiles
export function listProfiles() {
  return db().from("profiles").select("id, full_name, employee_id").order("full_name");
}

// ── project_budget_settings ───────────────────────────────────────────────────

// @table project_budget_settings
export function getProjectBudgetSettingByProjectId(projectId: string | number | boolean) {
  return db().from("project_budget_settings").select("*").eq("project_id", projectId).maybeSingle();
}

// @table project_budget_settings
export function upsertProjectBudgetSettings(rows: object | object[]) {
  return db().from("project_budget_settings").upsert(rows, { onConflict: "project_id" });
}

// ── project_code_sequences ────────────────────────────────────────────────────

// @table project_code_sequences
export function getProjectCodeSequenceWithPrefixP() {
  return db().from("project_code_sequences").select("last_sequence").eq("prefix", "P").single();
}

// ── project_numbering_rules ───────────────────────────────────────────────────

// @table project_numbering_rules
export function getProjectNumberingRuleByProjectId(projectId: string | number | boolean) {
  return db().from("project_numbering_rules").select("*").eq("project_id", projectId).maybeSingle();
}

// @table project_numbering_rules
export function upsertProjectNumberingRules(rows: object | object[]) {
  return db().from("project_numbering_rules").upsert(rows, { onConflict: "project_id" });
}

// ── projects ──────────────────────────────────────────────────────────────────

// @table projects
export function getProjectById(id: string | number | boolean, columns: string) {
  return db().from("projects").select(columns as "*").eq("id", id).single();
}

// @table projects
export function insertProjectsReturning(rows: object | object[]) {
  return db().from("projects").insert(rows).select().single();
}

// @table projects
export function updateProjectByIdReturning(patch: object, id: string | number | boolean) {
  return db().from("projects").update(patch).eq("id", id).select().single();
}

// ── stakeholder_abbreviations ─────────────────────────────────────────────────

// @table stakeholder_abbreviations
export function insertStakeholderAbbreviation(row: object) {
  return db().from("stakeholder_abbreviations").insert([row]);
}

// @table stakeholder_abbreviations
export function listStakeholderAbbreviations() {
  return db().from("stakeholder_abbreviations").select("*");
}

// @table stakeholder_abbreviations
export function listStakeholderAbbreviationsByStakeholderIds(stakeholderIds: readonly (string | number)[]) {
  return db()
    .from("stakeholder_abbreviations")
    .select("stakeholder_id, abbreviation")
    .in("stakeholder_id", stakeholderIds);
}

// @table stakeholder_abbreviations
export function listStakeholderAbbreviationsOrderedByAbbreviation() {
  return db()
    .from("stakeholder_abbreviations")
    .select("stakeholder_id, abbreviation, stakeholders!inner(organization_name)")
    .order("abbreviation");
}

// @table stakeholder_abbreviations
export function updateStakeholderAbbreviationById(patch: object, id: string | number | boolean) {
  return db().from("stakeholder_abbreviations").update(patch).eq("id", id);
}

// ── stakeholders ──────────────────────────────────────────────────────────────

// @table stakeholders
export function getStakeholderById(id: string | number | boolean) {
  return db().from("stakeholders").select("organization_name").eq("id", id).single();
}

// @table stakeholders
export function listStakeholders() {
  return db()
    .from("stakeholders")
    .select("id, organization_name, stakeholder_type")
    .order("organization_name");
}

// ── transmittal_documents ─────────────────────────────────────────────────────

// @table transmittal_documents
export function insertTransmittalDocuments(rows: object | object[]) {
  return db().from("transmittal_documents").insert(rows);
}

// @table transmittal_documents
export function listTransmittalDocumentsByTransmittalId(transmittalId: string | number | boolean) {
  return db()
    .from("transmittal_documents")
    .select("id, document_id, copies_count, media_format, notes, documents!inner(id, document_number, title, current_revision_code)")
    .eq("transmittal_id", transmittalId);
}

// ── transmittal_running_numbers ───────────────────────────────────────────────

// @table transmittal_running_numbers
export function getTransmittalRunningNumberByProjectId(projectId: string | number | boolean) {
  return db()
    .from("transmittal_running_numbers")
    .select("last_sequence")
    .eq("project_id", projectId)
    .maybeSingle();
}

// @table transmittal_running_numbers
export function upsertTransmittalRunningNumber(row: object) {
  return db().from("transmittal_running_numbers").upsert([row], { onConflict: "project_id" });
}

// ── transmittals ──────────────────────────────────────────────────────────────

// @table transmittals
export function getTransmittalById(id: string | number | boolean) {
  return db().from("transmittals").select("*").eq("id", id).single();
}

// @table transmittals
export function insertTransmittalsReturning(rows: object | object[]) {
  return db().from("transmittals").insert(rows).select().single();
}

// @table transmittals
export function listTransmittalsByProjectId(projectId: string | number | boolean) {
  return db()
    .from("transmittals")
    .select("*")
    .eq("project_id", projectId)
    .order("created_at", { ascending: false });
}

// @table transmittals
export function updateTransmittalById(patch: object, id: string | number | boolean) {
  return db().from("transmittals").update(patch).eq("id", id);
}

// ── wbs_nodes ─────────────────────────────────────────────────────────────────

// @table wbs_nodes
export function countWbsNodesByProjectId(projectId: string | number | boolean) {
  return db().from("wbs_nodes").select("*", { count: "exact", head: true }).eq("project_id", projectId);
}

// @table wbs_nodes
export function insertWbsNodeReturning(row: object) {
  return db().from("wbs_nodes").insert([row]).select().single();
}

// @table wbs_nodes
export function insertWbsNodes(rows: object | object[]) {
  return db().from("wbs_nodes").insert(rows);
}

// @table wbs_nodes
export function insertWbsNodesReturning(rows: object | object[]) {
  return db().from("wbs_nodes").insert(rows).select().single();
}

// ── zone_type_codes ───────────────────────────────────────────────────────────

// @table zone_type_codes
export function listZoneTypeCodes() {
  return db().from("zone_type_codes").select("code, name, category, description").order("sort_order");
}
