"use client";

import { GenericSchedule } from "./arc-schedules";

export function MepEquipment() { return <GenericSchedule config={{ title: "Equipment Schedule", table: "design_mep_equipment", orderField: "equipment_no", fields: [{ key: "equipment_no", label: "Equip No" }, { key: "equipment_name", label: "Name" }, { key: "sub_discipline", label: "Sub-Discipline" }, { key: "manufacturer", label: "Manufacturer" }, { key: "capacity", label: "Capacity" }, { key: "quantity", label: "Qty", type: "number" }, { key: "status", label: "Status" }] }} />; }
export function MepLoadSchedule() { return <GenericSchedule config={{ title: "Load Schedule", table: "design_mep_load_schedule", orderField: "load_name", fields: [{ key: "load_type", label: "Type" }, { key: "load_name", label: "Name" }, { key: "load_value", label: "Value", type: "number" }, { key: "unit", label: "Unit" }, { key: "demand_factor", label: "Demand %", type: "number" }] }} />; }
export function MepSleeveCoordination() { return <GenericSchedule config={{ title: "Sleeve/Opening Coordination", table: "design_mep_sleeve_coordination", orderField: "sleeve_no", fields: [{ key: "sleeve_no", label: "Sleeve No" }, { key: "service_type", label: "Service" }, { key: "size_mm", label: "Size" }, { key: "location_text", label: "Location" }, { key: "floor_ref", label: "Floor" }, { key: "status", label: "Status" }] }} />; }
export function MepMaterialSubmittal() { return <GenericSchedule config={{ title: "Material Submittal", table: "design_mep_material_submittal", orderField: "submittal_no", fields: [{ key: "submittal_no", label: "Submittal No" }, { key: "material_name", label: "Material" }, { key: "sub_discipline", label: "Sub-Discipline" }, { key: "manufacturer", label: "Manufacturer" }, { key: "status", label: "Status" }] }} />; }
export function MepCommissioning() { return <GenericSchedule config={{ title: "Commissioning Data", table: "design_mep_commissioning", orderField: "system_name", fields: [{ key: "system_name", label: "System" }, { key: "sub_discipline", label: "Sub-Discipline" }, { key: "test_type", label: "Test Type" }, { key: "test_date", label: "Test Date" }, { key: "test_result", label: "Result" }, { key: "status", label: "Status" }] }} />; }
