// Data access for the planning-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── advance_data_date ─────────────────────────────────────────────────────────

// @table advance_data_date
export function advanceDataDateRpc(args: object) {
  return db().rpc("advance_data_date", args);
}

// ── apply_schedule_dates ──────────────────────────────────────────────────────

// @table apply_schedule_dates
export function applyScheduleDates(args: object) {
  return db().rpc("apply_schedule_dates", args);
}

// ── apply_wbs_codes ───────────────────────────────────────────────────────────

// @table apply_wbs_codes
export function applyWbsCodes(args: object) {
  return db().rpc("apply_wbs_codes", args);
}

// ── companies ─────────────────────────────────────────────────────────────────

// @table companies
export function getCompany() {
  return db().from("companies").select("date_format").limit(1).maybeSingle();
}

// ── contract_register ─────────────────────────────────────────────────────────

// @table contract_register
export function listContractRegisterByProjectId(projectId: string | number | boolean) {
  return db()
    .from("contract_register")
    .select("id, contract_no, title")
    .eq("project_id", projectId)
    .order("contract_no");
}

// ── create_eot_notice_from_delay ──────────────────────────────────────────────

// @table create_eot_notice_from_delay
export function createEotNoticeFromDelay(args: object) {
  return db().rpc("create_eot_notice_from_delay", args);
}

// ── decide_progress_review ────────────────────────────────────────────────────

// @table decide_progress_review
export function decideProgressReview(args: object) {
  return db().rpc("decide_progress_review", args);
}

// ── delay_register ────────────────────────────────────────────────────────────

// @table delay_register
export function deleteDelayRegisterById(id: string | number | boolean) {
  return db().from("delay_register").delete().eq("id", id);
}

// @table delay_register
export function insertDelayRegister(row: object) {
  return db().from("delay_register").insert([row]);
}

// @table delay_register
export function insertDelayRegisterReturning(row: object) {
  return db().from("delay_register").insert([row]).select("id").single();
}

// @table delay_register
export function listDelayRegisterByProjectId(projectId: string | number | boolean) {
  return db()
    .from("delay_register")
    .select("id, wbs_task_id, delay_code, delay_type, impact_days, status")
    .eq("project_id", projectId);
}

// @table delay_register
export function listDelayRegisterByProjectIdOfCauseAndImpactDaysAndStatus(projectId: string | number | boolean) {
  return db()
    .from("delay_register")
    .select("cause, impact_days, status")
    .eq("project_id", projectId)
    .limit(2000);
}

// @table delay_register
export function listDelayRegisterByProjectIdOrderedByCreatedAt(projectId: string | number | boolean, columns: string) {
  return db()
    .from("delay_register")
    .select(columns as "*")
    .eq("project_id", projectId)
    .order("created_at", { ascending: false });
}

// @table delay_register
export function updateDelayRegisterByIdReturning(patch: object, id: string | number | boolean) {
  return db().from("delay_register").update(patch).eq("id", id).select("id").single();
}

// ── delay_register_tasks ──────────────────────────────────────────────────────

// @table delay_register_tasks
export function deleteDelayRegisterTasksByDelayId(delayId: string | number | boolean) {
  return db().from("delay_register_tasks").delete().eq("delay_id", delayId);
}

// @table delay_register_tasks
export function insertDelayRegisterTasks(rows: object | object[]) {
  return db().from("delay_register_tasks").insert(rows);
}

// @table delay_register_tasks
export function listDelayRegisterTasksByDelayIds(delayIds: readonly (string | number)[]) {
  return db().from("delay_register_tasks").select("delay_id, wbs_task_id").in("delay_id", delayIds);
}

// ── get_critical_path_tasks ───────────────────────────────────────────────────

// @table get_critical_path_tasks
export function getCriticalPathTasks(args: object) {
  return db().rpc("get_critical_path_tasks", args);
}

// ── get_portfolio_schedule ────────────────────────────────────────────────────

// @table get_portfolio_schedule
export function getPortfolioSchedule() {
  return db().rpc("get_portfolio_schedule");
}

// ── plan_calendar_exceptions ──────────────────────────────────────────────────

// @table plan_calendar_exceptions
export function deletePlanCalendarExceptionById(id: string | number | boolean) {
  return db().from("plan_calendar_exceptions").delete().eq("id", id);
}

// @table plan_calendar_exceptions
export function insertPlanCalendarException(row: object) {
  return db().from("plan_calendar_exceptions").insert([row]);
}

// @table plan_calendar_exceptions
export function listPlanCalendarExceptionsByCalendarId(calendarId: string | number | boolean) {
  return db()
    .from("plan_calendar_exceptions")
    .select("*")
    .eq("calendar_id", calendarId)
    .order("exception_date", { ascending: false });
}

// @table plan_calendar_exceptions
export function listPlanCalendarExceptionsByCalendarIdLimited(calendarId: string | number | boolean, limit: number) {
  return db()
    .from("plan_calendar_exceptions")
    .select("exception_date, is_working")
    .eq("calendar_id", calendarId)
    .limit(limit);
}

// @table plan_calendar_exceptions
export function listPlanCalendarExceptionsByCalendarIdOfExceptionDateAndIsWorking(calendarId: string | number | boolean) {
  return db()
    .from("plan_calendar_exceptions")
    .select("exception_date, is_working")
    .eq("calendar_id", calendarId);
}

// @table plan_calendar_exceptions
export function listPlanCalendarExceptionsByCalendarIdOrderedByExceptionDate(calendarId: string | number | boolean) {
  return db()
    .from("plan_calendar_exceptions")
    .select("id, exception_date, is_working, reason")
    .eq("calendar_id", calendarId)
    .order("exception_date");
}

// @table plan_calendar_exceptions
export function upsertPlanCalendarExceptionReturning(row: object) {
  return db()
    .from("plan_calendar_exceptions")
    .upsert([row], { onConflict: "calendar_id,exception_date" })
    .select("id, exception_date, is_working, reason")
    .single();
}

// ── plan_calendars ────────────────────────────────────────────────────────────

// @table plan_calendars
export function countPlanCalendarsByProjectId(projectId: string | number | boolean) {
  return db().from("plan_calendars").select("*", { count: "exact", head: true }).eq("project_id", projectId);
}

// @table plan_calendars
export function deletePlanCalendarById(id: string | number | boolean) {
  return db().from("plan_calendars").delete().eq("id", id);
}

// @table plan_calendars
export function getPlanCalendarByProjectId(projectId: string | number | boolean) {
  return db()
    .from("plan_calendars")
    .select("id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday")
    .eq("project_id", projectId)
    .order("is_default", { ascending: false })
    .limit(1)
    .maybeSingle();
}

// @table plan_calendars
export function insertPlanCalendar(row: object) {
  return db().from("plan_calendars").insert([row]);
}

// @table plan_calendars
export function insertPlanCalendarReturning(row: object) {
  return db()
    .from("plan_calendars")
    .insert([row])
    .select("id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday, is_default")
    .single();
}

// @table plan_calendars
export function listPlanCalendarsByProjectId(projectId: string | number | boolean, columns: string) {
  return db().from("plan_calendars").select(columns as "*").eq("project_id", projectId).order("name");
}

// @table plan_calendars
export function listPlanCalendarsByProjectIdOrderedByIsDefaultAndName(projectId: string | number | boolean) {
  return db()
    .from("plan_calendars")
    .select("id, name, monday, tuesday, wednesday, thursday, friday, saturday, sunday, is_default")
    .eq("project_id", projectId)
    .order("is_default", { ascending: false })
    .order("name");
}

// @table plan_calendars
export function updatePlanCalendarById(patch: object, id: string | number | boolean) {
  return db().from("plan_calendars").update(patch).eq("id", id);
}

// ── plan_schedule_settings ────────────────────────────────────────────────────

// @table plan_schedule_settings
export function getPlanScheduleSettingByProjectId(projectId: string | number | boolean, columns: string) {
  return db().from("plan_schedule_settings").select(columns as "*").eq("project_id", projectId).maybeSingle();
}

// @table plan_schedule_settings
export function upsertPlanScheduleSetting(row: object) {
  return db().from("plan_schedule_settings").upsert([row], { onConflict: "project_id" });
}

// ── plan_timescale ────────────────────────────────────────────────────────────

// @table plan_timescale
export function getPlanTimescaleByProjectId(projectId: string | number | boolean) {
  return db().from("plan_timescale").select("config").eq("project_id", projectId).maybeSingle();
}

// @table plan_timescale
export function upsertPlanTimescale(row: object) {
  return db().from("plan_timescale").upsert([row], { onConflict: "project_id" });
}

// ── plan_wbs_code_mask ────────────────────────────────────────────────────────

// @table plan_wbs_code_mask
export function getPlanWbsCodeMaskByProjectId(projectId: string | number | boolean) {
  return db()
    .from("plan_wbs_code_mask")
    .select("code_prefix, levels, generate_for_new, verify_unique")
    .eq("project_id", projectId)
    .maybeSingle();
}

// @table plan_wbs_code_mask
export function upsertPlanWbsCodeMask(row: object) {
  return db().from("plan_wbs_code_mask").upsert([row], { onConflict: "project_id" });
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function getProfileById(id: string | number | boolean, columns: string) {
  return db().from("profiles").select(columns as "*").eq("id", id).maybeSingle();
}

// @table profiles
export function getProfileByIdOfCompanyId(id: string | number | boolean) {
  return db().from("profiles").select("company_id").eq("id", id).single();
}

// @table profiles
export function listProfiles(columns: string) {
  return db().from("profiles").select(columns as "*").order("full_name");
}

// @table profiles
export function listProfilesOrderedByFullName() {
  return db().from("profiles").select("id, full_name, email").order("full_name", { ascending: true });
}

// ── project_members ───────────────────────────────────────────────────────────

// @table project_members
export function deleteProjectMembersByProjectIdAndUserId(projectId: string | number | boolean, userId: string | number | boolean) {
  return db().from("project_members").delete().eq("project_id", projectId).eq("user_id", userId);
}

// @table project_members
export function insertProjectMember(row: object) {
  return db().from("project_members").insert([row]);
}

// @table project_members
export function listProjectMembersByProjectId(projectId: string | number | boolean) {
  return db()
    .from("project_members")
    .select("user_id, role_code, added_by, created_at, profiles(full_name, email)")
    .eq("project_id", projectId)
    .order("created_at", { ascending: true });
}

// ── projects ──────────────────────────────────────────────────────────────────

// @table projects
export function getProjectById(id: string | number | boolean, columns: string) {
  return db().from("projects").select(columns as "*").eq("id", id).maybeSingle();
}

// ── roles ─────────────────────────────────────────────────────────────────────

// @table roles
export function listRoles() {
  return db().from("roles").select("code, name, type, level").order("level", { ascending: true });
}

// ── stakeholder_abbreviations ─────────────────────────────────────────────────

// @table stakeholder_abbreviations
export function listStakeholderAbbreviations() {
  return db()
    .from("stakeholder_abbreviations")
    .select("stakeholder_id, abbreviation, stakeholders!inner(organization_name)");
}

// ── submit_progress ───────────────────────────────────────────────────────────

// @table submit_progress
export function submitProgress(args: object) {
  return db().rpc("submit_progress", args);
}

// ── user_ui_preferences ───────────────────────────────────────────────────────

// @table user_ui_preferences
export function getUserUiPreferenceByUserIdAndPreferenceKey(userId: string | number | boolean, preferenceKey: string | number | boolean) {
  return db()
    .from("user_ui_preferences")
    .select("value")
    .eq("user_id", userId)
    .eq("preference_key", preferenceKey)
    .maybeSingle();
}

// @table user_ui_preferences
export function upsertUserUiPreference(row: object) {
  return db().from("user_ui_preferences").upsert([row], { onConflict: "user_id,preference_key" });
}

// ── v_plan_client_programme ───────────────────────────────────────────────────

// @table v_plan_client_programme
export function getVPlanClientProgrammeByProjectId(projectId: string | number | boolean) {
  return db().from("v_plan_client_programme").select("*").eq("project_id", projectId).maybeSingle();
}

// ── wbs_nodes ─────────────────────────────────────────────────────────────────

// @table wbs_nodes
export function deleteWbsNodeByIdReturning(id: string | number | boolean) {
  return db().from("wbs_nodes").delete().eq("id", id).select("id").maybeSingle();
}

// @table wbs_nodes
export function getWbsNodeByProjectIdWithParentIdAndNodeTypeTaskGroupAndWbsCodeTASKS(columns: string, projectId: string | number | boolean) {
  return db()
    .from("wbs_nodes")
    .select(columns)
    .eq("project_id", projectId)
    .is("parent_id", null)
    .eq("node_type", "task_group")
    .eq("wbs_code", "TASKS")
    .maybeSingle();
}

// @table wbs_nodes
export function getWbsNodeByProjectIdWithParentIdAndWbsCodeTASKS(projectId: string | number | boolean) {
  return db()
    .from("wbs_nodes")
    .select("id")
    .eq("project_id", projectId)
    .is("parent_id", null)
    .eq("wbs_code", "TASKS")
    .maybeSingle();
}

// @table wbs_nodes
export function insertWbsNodeReturning(row: object, columns: string) {
  return db().from("wbs_nodes").insert([row]).select(columns).single();
}

// @table wbs_nodes
export function listWbsNodesByProjectId(projectId: string | number | boolean) {
  return db()
    .from("wbs_nodes")
    .select("id, parent_id, wbs_code, wbs_name")
    .eq("project_id", projectId)
    .order("wbs_code", { ascending: true });
}

// @table wbs_nodes
export function listWbsNodesByProjectIdOrderedByFullPath(projectId: string | number | boolean) {
  return db()
    .from("wbs_nodes")
    .select("id, wbs_code, wbs_name, full_path, node_type")
    .eq("project_id", projectId)
    .order("full_path");
}

// @table wbs_nodes
export function listWbsNodesByProjectIdOrderedBySortOrder(columns: string, projectId: string | number | boolean, limit: number) {
  return db()
    .from("wbs_nodes")
    .select(columns)
    .eq("project_id", projectId)
    .order("sort_order", { ascending: true, nullsFirst: false })
    .limit(limit);
}

// @table wbs_nodes
export function updateWbsNodeById(patch: object, id: string | number | boolean) {
  return db().from("wbs_nodes").update(patch).eq("id", id);
}

// ── wbs_task_progress_reviews ─────────────────────────────────────────────────

// @table wbs_task_progress_reviews
export function listWbsTaskProgressReviewsByProjectIdWithStatusPending(projectId: string | number | boolean) {
  return db()
    .from("wbs_task_progress_reviews")
    .select(`
        id, wbs_task_id, proposed_progress, previous_progress, proposed_by, proposed_at, comment, daily_report_id,
        wbs_tasks (task_code, task_name),
        site_daily_reports (report_date, weather_conditions),
        profiles!wbs_task_progress_reviews_proposed_by_fkey (full_name)
      `)
    .eq("project_id", projectId)
    .eq("status", "pending")
    .order("proposed_at", { ascending: true });
}

// @table wbs_task_progress_reviews
export function listWbsTaskProgressReviewsByProjectIdWithStatusPendingOfWbsTaskId(projectId: string | number | boolean) {
  return db()
    .from("wbs_task_progress_reviews")
    .select("wbs_task_id")
    .eq("project_id", projectId)
    .eq("status", "pending");
}

// ── wbs_tasks ─────────────────────────────────────────────────────────────────

// @table wbs_tasks
export function countWbsTasksByProjectId(projectId: string | number | boolean) {
  return db().from("wbs_tasks").select("*", { count: "exact", head: true }).eq("project_id", projectId);
}

// @table wbs_tasks
export function deleteWbsTaskByIdReturning(id: string | number | boolean) {
  return db().from("wbs_tasks").delete().eq("id", id).select("id").maybeSingle();
}

// @table wbs_tasks
export function insertWbsTasksReturning(rows: object | object[], columns: string) {
  return db().from("wbs_tasks").insert(rows).select(columns).single();
}

// @table wbs_tasks
export function listWbsTaskColumnsByProjectId(columns: string, projectId: string | number | boolean) {
  return db().from("wbs_tasks").select(columns).eq("project_id", projectId).limit(1000);
}

// @table wbs_tasks
export function listWbsTaskMilestoneFlagsByProjectId(projectId: string | number | boolean) {
  return db()
    .from("wbs_tasks")
    .select("id, task_code, task_name, is_milestone")
    .eq("project_id", projectId)
    .limit(2000);
}

// @table wbs_tasks
export function listWbsTasksByProjectId(projectId: string | number | boolean) {
  return db()
    .from("wbs_tasks")
    .select(`
          id, task_code, task_name, discipline, wbs_node_id, owner_name,
          start_date, end_date, progress, status, delay_status, priority,
          dependency_task_ids, dependency_types, dependency_lag_days,
          is_milestone, constraint_type,
          baseline_start_date, baseline_finish_date,
          activity_type, actual_start_date, actual_finish_date, field_observation_notes
        `)
    .eq("project_id", projectId)
    .order("sort_order", { ascending: true })
    .order("start_date", { ascending: true })
    .limit(500);
}

// @table wbs_tasks
export function listWbsTasksByProjectIdOfTaskCode(projectId: string | number | boolean) {
  return db().from("wbs_tasks").select("task_code").eq("project_id", projectId);
}

// @table wbs_tasks
export function listWbsTasksByProjectIdOrderedBySortOrder(columns: string, projectId: string | number | boolean, limit: number) {
  return db()
    .from("wbs_tasks")
    .select(columns)
    .eq("project_id", projectId)
    .order("sort_order", { ascending: true, nullsFirst: false })
    .limit(limit);
}

// @table wbs_tasks
export function listWbsTasksByProjectIdOrderedByTaskCode(projectId: string | number | boolean) {
  return db()
    .from("wbs_tasks")
    .select("id, task_code, task_name")
    .eq("project_id", projectId)
    .order("task_code")
    .limit(500);
}

// @table wbs_tasks
export function listWbsTasksByProjectIdWithPlanTaskWork(projectId: string | number | boolean, columns: string) {
  return db().from("wbs_tasks").select(columns as "*").eq("project_id", projectId).limit(1000);
}

// @table wbs_tasks
export function listWbsTasksForDelayReviewByProjectId(projectId: string | number | boolean) {
  return db()
    .from("wbs_tasks")
    .select("id, task_code, task_name, status, discipline, delay_status, delay_reason, priority, start_date, end_date, progress, is_milestone, owner_name, baseline_finish_date")
    .eq("project_id", projectId)
    .limit(500);
}

// @table wbs_tasks
export function updateWbsTaskById(patch: object, id: string | number | boolean) {
  return db().from("wbs_tasks").update(patch).eq("id", id);
}

// ── weekly_plans ──────────────────────────────────────────────────────────────

// @table weekly_plans
export function getWeeklyPlanByProjectIdWithStatusApproved(projectId: string | number | boolean) {
  return db()
    .from("weekly_plans")
    .select("pcr")
    .eq("project_id", projectId)
    .eq("status", "approved")
    .not("pcr", "is", null)
    .order("closed_at", { ascending: false })
    .limit(1)
    .maybeSingle();
}
