// Data access for the documents-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── document_audit_log ────────────────────────────────────────────────────────

// @table document_audit_log
export function insertDocumentAuditLog(row: object) {
  return db().from("document_audit_log").insert([row]);
}

// @table document_audit_log
export function listDocumentAuditLog() {
  return db()
    .from("document_audit_log")
    .select("id, document_id, action, created_at, documents:document_id(document_number, title)")
    .order("created_at", { ascending: false })
    .limit(20);
}

// @table document_audit_log
export function listDocumentAuditLogByDocumentId(documentId: string | number | boolean) {
  return db()
    .from("document_audit_log")
    .select("*, profiles:user_id(full_name)")
    .eq("document_id", documentId)
    .order("created_at", { ascending: false });
}

// @table document_audit_log
export function listDocumentAuditLogOrderedByCreatedAt() {
  return db()
    .from("document_audit_log")
    .select("*, profiles:user_id(full_name), documents:document_id(document_number, title)")
    .order("created_at", { ascending: false })
    .limit(200);
}

// ── document_print_logs ───────────────────────────────────────────────────────

// @table document_print_logs
export function insertDocumentPrintLog(row: object) {
  return db().from("document_print_logs").insert([row]);
}

// @table document_print_logs
export function listDocumentPrintLogsByDocumentRevisionId(documentRevisionId: string | number | boolean) {
  return db()
    .from("document_print_logs")
    .select("*, profiles:printed_by(full_name)")
    .eq("document_revision_id", documentRevisionId)
    .order("copy_number", { ascending: true });
}

// @table document_print_logs
export function listDocumentPrintLogsWithRecalledAt() {
  return db()
    .from("document_print_logs")
    .select("id, document_revision_id, document_revisions!inner(document_id)")
    .is("recalled_at", null);
}

// @table document_print_logs
export function updateDocumentPrintLogById(patch: object, id: string | number | boolean) {
  return db().from("document_print_logs").update(patch).eq("id", id);
}

// ── document_revision_task_links ──────────────────────────────────────────────

// @table document_revision_task_links
export function listDocumentRevisionTaskLinksByRevisionId(revisionId: string | number | boolean) {
  return db()
    .from("document_revision_task_links")
    .select("*, wbs_tasks:task_id(task_code, task_name)")
    .eq("revision_id", revisionId);
}

// ── document_revisions ────────────────────────────────────────────────────────

// @table document_revisions
export function getDocumentRevisionByDocumentId(documentId: string | number | boolean) {
  return db()
    .from("document_revisions")
    .select("id, revision_code, file_url, file_name, is_latest")
    .eq("document_id", documentId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
}

// @table document_revisions
export function insertDocumentRevision(row: object) {
  return db().from("document_revisions").insert([row]);
}

// @table document_revisions
export function listDocumentRevisionsByDocumentId(documentId: string | number | boolean, columns: string) {
  return db()
    .from("document_revisions")
    .select(columns as "*")
    .eq("document_id", documentId)
    .order("revision_number", { ascending: false });
}

// @table document_revisions
export function listDocumentRevisionsByDocumentIdOrderedByCreatedAt(documentId: string | number | boolean) {
  return db()
    .from("document_revisions")
    .select("id, revision_code, suitability_code, sheet_size, status, file_url, file_name, created_at, is_latest")
    .eq("document_id", documentId)
    .order("created_at", { ascending: false });
}

// @table document_revisions
export function listDocumentRevisionsByDocumentIdsWithIsLatest(documentIds: readonly (string | number)[]) {
  return db()
    .from("document_revisions")
    .select("document_id, suitability_code, sheet_size")
    .in("document_id", documentIds)
    .eq("is_latest", true);
}

// ── document_types ────────────────────────────────────────────────────────────

// @table document_types
export function listDocumentTypes() {
  return db().from("document_types").select("*");
}

// @table document_types
export function listDocumentTypesOfIdAndCode() {
  return db().from("document_types").select("id, code").limit(5);
}

// @table document_types
export function listDocumentTypesWithIsActive() {
  return db()
    .from("document_types")
    .select("id, code, name")
    .eq("is_active", true)
    .order("code", { ascending: true });
}

// ── document_viewers ──────────────────────────────────────────────────────────

// @table document_viewers
export function insertDocumentViewer(row: object) {
  return db().from("document_viewers").insert([row]);
}

// @table document_viewers
export function listDocumentViewersByDocumentId(documentId: string | number | boolean) {
  return db()
    .from("document_viewers")
    .select("*, profiles:user_id(full_name)")
    .eq("document_id", documentId)
    .order("transmitted_at", { ascending: false });
}

// ── documents ─────────────────────────────────────────────────────────────────

// @table documents
export function insertDocumentReturning(row: object) {
  return db().from("documents").insert([row]).select("id").single();
}

// @table documents
export function insertDocumentsReturning(rows: object | object[]) {
  return db().from("documents").insert(rows).select().single();
}

// @table documents
export function listDocuments() {
  return db().from("documents").select("status");
}

// @table documents
export function listDocumentsByProjectId(projectId: string | number | boolean) {
  return db()
    .from("documents")
    .select(`
          id,
          project_id,
          document_number,
          title,
          discipline,
          package_code,
          status,
          current_revision,
          current_revision_code,
          review_code,
          planned_submission_date,
          actual_submission_date,
          consultant_due_date,
          consultant_returned_at,
          created_at
        `)
    .eq("project_id", projectId)
    .order("document_number", { ascending: true });
}

// @table documents
export function listDocumentsByProjectIdOfIdAndDocumentNumberAndTitle(projectId: string | number | boolean) {
  return db().from("documents").select("id, document_number, title").eq("project_id", projectId);
}

// @table documents
export function listDocumentsOrderedByCreatedAt() {
  return db().from("documents").select("*").order("created_at", { ascending: false });
}

// @table documents
export function updateDocumentById(patch: object, id: string | number | boolean) {
  return db().from("documents").update(patch).eq("id", id);
}

// @table documents
export function updateDocumentByIdReturning(patch: object, id: string | number | boolean) {
  return db().from("documents").update(patch).eq("id", id).select().single();
}

// ── get_document_verification_payload ─────────────────────────────────────────

// @table get_document_verification_payload
export function getDocumentVerificationPayload(args: object) {
  return db().rpc("get_document_verification_payload", args);
}

// ── projects ──────────────────────────────────────────────────────────────────

// @table projects
export function getProjectById(id: string | number | boolean) {
  return db().from("projects").select("project_code").eq("id", id).single();
}

// @table projects
export function listProjects() {
  return db()
    .from("projects")
    .select("id, project_code, project_name")
    .order("project_code", { ascending: true });
}

// @table projects
export function listProjectsOfIdAndProjectCodeAndProjectName() {
  return db().from("projects").select("id, project_code, project_name");
}

// ── submittal_comments ────────────────────────────────────────────────────────

// @table submittal_comments
export function insertSubmittalComment(row: object) {
  return db().from("submittal_comments").insert([row]);
}

// @table submittal_comments
export function listSubmittalCommentsBySubmittalId(submittalId: string | number | boolean) {
  return db()
    .from("submittal_comments")
    .select("*, commenter:commented_by(full_name), responder:responded_by(full_name)")
    .eq("submittal_id", submittalId)
    .order("commented_at", { ascending: true });
}

// @table submittal_comments
export function updateSubmittalCommentById(patch: object, id: string | number | boolean) {
  return db().from("submittal_comments").update(patch).eq("id", id);
}

// ── submittal_items ───────────────────────────────────────────────────────────

// @table submittal_items
export function insertSubmittalItem(row: object) {
  return db().from("submittal_items").insert([row]);
}

// @table submittal_items
export function listSubmittalItemsBySubmittalId(submittalId: string | number | boolean) {
  return db()
    .from("submittal_items")
    .select("*, document:document_id(document_number, title, current_revision_code), revision:document_revision_id(file_url, file_name)")
    .eq("submittal_id", submittalId)
    .order("created_at", { ascending: true });
}

// ── submittal_packages ────────────────────────────────────────────────────────

// @table submittal_packages
export function insertSubmittalPackages(rows: object | object[]) {
  return db().from("submittal_packages").insert(rows);
}

// @table submittal_packages
export function insertSubmittalPackagesReturning(rows: object | object[]) {
  return db().from("submittal_packages").insert(rows).select().single();
}

// @table submittal_packages
export function listSubmittalPackages() {
  return db()
    .from("submittal_packages")
    .select("consultant_status, consultant_due_date, consultant_returned_at");
}

// @table submittal_packages
export function listSubmittalPackagesByProjectId(projectId: string | number | boolean) {
  return db().from("submittal_packages").select("submittal_number").eq("project_id", projectId);
}

// @table submittal_packages
export function listSubmittalPackagesByProjectIdOrderedByCreatedAt(projectId: string | number | boolean) {
  return db()
    .from("submittal_packages")
    .select("*, originator:originator_id(full_name), reviewer:consultant_reviewer_id(full_name)")
    .eq("project_id", projectId)
    .order("created_at", { ascending: false });
}

// @table submittal_packages
export function updateSubmittalPackageById(patch: object, id: string | number | boolean) {
  return db().from("submittal_packages").update(patch).eq("id", id);
}

// ── wbs_nodes ─────────────────────────────────────────────────────────────────

// @table wbs_nodes
export function listWbsNodesByProjectId(projectId: string | number | boolean) {
  return db()
    .from("wbs_nodes")
    .select("id, wbs_code, wbs_name, full_path")
    .eq("project_id", projectId)
    .order("full_path", { ascending: true, nullsFirst: false });
}

// @table wbs_nodes
export function listWbsNodesByProjectIdOrderedByFullPath(projectId: string | number | boolean) {
  return db()
    .from("wbs_nodes")
    .select("id, wbs_code, wbs_name, full_path")
    .eq("project_id", projectId)
    .order("full_path", { ascending: true });
}
