// Data access for the inventory-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── inv_adjustment_lines ──────────────────────────────────────────────────────

// @table inv_adjustment_lines
export function listInvAdjustmentLinesByAdjustmentId(adjustmentId: string | number | boolean) {
  return db()
    .from("inv_adjustment_lines")
    .select("*, inv_items(item_code, name, unit_of_measure)")
    .eq("adjustment_id", adjustmentId)
    .order("created_at");
}

// ── inv_adjustments ───────────────────────────────────────────────────────────

// @table inv_adjustments
export function getInvAdjustmentById(id: string | number | boolean) {
  return db()
    .from("inv_adjustments")
    .select("*, profiles!inv_adjustments_requested_by_fkey(full_name, email)")
    .eq("id", id)
    .single();
}

// @table inv_adjustments
export function listInvAdjustments(from: number, to: number) {
  return db()
    .from("inv_adjustments")
    .select("*, inv_adjustment_lines(count)", { count: "exact" })
    .order("created_at", { ascending: false })
    .range(from, to);
}

// ── inv_audit_log ─────────────────────────────────────────────────────────────

// @table inv_audit_log
export function listInvAuditLogByRecordIdWithTableNameInvAdjustments(recordId: string | number | boolean) {
  return db()
    .from("inv_audit_log")
    .select("action, performed_by, created_at, old_status, new_status")
    .eq("record_id", recordId)
    .eq("table_name", "inv_adjustments")
    .order("created_at", { ascending: true });
}

// @table inv_audit_log
export function listInvAuditLogByRecordIdWithTableNameInvMaterialRequisitions(recordId: string | number | boolean) {
  return db()
    .from("inv_audit_log")
    .select("*, profiles!performed_by(full_name, email)")
    .eq("table_name", "inv_material_requisitions")
    .eq("record_id", recordId)
    .order("created_at", { ascending: true });
}

// @table inv_audit_log
export function listInvAuditLogByRecordIdWithTableNameInvTransfers(recordId: string | number | boolean) {
  return db()
    .from("inv_audit_log")
    .select("*, profiles!performed_by(full_name, email)")
    .eq("table_name", "inv_transfers")
    .eq("record_id", recordId)
    .order("created_at", { ascending: true });
}

// ── inv_grns ──────────────────────────────────────────────────────────────────

// @table inv_grns
export function countInvGrnsWithStatusDraft() {
  return db().from("inv_grns").select("id", { count: "exact", head: true }).eq("status", "draft");
}

// @table inv_grns
export function getInvGrnById(id: string | number | boolean) {
  return db()
    .from("inv_grns")
    .select(`
        *,
        inv_grn_lines(
          id, item_id, po_item_id, quantity_ordered, quantity_received,
          unit_cost, total_cost, batch_number, inspection_required,
          inspection_status, condition_notes,
          inv_items(item_code, name, unit_of_measure)
        )
      `)
    .eq("id", id)
    .single();
}

// @table inv_grns
export function listInvGrns(from: number, to: number) {
  return db()
    .from("inv_grns")
    .select("*", { count: "exact" })
    .order("created_at", { ascending: false })
    .range(from, to);
}

// ── inv_items ─────────────────────────────────────────────────────────────────

// @table inv_items
export function listActiveInvItemsForInspection() {
  return db()
    .from("inv_items")
    .select("id, item_code, name, unit_of_measure, is_inspection_required")
    .eq("is_active", true);
}

// @table inv_items
export function listInvItemsByFilterWithIsActive(filter: string) {
  return db()
    .from("inv_items")
    .select("id, item_code, name, category, unit_of_measure, is_active")
    .eq("is_active", true)
    .or(filter)
    .limit(20);
}

// @table inv_items
export function listInvItemsWithIsActive() {
  return db().from("inv_items").select("*").eq("is_active", true).order("name");
}

// @table inv_items
export function listInvItemsWithIsActiveWithInvStock() {
  return db()
    .from("inv_items")
    .select("id, min_stock_level, inv_stock(quantity_available)")
    .eq("is_active", true)
    .not("min_stock_level", "is", null);
}

// ── inv_locations ─────────────────────────────────────────────────────────────

// @table inv_locations
export function listInvLocationsByStoreId(storeId: string | number | boolean) {
  return db().from("inv_locations").select("*").eq("store_id", storeId).order("code");
}

// ── inv_material_requisitions ─────────────────────────────────────────────────

// @table inv_material_requisitions
export function countInvMaterialRequisitionsWithStatusSubmitted() {
  return db()
    .from("inv_material_requisitions")
    .select("id", { count: "exact", head: true })
    .in("status", ["submitted"]);
}

// @table inv_material_requisitions
export function getInvMaterialRequisitionById(id: string | number | boolean) {
  return db()
    .from("inv_material_requisitions")
    .select(`
          *,
          inv_mr_lines(
            id, item_id, quantity_requested, quantity_approved, quantity_issued,
            unit_cost_at_issue, remarks,
            inv_items(item_code, name, unit_of_measure)
          ),
          wbs_nodes!wbs_node_id(wbs_code, wbs_name, full_path),
          inv_stores!store_id(name, store_code),
          profiles!requested_by(full_name, email),
          approver:profiles!approved_by(full_name, email)
        `)
    .eq("id", id)
    .single();
}

// @table inv_material_requisitions
export function listInvMaterialRequisitions(from: number, to: number) {
  return db()
    .from("inv_material_requisitions")
    .select("*, profiles!requested_by(full_name, email)", { count: "exact" })
    .order("created_at", { ascending: false })
    .range(from, to);
}

// @table inv_material_requisitions
export function listInvMaterialRequisitionsByProjectIdAndStoreIdWithStatusIssuedPartiallyIssued(projectId: string | number | boolean, storeId: string | number | boolean) {
  return db()
    .from("inv_material_requisitions")
    .select("id, mr_number, status")
    .eq("project_id", projectId)
    .eq("store_id", storeId)
    .in("status", ["issued", "partially_issued"])
    .order("mr_number");
}

// ── inv_movements ─────────────────────────────────────────────────────────────

// @table inv_movements
export function listInvMovements() {
  return db()
    .from("inv_movements")
    .select("*, inv_items!inner(item_code, name, unit_of_measure)")
    .order("created_at", { ascending: false })
    .limit(20);
}

// @table inv_movements
export function listInvMovementsOrderedByCreatedAt(from: number, to: number) {
  return db()
    .from("inv_movements")
    .select("*, inv_items!inner(item_code, name, unit_of_measure)", { count: "exact" })
    .order("created_at", { ascending: false })
    .range(from, to);
}

// ── inv_returns ───────────────────────────────────────────────────────────────

// @table inv_returns
export function countInvReturnsWithStatusDraftSubmittedInspected() {
  return db()
    .from("inv_returns")
    .select("id", { count: "exact", head: true })
    .in("status", ["draft", "submitted", "inspected"]);
}

// @table inv_returns
export function getInvReturnById(id: string | number | boolean) {
  return db()
    .from("inv_returns")
    .select(`
        *,
        inv_return_lines(id, return_id, item_id, quantity, condition, unit_cost, remarks, inv_items(item_code, name, unit_of_measure)),
        inv_stores(name, store_code),
        profiles!returned_by(full_name, email)
      `)
    .eq("id", id)
    .single();
}

// @table inv_returns
export function listInvReturns() {
  return db()
    .from("inv_returns")
    .select("*, inv_return_lines(count), inv_stores(name, store_code)")
    .order("created_at", { ascending: false });
}

// ── inv_stock ─────────────────────────────────────────────────────────────────

// @table inv_stock
export function listInvStock() {
  return db()
    .from("inv_stock")
    .select("*, inv_items!inner(item_code, name, category, unit_of_measure, min_stock_level, reorder_quantity)")
    .order("last_movement_at", { ascending: false });
}

// @table inv_stock
export function listInvStockByStoreIdAndItemIds(storeId: string | number | boolean, itemIds: readonly (string | number)[]) {
  return db()
    .from("inv_stock")
    .select("item_id, quantity_available")
    .eq("store_id", storeId)
    .in("item_id", itemIds);
}

// @table inv_stock
export function listInvStockWithIsActive() {
  return db()
    .from("inv_stock")
    .select("quantity_available, unit_cost_fifo, inv_items!inner(is_active)")
    .eq("inv_items.is_active", true);
}

// ── inv_stocktake_lines ───────────────────────────────────────────────────────

// @table inv_stocktake_lines
export function listInvStocktakeLinesByStocktakeId(stocktakeId: string | number | boolean) {
  return db()
    .from("inv_stocktake_lines")
    .select("*, inv_items(item_code, name, unit_of_measure)")
    .eq("stocktake_id", stocktakeId)
    .order("created_at");
}

// ── inv_stocktakes ────────────────────────────────────────────────────────────

// @table inv_stocktakes
export function getInvStocktakeById(id: string | number | boolean) {
  return db()
    .from("inv_stocktakes")
    .select("*, profiles!inv_stocktakes_initiated_by_fkey(full_name, email)")
    .eq("id", id)
    .single();
}

// @table inv_stocktakes
export function getInvStocktakeWithStatusOpenCountingPendingApproval() {
  return db()
    .from("inv_stocktakes")
    .select("id")
    .in("status", ["open", "counting", "pending_approval"])
    .maybeSingle();
}

// @table inv_stocktakes
export function listInvStocktakes(from: number, to: number) {
  return db()
    .from("inv_stocktakes")
    .select("*, inv_stocktake_lines(count)", { count: "exact" })
    .order("created_at", { ascending: false })
    .range(from, to);
}

// ── inv_stores ────────────────────────────────────────────────────────────────

// @table inv_stores
export function getInvStoreById(id: string | number | boolean) {
  return db().from("inv_stores").select("*").eq("id", id).single();
}

// @table inv_stores
export function listInvStores() {
  return db().from("inv_stores").select("*").order("name");
}

// @table inv_stores
export function listInvStoresWithStatusActive(columns: string) {
  return db().from("inv_stores").select(columns as "*").eq("status", "active").order("name");
}

// ── inv_tool_issues ───────────────────────────────────────────────────────────

// @table inv_tool_issues
export function listInvToolIssuesByToolId(toolId: string | number | boolean) {
  return db()
    .from("inv_tool_issues")
    .select(`
          *,
          profiles!custodian_id(full_name, email),
          projects!project_id(project_code, project_name),
          wbs_nodes!wbs_node_id(wbs_code, wbs_name)
        `)
    .eq("tool_id", toolId)
    .order("issued_at", { ascending: false });
}

// @table inv_tool_issues
export function listInvToolIssuesWithStatusIssuedOverdue(columns: string) {
  return db().from("inv_tool_issues").select(columns as "*").in("status", ["issued", "overdue"]);
}

// ── inv_tools ─────────────────────────────────────────────────────────────────

// @table inv_tools
export function countInvToolsWithStatusAvailable() {
  return db().from("inv_tools").select("id", { count: "exact", head: true }).eq("status", "available");
}

// @table inv_tools
export function countInvToolsWithStatusIssued() {
  return db().from("inv_tools").select("id", { count: "exact", head: true }).eq("status", "issued");
}

// @table inv_tools
export function getInvToolById(id: string | number | boolean) {
  return db().from("inv_tools").select("*").eq("id", id).single();
}

// @table inv_tools
export function listInvTools() {
  return db().from("inv_tools").select("*").order("tool_code");
}

// ── inv_transfers ─────────────────────────────────────────────────────────────

// @table inv_transfers
export function countInvTransfersWithStatusSubmittedApproved() {
  return db()
    .from("inv_transfers")
    .select("id", { count: "exact", head: true })
    .in("status", ["submitted", "approved"]);
}

// @table inv_transfers
export function getInvTransferById(id: string | number | boolean) {
  return db()
    .from("inv_transfers")
    .select(`
            *,
            inv_transfer_lines(*, inv_items(item_code, name, unit_of_measure)),
            source_store:source_store_id(name, store_code),
            destination_store:destination_store_id(name, store_code),
            source_project:source_project_id(project_name, project_code),
            destination_project:destination_project_id(project_name, project_code),
            profiles!requested_by(full_name, email),
            source_approver:profiles!source_approved_by(full_name, email),
            dest_approver:profiles!dest_approved_by(full_name, email),
            dispatcher:profiles!dispatched_by(full_name, email),
            receiver:profiles!received_by(full_name, email)
          `)
    .eq("id", id)
    .single();
}

// @table inv_transfers
export function listInvTransfers(from: number, to: number) {
  return db()
    .from("inv_transfers")
    .select("*, source_store:source_store_id(name, store_code), destination_store:destination_store_id(name, store_code), source_project:source_project_id(project_name, project_code), destination_project:destination_project_id(project_name, project_code)", { count: "exact" })
    .order("created_at", { ascending: false })
    .range(from, to);
}

// ── procurement_po_items ──────────────────────────────────────────────────────

// @table procurement_po_items
export function listProcurementPoItemsByPoId(poId: string | number | boolean) {
  return db()
    .from("procurement_po_items")
    .select("id, item_code, item_description, unit, quantity_ordered, quantity_delivered, unit_price")
    .eq("po_id", poId)
    .order("line_no");
}

// ── procurement_pos ───────────────────────────────────────────────────────────

// @table procurement_pos
export function listProcurementPosByProjectIdWithStatusApprovedIssuedPartiallyDelivered(projectId: string | number | boolean) {
  return db()
    .from("procurement_pos")
    .select("id, po_number, status, project_id, procurement_suppliers(supplier_name)")
    .eq("project_id", projectId)
    .in("status", ["approved", "issued", "partially_delivered"])
    .order("po_number");
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function listProfiles() {
  return db().from("profiles").select("id, full_name, email").order("full_name");
}

// ── projects ──────────────────────────────────────────────────────────────────

// @table projects
export function getProjectById(id: string | number | boolean) {
  return db().from("projects").select("id, project_code, project_name").eq("id", id).single();
}

// @table projects
export function listProjects() {
  return db().from("projects").select("id, project_code, project_name").order("project_code");
}

// @table projects
export function listProjectsOfIdAndProjectCodeAndProjectName() {
  return db().from("projects").select("id, project_code, project_name");
}

// ── wbs_nodes ─────────────────────────────────────────────────────────────────

// @table wbs_nodes
export function listWbsNodesByProjectId(projectId: string | number | boolean, columns: string) {
  return db().from("wbs_nodes").select(columns as "*").eq("project_id", projectId).order("wbs_code");
}

// ── wbs_tasks ─────────────────────────────────────────────────────────────────

// @table wbs_tasks
export function listWbsTasksByWbsNodeId(wbsNodeId: string | number | boolean) {
  return db()
    .from("wbs_tasks")
    .select("id, task_code, task_name, cost_code")
    .eq("wbs_node_id", wbsNodeId)
    .order("task_code");
}
