// Data access for the reporting-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── report_logs ───────────────────────────────────────────────────────────────

// @table report_logs
export function insertReportLog(row: object) {
  return db().from("report_logs").insert([row]);
}

// ── report_schedules ──────────────────────────────────────────────────────────

// @table report_schedules
export function deleteReportScheduleById(id: string | number | boolean) {
  return db().from("report_schedules").delete().eq("id", id);
}

// @table report_schedules
export function insertReportSchedule(row: object) {
  return db().from("report_schedules").insert([row]);
}

// @table report_schedules
export function listReportSchedules() {
  return db().from("report_schedules").select("*").order("created_at", { ascending: false });
}

// @table report_schedules
export function updateReportScheduleById(patch: object, id: string | number | boolean) {
  return db().from("report_schedules").update(patch).eq("id", id);
}
