-- Migration: 20260719000001_seed_tender_rbac.sql
-- Purpose: RBAC permission rows for the Pre-Contract / Tendering module.
--          11 actions mapping to the 11 tender cost estimation tabs.
-- Depends on: role_permissions (20260527000002_create_rbac_tables.sql),
--             roles seed (20260527000003_seed_rbac_data.sql),
--             pattern: 20260612000001_qs_rbac_and_vo_approvals.sql

-- ─── Tender Module Role Permissions ──────────────────────────────────────────
INSERT INTO public.role_permissions
  (role_code, module, action, view, can_create, edit, delete, submit, approve, reject, export, transmit, configure, reassign, scope)
VALUES
  -- TENDER REGISTER
  ('L0',      'tender','tender_register', true,  true,  true,  true,  true,  false, false, false, false, false, false, 'company'),
  ('L1',      'tender','tender_register', true,  true,  true,  true,  true,  false, false, false, false, false, false, 'company'),
  ('L2',      'tender','tender_register', true,  true,  true,  true,  true,  false, false, false, false, false, false, 'company'),
  ('L3',      'tender','tender_register', true,  true,  true,  false, true,  false, false, false, false, false, false, 'project'),
  ('QS',      'tender','tender_register', true,  true,  true,  false, false, false, false, false, false, false, false, 'company'),
  ('AC',      'tender','tender_register', true,  false, false, false, false, false, false, false, false, false, false, 'company'),
  ('PO',      'tender','tender_register', true,  true,  true,  false, true,  false, false, false, false, false, false, 'company'),
  ('L4',      'tender','tender_register', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L5',      'tender','tender_register', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L6',      'tender','tender_register', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'tender','tender_register', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-CON', 'tender','tender_register', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-SUB', 'tender','tender_register', false, false, false, false, false, false, false, false, false, false, false, null),

  -- TENDER BOQ
  ('L0',      'tender','tender_boq', true,  true,  true,  true,  false, false, false, true,  false, false, false, 'company'),
  ('L1',      'tender','tender_boq', true,  true,  true,  true,  false, false, false, true,  false, false, false, 'company'),
  ('L2',      'tender','tender_boq', true,  true,  true,  true,  false, false, false, true,  false, false, false, 'company'),
  ('L3',      'tender','tender_boq', true,  true,  true,  false, false, false, false, true,  false, false, false, 'project'),
  ('QS',      'tender','tender_boq', true,  true,  true,  true,  false, false, false, true,  false, false, false, 'company'),
  ('AC',      'tender','tender_boq', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('PO',      'tender','tender_boq', true,  true,  true,  false, false, false, false, true,  false, false, false, 'company'),
  ('L4',      'tender','tender_boq', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L5',      'tender','tender_boq', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L6',      'tender','tender_boq', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'tender','tender_boq', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-CON', 'tender','tender_boq', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-SUB', 'tender','tender_boq', true,  false, false, false, false, false, false, false, false, false, false, 'own'),

  -- TENDER PRICE LIST
  ('L0',      'tender','tender_price_list', true,  true,  true,  true,  false, false, false, true,  false, false, false, 'company'),
  ('L1',      'tender','tender_price_list', true,  true,  true,  true,  false, false, false, true,  false, false, false, 'company'),
  ('L2',      'tender','tender_price_list', true,  true,  true,  true,  false, false, false, true,  false, false, false, 'company'),
  ('L3',      'tender','tender_price_list', true,  true,  true,  false, false, false, false, true,  false, false, false, 'project'),
  ('QS',      'tender','tender_price_list', true,  true,  true,  true,  false, false, false, true,  false, false, false, 'company'),
  ('AC',      'tender','tender_price_list', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('PO',      'tender','tender_price_list', true,  true,  true,  false, false, false, false, true,  false, false, false, 'company'),
  ('L4',      'tender','tender_price_list', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L5',      'tender','tender_price_list', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L6',      'tender','tender_price_list', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'tender','tender_price_list', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CON', 'tender','tender_price_list', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-SUB', 'tender','tender_price_list', false, false, false, false, false, false, false, false, false, false, false, null),

  -- TENDER PRELIMINARIES
  ('L0',      'tender','tender_preliminaries', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('L1',      'tender','tender_preliminaries', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('L2',      'tender','tender_preliminaries', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('L3',      'tender','tender_preliminaries', true,  true,  true,  false, false, false, false, false, false, false, false, 'project'),
  ('QS',      'tender','tender_preliminaries', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('AC',      'tender','tender_preliminaries', true,  false, false, false, false, false, false, false, false, false, false, 'company'),
  ('PO',      'tender','tender_preliminaries', true,  true,  true,  false, false, false, false, false, false, false, false, 'company'),
  ('L4',      'tender','tender_preliminaries', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L5',      'tender','tender_preliminaries', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L6',      'tender','tender_preliminaries', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'tender','tender_preliminaries', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CON', 'tender','tender_preliminaries', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-SUB', 'tender','tender_preliminaries', false, false, false, false, false, false, false, false, false, false, false, null),

  -- TENDER BID SUMMARY
  ('L0',      'tender','tender_bid_summary', true,  true,  true,  false, true,  true,  false, false, false, false, false, 'company'),
  ('L1',      'tender','tender_bid_summary', true,  true,  true,  false, true,  true,  false, false, false, false, false, 'company'),
  ('L2',      'tender','tender_bid_summary', true,  true,  true,  false, true,  false, false, false, false, false, false, 'company'),
  ('L3',      'tender','tender_bid_summary', true,  true,  true,  false, true,  false, false, false, false, false, false, 'project'),
  ('QS',      'tender','tender_bid_summary', true,  true,  true,  false, true,  false, false, false, false, false, false, 'company'),
  ('AC',      'tender','tender_bid_summary', true,  false, false, false, true,  true,  false, false, false, false, false, 'company'),
  ('PO',      'tender','tender_bid_summary', true,  true,  true,  false, true,  false, false, false, false, false, false, 'company'),
  ('L4',      'tender','tender_bid_summary', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L5',      'tender','tender_bid_summary', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L6',      'tender','tender_bid_summary', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'tender','tender_bid_summary', true,  false, false, false, true,  true,  false, false, false, false, false, 'project'),
  ('EXT-CON', 'tender','tender_bid_summary', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-SUB', 'tender','tender_bid_summary', false, false, false, false, false, false, false, false, false, false, false, null),

  -- TENDER COVER PAGE
  ('L0',      'tender','tender_cover', true,  false, false, false, false, false, false, true,  true,  false, false, 'company'),
  ('L1',      'tender','tender_cover', true,  false, false, false, false, false, false, true,  true,  false, false, 'company'),
  ('L2',      'tender','tender_cover', true,  false, false, false, false, false, false, true,  true,  false, false, 'company'),
  ('L3',      'tender','tender_cover', true,  false, false, false, false, false, false, true,  false, false, false, 'project'),
  ('QS',      'tender','tender_cover', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('AC',      'tender','tender_cover', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('PO',      'tender','tender_cover', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('L4',      'tender','tender_cover', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L5',      'tender','tender_cover', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L6',      'tender','tender_cover', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'tender','tender_cover', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-CON', 'tender','tender_cover', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-SUB', 'tender','tender_cover', false, false, false, false, false, false, false, false, false, false, false, null),

  -- TENDER SUB QUOTES
  ('L0',      'tender','tender_sub_quotes', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('L1',      'tender','tender_sub_quotes', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('L2',      'tender','tender_sub_quotes', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('L3',      'tender','tender_sub_quotes', true,  true,  true,  false, false, false, false, false, false, false, false, 'project'),
  ('QS',      'tender','tender_sub_quotes', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('AC',      'tender','tender_sub_quotes', true,  false, false, false, false, false, false, false, false, false, false, 'company'),
  ('PO',      'tender','tender_sub_quotes', true,  true,  true,  false, false, false, false, false, false, false, false, 'company'),
  ('L4',      'tender','tender_sub_quotes', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L5',      'tender','tender_sub_quotes', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L6',      'tender','tender_sub_quotes', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'tender','tender_sub_quotes', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CON', 'tender','tender_sub_quotes', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-SUB', 'tender','tender_sub_quotes', true,  true,  true,  false, false, false, false, false, false, false, false, 'own'),

  -- TENDER RISKS
  ('L0',      'tender','tender_risks', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('L1',      'tender','tender_risks', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('L2',      'tender','tender_risks', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('L3',      'tender','tender_risks', true,  true,  true,  false, false, false, false, false, false, false, false, 'project'),
  ('QS',      'tender','tender_risks', true,  true,  true,  true,  false, false, false, false, false, false, false, 'company'),
  ('AC',      'tender','tender_risks', true,  false, false, false, false, false, false, false, false, false, false, 'company'),
  ('PO',      'tender','tender_risks', true,  true,  true,  false, false, false, false, false, false, false, false, 'company'),
  ('L4',      'tender','tender_risks', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L5',      'tender','tender_risks', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L6',      'tender','tender_risks', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'tender','tender_risks', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-CON', 'tender','tender_risks', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-SUB', 'tender','tender_risks', false, false, false, false, false, false, false, false, false, false, false, null),

  -- TENDER COST SUMMARY
  ('L0',      'tender','tender_cost_summary', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('L1',      'tender','tender_cost_summary', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('L2',      'tender','tender_cost_summary', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('L3',      'tender','tender_cost_summary', true,  false, false, false, false, false, false, true,  false, false, false, 'project'),
  ('QS',      'tender','tender_cost_summary', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('AC',      'tender','tender_cost_summary', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('PO',      'tender','tender_cost_summary', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('L4',      'tender','tender_cost_summary', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L5',      'tender','tender_cost_summary', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L6',      'tender','tender_cost_summary', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'tender','tender_cost_summary', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-CON', 'tender','tender_cost_summary', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-SUB', 'tender','tender_cost_summary', false, false, false, false, false, false, false, false, false, false, false, null),

  -- TENDER COST PER M2
  ('L0',      'tender','tender_cost_per_m2', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('L1',      'tender','tender_cost_per_m2', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('L2',      'tender','tender_cost_per_m2', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('L3',      'tender','tender_cost_per_m2', true,  false, false, false, false, false, false, true,  false, false, false, 'project'),
  ('QS',      'tender','tender_cost_per_m2', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('AC',      'tender','tender_cost_per_m2', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('PO',      'tender','tender_cost_per_m2', true,  false, false, false, false, false, false, true,  false, false, false, 'company'),
  ('L4',      'tender','tender_cost_per_m2', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L5',      'tender','tender_cost_per_m2', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L6',      'tender','tender_cost_per_m2', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'tender','tender_cost_per_m2', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-CON', 'tender','tender_cost_per_m2', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('EXT-SUB', 'tender','tender_cost_per_m2', false, false, false, false, false, false, false, false, false, false, false, null),

  -- TENDER BUDGET
  ('L0',      'tender','tender_budget', true,  false, true,  false, false, false, false, false, false, false, false, 'company'),
  ('L1',      'tender','tender_budget', true,  false, true,  false, false, false, false, false, false, false, false, 'company'),
  ('L2',      'tender','tender_budget', true,  false, true,  false, false, false, false, false, false, false, false, 'company'),
  ('L3',      'tender','tender_budget', true,  false, true,  false, false, false, false, false, false, false, false, 'project'),
  ('QS',      'tender','tender_budget', true,  false, false, false, false, false, false, false, false, false, false, 'company'),
  ('AC',      'tender','tender_budget', true,  false, false, false, false, false, false, false, false, false, false, 'company'),
  ('PO',      'tender','tender_budget', true,  false, false, false, false, false, false, false, false, false, false, 'company'),
  ('L4',      'tender','tender_budget', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L5',      'tender','tender_budget', true,  false, false, false, false, false, false, false, false, false, false, 'project'),
  ('L6',      'tender','tender_budget', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'tender','tender_budget', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CON', 'tender','tender_budget', false, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-SUB', 'tender','tender_budget', false, false, false, false, false, false, false, false, false, false, false, null)

ON CONFLICT (role_code, module, action) DO NOTHING;
