-- ============================================================
-- Migration 21: Extended Task Groups (discipline-specific)
-- Adds per-discipline workflow groups alongside existing generic groups.
-- ============================================================

insert into public.task_group_master (task_group_code, task_group_name, category, description) values
  ('ARC-DESDEV', 'Design Development', 'Design', 'ARC - Design Development tasks.'),
  ('ARC-CALC', 'Calculation & Compliance', 'Design', 'ARC - Calculation & Compliance tasks.'),
  ('ARC-SPEC', 'Specification', 'Design', 'ARC - Specification tasks.'),
  ('ARC-DRAW', 'Drawing Production', 'Design', 'ARC - Drawing Production tasks.'),
  ('ARC-SHOP', 'Shop Drawing Review', 'Design', 'ARC - Shop Drawing Review tasks.'),
  ('ARC-MAR', 'Material Approval (MAR)', 'Procurement', 'ARC - Material Approval (MAR) tasks.'),
  ('ARC-METHOD', 'Method Statement Review', 'Construction', 'ARC - Method Statement Review tasks.'),
  ('ARC-RFI', 'RFI Management', 'Design', 'ARC - RFI Management tasks.'),
  ('ARC-BIM', 'BIM Coordination', 'Design', 'ARC - BIM Coordination tasks.'),
  ('ARC-QS', 'Quantity Support', 'Design', 'ARC - Quantity Support tasks.'),
  ('ARC-CS', 'Construction Support', 'Construction', 'ARC - Construction Support tasks.'),
  ('ARC-INSP', 'Site Inspection', 'QAQC', 'ARC - Site Inspection tasks.'),
  ('ARC-ASB', 'As-built Drawing', 'Handover', 'ARC - As-built Drawing tasks.'),
  ('ARC-HANDOVER', 'Handover Documentation', 'Handover', 'ARC - Handover Documentation tasks.'),
  ('STR-DESBAS', 'Design Basis & Planning', 'Design', 'STR - Design Basis & Planning tasks.'),
  ('STR-ANAL', 'Structural Analysis & Calculation', 'Design', 'STR - Structural Analysis & Calculation tasks.'),
  ('STR-FND', 'Foundation Design', 'Design', 'STR - Foundation Design tasks.'),
  ('STR-SUPER', 'Superstructure Design', 'Design', 'STR - Superstructure Design tasks.'),
  ('STR-DRAW', 'Drawing Production', 'Design', 'STR - Drawing Production tasks.'),
  ('STR-SHOP', 'Shop Drawing Review', 'Design', 'STR - Shop Drawing Review tasks.'),
  ('STR-MAR', 'Material Approval Review (MAR)', 'Procurement', 'STR - Material Approval Review (MAR) tasks.'),
  ('STR-METHOD', 'Method Statement Review', 'Construction', 'STR - Method Statement Review tasks.'),
  ('STR-BIM', 'BIM Coordination', 'Design', 'STR - BIM Coordination tasks.'),
  ('STR-QS', 'Quantity & BOQ Support', 'Design', 'STR - Quantity & BOQ Support tasks.'),
  ('STR-RFI', 'RFI Management', 'Design', 'STR - RFI Management tasks.'),
  ('STR-CS', 'Construction Technical Support', 'Construction', 'STR - Construction Technical Support tasks.'),
  ('STR-INSP', 'Site Inspection', 'QAQC', 'STR - Site Inspection tasks.'),
  ('STR-ASB', 'As-built Drawing', 'Handover', 'STR - As-built Drawing tasks.'),
  ('STR-HANDOVER', 'Handover Documentation', 'Handover', 'STR - Handover Documentation tasks.'),
  ('MEP-DESDEV', 'Design Development', 'Design', 'MEP - Design Development tasks.'),
  ('MEP-CALC', 'Engineering Calculation', 'Design', 'MEP - Engineering Calculation tasks.'),
  ('MEP-EQ', 'Equipment Schedule', 'Design', 'MEP - Equipment Schedule tasks.'),
  ('MEP-DRAW', 'Drawing Production', 'Design', 'MEP - Drawing Production tasks.'),
  ('MEP-SHOP', 'Shop Drawing Review', 'Design', 'MEP - Shop Drawing Review tasks.'),
  ('MEP-MAR', 'Material Approval (MAR)', 'Procurement', 'MEP - Material Approval (MAR) tasks.'),
  ('MEP-METHOD', 'Method Statement Review', 'Construction', 'MEP - Method Statement Review tasks.'),
  ('MEP-BIM', 'BIM Coordination', 'Design', 'MEP - BIM Coordination tasks.'),
  ('MEP-QS', 'Quantity & BOQ Support', 'Design', 'MEP - Quantity & BOQ Support tasks.'),
  ('MEP-RFI', 'RFI Management', 'Design', 'MEP - RFI Management tasks.'),
  ('MEP-CS', 'Construction Technical Support', 'Construction', 'MEP - Construction Technical Support tasks.'),
  ('MEP-INSP', 'Site Inspection', 'QAQC', 'MEP - Site Inspection tasks.'),
  ('MEP-TC', 'Testing & Commissioning', 'Commissioning', 'MEP - Testing & Commissioning tasks.'),
  ('MEP-ASB', 'As-built Drawing', 'Handover', 'MEP - As-built Drawing tasks.'),
  ('MEP-HANDOVER', 'Handover Documentation', 'Handover', 'MEP - Handover Documentation tasks.'),
  ('PROC-PLAN', 'Procurement Planning', 'Procurement', 'PRC - Procurement Planning tasks.'),
  ('PROC-MR', 'Material Request (MR)', 'Procurement', 'PRC - Material Request (MR) tasks.'),
  ('PROC-PR', 'Purchase Requisition (PR)', 'Procurement', 'PRC - Purchase Requisition (PR) tasks.'),
  ('PROC-RFQ', 'RFQ / Tendering', 'Procurement', 'PRC - RFQ / Tendering tasks.'),
  ('PROC-TECHEVAL', 'Technical Evaluation', 'Procurement', 'PRC - Technical Evaluation tasks.'),
  ('PROC-COMEVAL', 'Commercial Evaluation', 'Procurement', 'PRC - Commercial Evaluation tasks.'),
  ('PROC-NEG', 'Supplier Negotiation', 'Procurement', 'PRC - Supplier Negotiation tasks.'),
  ('PROC-PO', 'Purchase Order (PO)', 'Procurement', 'PRC - Purchase Order (PO) tasks.'),
  ('PROC-MFG', 'Manufacturing Monitoring', 'Procurement', 'PRC - Manufacturing Monitoring tasks.'),
  ('PROC-LOG', 'Logistics & Delivery', 'Procurement', 'PRC - Logistics & Delivery tasks.'),
  ('PROC-GRN', 'Material Receiving (GRN)', 'Procurement', 'PRC - Material Receiving (GRN) tasks.'),
  ('PROC-INV', 'Invoice & Payment', 'Procurement', 'PRC - Invoice & Payment tasks.'),
  ('PROC-SUPPERF', 'Supplier Performance', 'Procurement', 'PRC - Supplier Performance tasks.'),
  ('PROC-CLOSEOUT', 'Contract Closeout', 'Procurement', 'PRC - Contract Closeout tasks.'),
  ('PROC-RPT', 'Procurement Reporting', 'Procurement', 'PRC - Procurement Reporting tasks.'),
  ('CON-SITEPREP', 'Site Preparation', 'Construction', 'CON - Site Preparation tasks.'),
  ('CON-SURV', 'Survey & Setting Out', 'Construction', 'CON - Survey & Setting Out tasks.'),
  ('CON-TEMPWORKS', 'Temporary Works', 'Construction', 'CON - Temporary Works tasks.'),
  ('CON-EARTH', 'Earthwork & Excavation', 'Construction', 'CON - Earthwork & Excavation tasks.'),
  ('CON-FND', 'Foundation Construction', 'Construction', 'CON - Foundation Construction tasks.'),
  ('CON-STRUCT', 'Structural Construction', 'Construction', 'CON - Structural Construction tasks.'),
  ('CON-ARCH', 'Architectural Construction', 'Construction', 'CON - Architectural Construction tasks.'),
  ('CON-MEPINS', 'MEP Installation', 'Construction', 'CON - MEP Installation tasks.'),
  ('CON-SITEMGT', 'Daily Site Management', 'Construction', 'CON - Daily Site Management tasks.'),
  ('CON-QAQC', 'QAQC & Inspection', 'QAQC', 'CON - QAQC & Inspection tasks.'),
  ('CON-HSE', 'HSE Coordination', 'HSE', 'CON - HSE Coordination tasks.'),
  ('CON-PROGRESS', 'Progress Monitoring', 'Construction', 'CON - Progress Monitoring tasks.'),
  ('CON-PUNCH', 'Snag & Punch List', 'Handover', 'CON - Snag & Punch List tasks.'),
  ('CON-CLOSEOUT', 'Project Closeout', 'Handover', 'CON - Project Closeout tasks.'),
  ('CON-HANDOVER', 'Handover Support', 'Handover', 'CON - Handover Support tasks.')
on conflict (task_group_code) do update set
  task_group_name = excluded.task_group_name,
  category = excluded.category,
  description = excluded.description;
