-- Seed data: Roles, Role Permissions, Approval Thresholds

insert into public.roles (code, name, type, level, description) values
  ('L0', 'Super Admin',          'internal_level', 0, 'Platform owner. Manages tenants, system configuration.'),
  ('L1', 'Managing Director',    'internal_level', 1, 'Full company control. Final approval authority.'),
  ('L2', 'General Manager',      'internal_level', 2, 'Company-wide operations. Second-level approval.'),
  ('L3', 'Project Manager',      'internal_level', 3, 'Full control within assigned projects.'),
  ('L4', 'Department Manager',   'internal_level', 4, 'Controls department workflow within own discipline.'),
  ('L5', 'Senior Engineer',      'internal_level', 5, 'Executes, reviews within own discipline.'),
  ('L6', 'Staff',                'internal_level', 6, 'Execution and submission. No approval authority.'),
  ('DC', 'Document Controller',  'functional', null, 'Manage document control, transmittals.'),
  ('PO', 'Procurement Officer',  'functional', null, 'Create PR/RFQ, receive quotations.'),
  ('QA', 'QA/QC Inspector',      'functional', null, 'Create inspection request, record results.'),
  ('HSE', 'HSE Officer',         'functional', null, 'Issue permits, log incidents.'),
  ('QS', 'QS / Cost Engineer',   'functional', null, 'Measure, value, prepare payment certificates.'),
  ('SS', 'Site Supervisor',      'functional', null, 'Create daily reports, update progress.'),
  ('SK', 'Storekeeper',          'functional', null, 'Receive materials, issue to site.'),
  ('HR', 'HR Officer',           'functional', null, 'Manage employee records, process leave.'),
  ('AC', 'Accountant',           'functional', null, 'Process invoices, prepare payments.'),
  ('BIM', 'BIM Coordinator',     'functional', null, 'Upload models, manage clash reports.'),
  ('PE', 'Planning Engineer',    'functional', null, 'Maintain schedule, report progress.'),
  ('EXT-CLT', 'Client / Owner',  'external', null, 'Contract principal. Approves milestones.'),
  ('EXT-CON', 'Consultant / PMC','external', null, 'Technical reviewer on behalf of Client.'),
  ('EXT-SUB', 'Subcontractor',   'external', null, 'Executes scope, submits progress.'),
  ('EXT-SUP', 'Supplier / Vendor','external', null, 'Receives PO, confirms delivery.'),
  ('EXT-REG', 'Regulatory Authority','external', null, 'Reviews authority submission packages.'),
  ('EXT-AUD', 'External Auditor','external', null, 'Read-only within defined audit scope.');

insert into public.role_permissions (role_code, module, action, view, can_create, edit, delete, submit, approve, reject, export, transmit, configure, reassign, scope) values
  ('L1', 'task_management', 'view_task', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L2', 'task_management', 'view_task', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L3', 'task_management', 'view_task', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L4', 'task_management', 'view_task', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L5', 'task_management', 'view_task', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L6', 'task_management', 'view_task', true, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'task_management', 'view_task', true, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CON', 'task_management', 'view_task', true, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-SUB', 'task_management', 'view_task', true, false, false, false, false, false, false, false, false, false, false, 'own'),
  ('L1', 'task_management', 'create_task', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L2', 'task_management', 'create_task', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L3', 'task_management', 'create_task', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L4', 'task_management', 'create_task', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L0', 'task_management', 'create_task', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'task_management', 'assign_task', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L2', 'task_management', 'assign_task', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L3', 'task_management', 'assign_task', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L4', 'task_management', 'assign_task', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L0', 'task_management', 'assign_task', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'task_management', 'reassign_task', false, false, false, false, false, false, false, false, false, false, true, null),
  ('L2', 'task_management', 'reassign_task', false, false, false, false, false, false, false, false, false, false, true, null),
  ('L3', 'task_management', 'reassign_task', false, false, false, false, false, false, false, false, false, false, true, null),
  ('L4', 'task_management', 'reassign_task', false, false, false, false, false, false, false, false, false, false, true, null),
  ('L0', 'task_management', 'reassign_task', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'task_management', 'update_progress', false, false, true, false, false, false, false, false, false, false, false, null),
  ('L2', 'task_management', 'update_progress', false, false, true, false, false, false, false, false, false, false, false, null),
  ('L3', 'task_management', 'update_progress', false, false, true, false, false, false, false, false, false, false, false, null),
  ('L4', 'task_management', 'update_progress', false, false, true, false, false, false, false, false, false, false, false, null),
  ('L5', 'task_management', 'update_progress', false, false, true, false, false, false, false, false, false, false, false, null),
  ('L6', 'task_management', 'update_progress', false, false, true, false, false, false, false, false, false, false, false, null),
  ('EXT-SUB', 'task_management', 'update_progress', false, false, true, false, false, false, false, false, false, false, false, 'own'),
  ('L1', 'task_management', 'submit_task', false, false, false, false, true, false, false, false, false, false, false, null),
  ('L2', 'task_management', 'submit_task', false, false, false, false, true, false, false, false, false, false, false, null),
  ('L3', 'task_management', 'submit_task', false, false, false, false, true, false, false, false, false, false, false, null),
  ('L4', 'task_management', 'submit_task', false, false, false, false, true, false, false, false, false, false, false, null),
  ('L5', 'task_management', 'submit_task', false, false, false, false, true, false, false, false, false, false, false, null),
  ('L6', 'task_management', 'submit_task', false, false, false, false, true, false, false, false, false, false, false, null),
  ('EXT-SUB', 'task_management', 'submit_task', false, false, false, false, true, false, false, false, false, false, false, 'own'),
  ('L1', 'task_management', 'approve_task', false, false, false, false, false, true, true, false, false, false, false, null),
  ('L2', 'task_management', 'approve_task', false, false, false, false, false, true, true, false, false, false, false, null),
  ('L3', 'task_management', 'approve_task', false, false, false, false, false, true, true, false, false, false, false, null),
  ('L0', 'task_management', 'approve_task', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'task_management', 'delete_task', false, false, false, true, false, false, false, false, false, false, false, null),
  ('L2', 'task_management', 'delete_task', false, false, false, true, false, false, false, false, false, false, false, null),
  ('L3', 'task_management', 'delete_task', false, false, false, true, false, false, false, false, false, false, false, null),
  ('L0', 'task_management', 'delete_task', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'task_management', 'export_task', false, false, false, false, false, false, false, true, false, false, false, null),
  ('L2', 'task_management', 'export_task', false, false, false, false, false, false, false, true, false, false, false, null),
  ('L3', 'task_management', 'export_task', false, false, false, false, false, false, false, true, false, false, false, null),
  ('L4', 'task_management', 'export_task', false, false, false, false, false, false, false, true, false, false, false, null),
  ('L5', 'task_management', 'export_task', false, false, false, false, false, false, false, true, false, false, false, null),
  ('L0', 'task_management', 'configure_task_workflow', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L0', 'admin_config', 'manage_tenant', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L0', 'admin_config', 'manage_users', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'admin_config', 'manage_users', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L2', 'admin_config', 'manage_users', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L0', 'admin_config', 'assign_roles', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'admin_config', 'assign_roles', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L2', 'admin_config', 'assign_roles', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L0', 'admin_config', 'change_permissions', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'admin_config', 'change_permissions', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L0', 'admin_config', 'configure_approval_workflow', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'admin_config', 'configure_approval_workflow', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L2', 'admin_config', 'configure_approval_workflow', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L3', 'admin_config', 'configure_approval_workflow', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L0', 'admin_config', 'configure_notification_rules', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'admin_config', 'configure_notification_rules', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L2', 'admin_config', 'configure_notification_rules', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L3', 'admin_config', 'configure_notification_rules', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L0', 'admin_config', 'configure_document_types', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'admin_config', 'configure_document_types', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L2', 'admin_config', 'configure_document_types', false, false, false, false, false, false, false, false, false, true, false, null),
  ('DC', 'admin_config', 'configure_document_types', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L0', 'admin_config', 'configure_wbs_templates', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'admin_config', 'configure_wbs_templates', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L2', 'admin_config', 'configure_wbs_templates', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L3', 'admin_config', 'configure_wbs_templates', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L0', 'admin_config', 'configure_cost_codes', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'admin_config', 'configure_cost_codes', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L2', 'admin_config', 'configure_cost_codes', false, false, false, false, false, false, false, false, false, true, false, null),
  ('AC', 'admin_config', 'configure_cost_codes', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L0', 'admin_config', 'configure_public_holidays', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'admin_config', 'configure_public_holidays', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L2', 'admin_config', 'configure_public_holidays', false, false, false, false, false, false, false, false, false, true, false, null),
  ('HR', 'admin_config', 'configure_public_holidays', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L0', 'admin_config', 'view_audit_logs', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L1', 'admin_config', 'view_audit_logs', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L2', 'admin_config', 'view_audit_logs', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L3', 'admin_config', 'view_audit_logs', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L4', 'admin_config', 'view_audit_logs', true, false, false, false, false, false, false, false, false, false, false, 'department'),
  ('L0', 'admin_config', 'export_audit_logs', false, false, false, false, false, false, false, true, false, false, false, null),
  ('L1', 'admin_config', 'export_audit_logs', false, false, false, false, false, false, false, true, false, false, false, null),
  ('L2', 'admin_config', 'export_audit_logs', false, false, false, false, false, false, false, true, false, false, false, null),
  ('L3', 'admin_config', 'export_audit_logs', false, false, false, false, false, false, false, true, false, false, false, null),
  ('L1', 'document_control', 'view_document', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L2', 'document_control', 'view_document', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L3', 'document_control', 'view_document', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L4', 'document_control', 'view_document', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L5', 'document_control', 'view_document', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L6', 'document_control', 'view_document', true, false, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CLT', 'document_control', 'view_document', true, false, false, false, false, false, false, false, false, false, false, 'own'),
  ('EXT-CON', 'document_control', 'view_document', true, false, false, false, false, false, false, false, false, false, false, 'own'),
  ('EXT-SUB', 'document_control', 'view_document', true, false, false, false, false, false, false, false, false, false, false, 'own'),
  ('EXT-REG', 'document_control', 'view_document', true, false, false, false, false, false, false, false, false, false, false, 'own'),
  ('EXT-AUD', 'document_control', 'view_document', true, false, false, false, false, false, false, false, false, false, false, null),
  ('L1', 'document_control', 'upload_document', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L2', 'document_control', 'upload_document', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L3', 'document_control', 'upload_document', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L4', 'document_control', 'upload_document', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L5', 'document_control', 'upload_document', false, true, false, false, false, false, false, false, false, false, false, null),
  ('EXT-CON', 'document_control', 'upload_document', false, true, false, false, false, false, false, false, false, false, false, null),
  ('EXT-SUB', 'document_control', 'upload_document', false, true, false, false, false, false, false, false, false, false, false, null),
  ('L1', 'document_control', 'approve_document', false, false, false, false, false, true, true, false, false, false, false, null),
  ('L2', 'document_control', 'approve_document', false, false, false, false, false, true, true, false, false, false, false, null),
  ('L3', 'document_control', 'approve_document', false, false, false, false, false, true, true, false, false, false, false, null),
  ('EXT-CLT', 'document_control', 'approve_document', false, false, false, false, false, true, true, false, false, false, false, null),
  ('EXT-CON', 'document_control', 'approve_document', false, false, false, false, false, true, true, false, false, false, false, null),
  ('EXT-REG', 'document_control', 'approve_document', false, false, false, false, false, true, true, false, false, false, false, 'own'),
  ('L1', 'document_control', 'transmit_document', false, false, false, false, false, false, false, false, true, false, false, null),
  ('L2', 'document_control', 'transmit_document', false, false, false, false, false, false, false, false, true, false, false, null),
  ('L3', 'document_control', 'transmit_document', false, false, false, false, false, false, false, false, true, false, false, null),
  ('L4', 'document_control', 'transmit_document', false, false, false, false, false, false, false, false, true, false, false, null),
  ('L1', 'document_control', 'delete_document', false, false, false, true, false, false, false, false, false, false, false, null),
  ('L2', 'document_control', 'delete_document', false, false, false, true, false, false, false, false, false, false, false, null),
  ('L0', 'document_control', 'configure_doc_types', false, false, false, false, false, false, false, false, false, true, false, null),
  ('L1', 'document_control', 'configure_doc_types', false, false, false, false, false, false, false, false, false, true, false, null);

insert into public.approval_thresholds (module, tier, min_amount, max_amount, approver_roles) values
  ('procurement_pr', 'tier_1', 0, 5000,         '{L3}'),
  ('procurement_pr', 'tier_2', 5000, 50000,     '{L3,L2}'),
  ('procurement_pr', 'tier_3', 50000, null,      '{L3,L2,L1}'),
  ('procurement_po', 'tier_1', 0, 10000,        '{L3}'),
  ('procurement_po', 'tier_2', 10000, 100000,   '{L2}'),
  ('procurement_po', 'tier_3', 100000, null,     '{L1}'),
  ('payment',        'tier_1', 0, 5000,         '{L3}'),
  ('payment',        'tier_2', 5000, 50000,     '{L2}'),
  ('payment',        'tier_3', 50000, null,      '{L1}'),
  ('variation_order','tier_1', 0, 10000,        '{L3,L4}'),
  ('variation_order','tier_2', 10000, 100000,   '{L2,L3}'),
  ('variation_order','tier_3', 100000, null,     '{L1,EXT-CLT}');
