-- Migration: 20260728000001_seed_inv_items_material_list.sql
-- Purpose: Seed inv_items with items from Material_List.md (CWIMS TLY project)
-- Spec: docs/03-Business-Modules/31-cwims/Item_Master_Mapping.md
-- Depends on: 20260621000001_create_inv_module_tables.sql, public.companies
--
-- Idempotent: ON CONFLICT (tenant_id, item_code) DO NOTHING

do $$
declare
  v_tenant_id uuid;
begin
  select id into v_tenant_id from public.companies where code = 'MCC';

  if v_tenant_id is null then
    raise exception 'inv_items seed: no company with code = MCC found';
  end if;

  insert into public.inv_items
    (tenant_id, item_code, name, category, sub_category, unit_of_measure,
     is_inspection_required, is_active, is_dg, is_batch_managed)
  values
    (v_tenant_id, 'TLY-001', 'Air Blow Motor -- 15cm', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-002', 'Air Conditioner LG -- 2Hp', 'mep', 'MEP Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-003', 'Aluminium Telescopic Ladder -- 6m', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-004', 'Aluminum Aliger -- 1.2m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-005', '4 Core Cable 8mm PVC Power Cable -- 10m', 'mep', 'Wire & Cable', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-006', 'Aluminum Ladder -- 3m', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-007', 'Aluminum Level Bar -- 1m', 'consumables', 'Hand Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-008', 'Aluminum Tripod Stand -- 1m', 'consumables', 'Measuring Tool', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-009', 'Aluminum Formwork -- 1m*50cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-010', 'Angle Drop -- 1.2m x 50cm', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-011', 'Angle Grinder Motor -- 1.25mm', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-012', 'Automatic Electric Cutter -- 2m', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-013', 'Barbed Wire Fencing -- 100m', 'structural', 'Fencing Materials', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-014', 'Bed Board (Worker Camp) -- 2m*1m', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-015', 'Bed Head (Worker Camp) -- 2m*1m', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-016', 'Black Rubber Water Hose -- 50m', 'mep', 'Pipe & Plumbing Materials', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-017', 'Blue Basket -- 1.1m x 1.1m', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-018', 'Bolt -- 2cm', 'structural', 'Fastener', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-019', 'Bookshelf -- 1.2m x 90cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-020', 'Box File A4 -- 50cm*50cm', 'others', 'Office Supplies', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-021', 'Brace Support -- 3.50 cm x 4.90 cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-022', 'Brick Tile -- 20cm*10cm', 'civil', 'Construction Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-023', 'Burlap Sack -- 1m*50cm', 'others', 'Packaging Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-025', 'Carpet Floor -- 50cm*50cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-026', 'CCTV Camera (Big) -- 15cm', 'consumables', 'Safety Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-027', 'CCTV Camera (Small) -- 10cm', 'consumables', 'Safety Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-028', 'CCTV Camera Mount -- 1m', 'consumables', 'Safety Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-029', 'CCTV Junction Box -- 10cm*10cm', 'consumables', 'Safety Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-030', 'CCTV Junction Box -- 20cm*30cm', 'consumables', 'Safety Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-031', 'Ceiling Board -- 50cm*50cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-032', 'Ceiling Fan -- 60cm', 'mep', 'MEP Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-033', 'Ceiling Fan Controller -- 10cm', 'mep', 'MEP Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-034', 'CFM Bathroom Exhaust Fan -- 0.50 M x 0.50 M', 'mep', 'Ventilation Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-035', 'CFM Inline Circular Fan -- 50cm*40cm', 'mep', 'Ventilation Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-036', 'Round Panel LED light 18W -- 18W/240V', 'mep', 'Lighting Equipment', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-037', 'Round Panel LED light -- 20W/240V', 'mep', 'Lighting Equipment', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-038', 'Clip Pin -- 2cm', 'structural', 'Fastener', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-039', 'CMED Tower Crane Logo -- 1.20 m x 4.00 m', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-040', 'Black Plastic Bucket -- 1.5m*60cm', 'consumables', 'Cleaning & Hygiene', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-041', 'Concrete Mixer Motor -- 2m*1.5m', 'others', 'Machinery', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-042', 'Concrete Polishing Machine -- 1.2m', 'others', 'Machinery', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-043', 'Container Storage -- 2.2 M x 4.9 M', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-044', 'Container Storage -- 2.4 M x 6.0 M', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-045', 'Copper Pipe -- 6m', 'mep', 'MEP Equipment', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-046', 'Corner Brackets -- 20cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-047', 'Corner Meter -- 1 M', 'consumables', 'Measuring Tool', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-048', 'Cotto Floor Tiles -- 30cm*30cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-049', 'Counter Weight -- 9 m', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-050', 'Crane Lifting Mixed Concrete Container Stock -- 1.20 M x 1.50 M', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-051', 'Cross Brace -- 1.70 cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-052', 'Cross Brace -- 2.00 M', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-053', 'Smart Curtain Motor -- 50cm', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-054', 'Cut-Off Saw 14″ (3.5HP) -- 50cm', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-055', 'DB Panel -- 50cm*60cm', 'mep', 'Electrical & Mechanical Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-056', 'Deformed Steel Bar Coil 6mm -- 50 M', 'structural', 'Fencing Materials', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-057', 'Deluxe Door Lockset -- 20cm', 'finishes', 'Door Hardware', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-058', 'Desk with Drawers -- 1.20 M x 7.50 cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-059', 'Doka 3D Coupler -- 20cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-060', 'Doka Adjustable Waling Extension FF20/50 (foot) -- 50cm*10cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-061', 'Expansion Bolt Metal -- D16mm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-062', 'Doka Beam H20 eco N -- 1.95m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-063', 'Doka Beam H20 eco N -- 2.45m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-064', 'Doka Beam H20 eco N -- 2.65m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-065', 'Doka Beam H20 eco N -- 2.9m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-066', 'Doka Beam H20 eco N -- 3.3m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-067', 'Doka Beam H20 eco N -- 3.9m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-068', 'Doka Beam H20 eco N -- 4.5m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-069', 'Doka Beam H20 eco N -- 4.9m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-070', 'Doka Bracket K -- 1m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-071', 'Doka Diagonal Cross -- 12.150m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-072', 'Doka Diagonal Cross -- 12.200m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-073', 'Doka Diagonal Cross -- 18.150m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-074', 'Doka Diagonal Cross -- 9.150m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-075', 'Doka Floor Prop Eurex 20 Eco550 -- 2.5m', 'structural', 'Prop', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-076', 'Scaffolding Frame -- D60mm/0.90cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-077', 'Scaffolding Frame -- D60mm/1.20cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-078', 'Scaffolding Frame -- D60mm/1.80cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-079', 'Doka Frame bracket 60 -- 1m*60m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-080', 'Doka Frame Panel -- 75cm*1.5m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-081', 'Doka Galvanised Trunking -- 2.4m*50m', 'mep', 'Cable Trunking', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-082', 'Doka Guided Climbing Formwork Xclimb 60 -- 0.3m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-083', 'Doka Handrail Clamp S -- 1m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-084', 'Doka Handrail Post T -- 1m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-085', 'Doka Internal PlateH20 Top50 -- 50cm*10cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-086', 'Doka Multi-Purpose Waling WS10 Top 50 -- 50cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-087', 'Doka Multi-Purpose Waling WS10 Top 50 -- 75cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-088', 'Doka Multi-Purpose Waling WS10 Top 50 -- 1m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-089', 'Doka Multi-Purpose Waling WS10 Top 50 -- 1.25m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-090', 'Doka Multi-Purpose Waling WS10 Top 50 -- 1.5m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-091', 'Doka Multi-Purpose Waling WS10 Top 50 -- 1.75m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-092', 'Doka Multi-Purpose Waling WS10 Top 50 -- 2m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-093', 'Doka Multi-Purpose Waling WS10 Top 50 -- 2.25m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-094', 'Doka Multi-Purpose Waling WS10 Top 50 -- 2.5m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-095', 'Doka Multi-Purpose Waling WS10 Top 50 -- 2.75m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-096', 'Doka Multi-Purpose Waling WS10 Top 50 -- 3m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-098', 'Doka Multi-Purpose Waling WS10 Top 50 -- 4m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-099', 'Doka Multi-Purpose Waling WS10 Top 50 -- 4.5m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-100', 'Doka Multi-Purpose Waling WS10 Top 50 -- 5m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-101', 'Doka Multi-Purpose Waling WS10 Top 50 -- 5.5m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-102', 'Doka Multi-Purpose Waling WS10 Top 50 -- 6m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-103', 'Doka Plumbing Spindle MF -- 4.5m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-104', 'Doka S Screw-on Handrailpost (Body) -- 1.5m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-105', 'Doka S Screw-on Handrailpost (Foot) -- 1.5m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-106', 'Doka Screw base Jack -- 50cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-107', 'Screw U-head -- 50cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-108', 'Doka S-joint Plate Type A -- 4.5m*20cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-109', 'Doka Spindle Strut T7250 -- 3m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-110', 'Doka S-Single Plate adj Waling Extention -- 60cm*20cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-111', 'Doka S-Suspension Profile Xclimb 60 ST 2 -- 3.5m*5cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-112', 'Doka S-Suspension Profile Xclimb 60 ST 3 -- 3m*5cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-114', 'Doka Stop Anchor -- 15.0 A17', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-115', 'Doka Stop Anchor -- 20.0 C17', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-116', 'Doka Supporting Carriage Xclimb 60 ST -- 60cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-117', 'Doka Top Scaffolding Bracket L -- 1m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-118', 'Doka Traveling Gear SK0.95m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-119', 'Dokaply Birch DC -- 2.5m*1.2m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-120', 'Door (Worker Camp) -- 2m*60cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-121', 'Door Closer -- 600-1200mm', 'finishes', 'Door Hardware', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-122', 'Door Hinges -- 10cm', 'finishes', 'Door Hardware', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-123', 'Door Stoppers -- 10cm', 'finishes', 'Door Hardware', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-125', 'Drill Motor -- 750W', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-126', 'Electric Cable -- 120mm', 'mep', 'Wire & Cable', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-127', 'Electric Cable -- 16mm', 'mep', 'Wire & Cable', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-128', 'Electric Cable 2.5mm', 'mep', 'Wire & Cable', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-129', 'Electric Cable 200mm', 'mep', 'Wire & Cable', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-130', 'Electric Cable 2.4mm', 'mep', 'Wire & Cable', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-131', 'Electric Cable 25mm', 'mep', 'Wire & Cable', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-132', 'Electric Cable 30mm', 'mep', 'Wire & Cable', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-133', 'Electric Cable 35mm', 'mep', 'Wire & Cable', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-134', 'Electric Cable 70mm', 'mep', 'Wire & Cable', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-135', 'Electric Cable 75mm', 'mep', 'Wire & Cable', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-136', 'Electric Cable 95mm', 'mep', 'Wire & Cable', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-137', 'Electric Circuit Breaker Box -- 30cm x 20cm', 'mep', 'Electrical & Mechanical Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-138', 'Engine Air Filter YK3043A -- 40cm x 70cm', 'mep', 'Ventilation Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-139', 'Portable Ventilation -- 50cm*50vm', 'mep', 'Ventilation Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-140', 'Exhaust Fan Hose -- D500mm', 'mep', 'Ventilation Equipment', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-141', 'Exterior Wall Round Lights -- 9W/220V', 'mep', 'Lighting Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-142', 'Face Scan Devices -- 20cm*10cm', 'others', 'Security Devices', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-143', 'Finger Print Machine -- 30cm*30cm', 'others', 'Office Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-144', 'Fire Damper (HVAC) -- 2.4m*50cm', 'mep', 'MEP Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-145', 'Fire Extinguisher -- 60cm', 'consumables', 'Safety Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-147', 'Flood LED Light -- 30cm*20cm', 'mep', 'Lighting Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-148', 'Floor Number Sign -- 60cm*60cm', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-149', 'Folding Chair -- 60cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-150', 'Folding Table -- 2.4m*60cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-151', 'Folding Table -- 1.2m*50cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-152', 'Forging Motor -- 1.5m', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-153', 'FR CV Power Cable 0.6/1kV length 50m', 'mep', 'Wire & Cable', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-154', 'FR-LH Power Cable 0.6/1kV length 500m', 'mep', 'Wire & Cable', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-155', 'Fuji Xerox Color Photocopier Doccenter SC2020 -- 1.2m*60cm', 'others', 'Office Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-156', 'Galvanised Cable Trunking -- 1.5m*50cm', 'mep', 'Cable Trunking', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-157', 'Galvanized Angle Bar -- 25cm*25cm, 5m', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-158', 'Generator Oil Filters (Black) -- 20cm', 'others', 'Machinery Spare Parts', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-159', 'Generator Oil Filters (White) -- 20cm', 'others', 'Machinery Spare Parts', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-160', 'Glass Block Bathroom -- D80mm/190mmx190mm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-161', 'Glass Cabinet -- 50cm*70cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-162', 'Glass Door -- 80cm*19cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-163', 'Glass Door Handles -- VVP-30cm', 'finishes', 'Door Hardware', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-164', 'Glass Window -- 1m*50cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-165', 'Glass Window -- 50cm*60cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-166', 'Glass Wool Dealers -- 1.2m*50cm', 'finishes', 'Finishing Material', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-169', 'Gypsum Board Ceilings -- 1m', 'finishes', 'Finishing Material', 'Sheet', false, true, false, false),
    (v_tenant_id, 'TLY-170', 'Hand Lab Washing -- 30cm*30cm', 'consumables', 'Cleaning & Hygiene', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-171', 'Hand Lab Washing -- 50cm*50cm', 'consumables', 'Cleaning & Hygiene', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-172', 'Hoist Trolley Mechanism Of Tower Crane -- 100m', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-173', 'Hose Fire Box -- 15cm*60cm', 'consumables', 'Safety Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-174', 'Hydraulic Cylinder Xclimb 60 DA -- 50cm', 'mep', 'Wire & Cable', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-175', 'Hydraulic Distributor Xclimb 60 V4 -- 1m*50cm', 'mep', 'Wire & Cable', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-176', 'Hydraulic Hose SKE -- 6.5m', 'mep', 'Pipe & Plumbing Materials', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-177', 'Hydraulic Unit Xclimb 60V45 50/60Hz -- 1m*50cm', 'mep', 'Wire & Cable', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-178', 'Interlocking PVC Floor Tiles -- 50cm*50cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-179', 'Laminate Wood grain Flooring IV331 -- D8mm/1.288X192', 'finishes', 'Finishing Material', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-180', 'LED 1000W', 'mep', 'Lighting Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-181', 'LED 250W', 'mep', 'Lighting Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-182', 'LED 40W', 'mep', 'Lighting Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-183', 'Fluorescent LED lamp -- 1.2m', 'mep', 'Lighting Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-184', 'Fluorescent LED Light -- 1.2m', 'mep', 'Lighting Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-185', 'LED Tube Light -- 18W/60cm', 'mep', 'Lighting Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-186', 'Leica Lino L2P5 -- 10cm*10cm', 'consumables', 'Measuring Tool', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-187', 'Light Sensor -- 10cm', 'mep', 'Lighting Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-188', 'Light Stand -- 1m', 'mep', 'Lighting Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-189', 'Loading Platform -- 3.5m*4.5m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-190', 'Loading Platform -- 3m*5m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-191', 'Lock Entry Trim Door Lever -- 20cm', 'finishes', 'Door Hardware', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-192', 'Marble Black -- 1.2m*60cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-194', 'Marble Gray -- 1.2m*60cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-195', 'Marble Weight of Umbrella -- 30cm*30cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-196', 'Metal 2 Drawer File Cabinet -- 55cm*40cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-197', 'Nail 6mm -- 50cm', 'structural', 'Fastener', 'Box', false, true, false, false),
    (v_tenant_id, 'TLY-198', 'CAT6 Network Cable -- 50m', 'others', 'Networking Equipment', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-199', 'Nut -- 10cm', 'structural', 'Fastener', 'Box', false, true, false, false),
    (v_tenant_id, 'TLY-200', 'Nylon Cable Puller Rod -- 2m', 'mep', 'Wire & Cable', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-201', 'Office Container -- 3.8m*6m', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-202', 'Hydraulic Hoses Xclimb 60 DA -- 17.00m', 'mep', 'Pipe & Plumbing Materials', 'Pair', false, true, false, false),
    (v_tenant_id, 'TLY-203', 'Panel Socket -- 15cm', 'mep', 'Cable Trunking', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-204', 'Partition Cabinet -- 90cm*55cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-205', 'Pin of Mast Tower Crane -- 20cm', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-206', 'Plywood -- 2m x 60cm', 'structural', 'Formwork System', 'Sheet', false, true, false, false),
    (v_tenant_id, 'TLY-207', 'Plywood (Worker Camp) -- 2m*1.2m', 'others', 'Furniture', 'Sheet', false, true, false, false),
    (v_tenant_id, 'TLY-208', 'Plywood Adhesive -- 3.50L', 'finishes', 'Sealant & Adhesives', 'Bottle', false, true, false, false),
    (v_tenant_id, 'TLY-209', 'Polisher Motor -- 20cm', 'others', 'Machinery', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-210', 'Porcelain Glazed Tiles -- 60*30 cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-211', 'Porcelain Mat Gray -- 1.2m*60cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-212', 'Porcelain Tiles -- 80cm*80cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-213', 'Power Steering Hose -- 10m', 'mep', 'Pipe & Plumbing Materials', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-214', 'PPR Tee -- 15mm', 'mep', 'Pipe & Plumbing Materials', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-215', 'Printer imageRUNNER ADVANCE C3330i -- 1m*60cm', 'others', 'Office Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-216', 'PVC Hose Pipe -- 10m', 'mep', 'Water Storage Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-217', 'PVC Red Chair -- 30cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-218', 'Rolling Pallet Truck -- 2.5T', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-219', 'Rolling Scaffolding -- 30cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-220', 'Roof Panel (Worker Camp) -- 4.5m*1m', 'structural', 'Roofing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-221', 'Rope -- 30mm', 'mep', 'Wire & Cable', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-222', 'Rotary Hammer Drill Motor -- 1800W', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-223', 'Safety Belt -- 1m', 'consumables', 'Safety Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-224', 'Sample Board -- 1.2m*80cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-225', 'Scaffolding 2m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-226', 'Fastener -- 10cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-227', 'Scaffolding Frame -- 1.7m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-228', 'Scaffolding Frame -- 2m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-229', 'Scaffolding Jack Bass -- 50cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-230', 'Scaffolding Join Pin -- 20cm', 'structural', 'Join Pin', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-231', 'Scaffolding Platform -- 1.2m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-232', 'U-Head Support -- 50cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-233', 'Security Guard Post -- 2m*1.5m', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-234', 'Sensor of Urinal for Male KOHLEP -- 20cmX20cm', 'mep', 'Sanitary', 'Sheet', false, true, false, false),
    (v_tenant_id, 'TLY-235', 'Septic Tank -- 1.2m*1.5m', 'mep', 'Sanitary', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-236', 'Server Rack -- 70cm*80cm', 'others', 'Networking Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-237', 'Silicone Sealant for Aquarium Glass -- 50cm', 'finishes', 'Sealant & Adhesives', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-238', 'Silicone Sealant for Aquarium Glass with Gun (Blue) -- 60cm', 'finishes', 'Sealant & Adhesives', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-239', 'Silicone Sealant for Aquarium Glass with Gun (Red) -- 60cm', 'finishes', 'Sealant & Adhesives', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-240', 'Small Pin -- 7cm', 'structural', 'Fastener', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-241', 'Sofar -- 1.2m*70cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-242', 'Split Flexible Conduit -- 20m', 'mep', 'Cable Trunking', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-243', 'Spraying Machine -- 1m', 'others', 'Machinery', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-244', 'Spun Pile -- 6m', 'civil', 'Foundation Materials', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-245', 'Stainless Steel Flat Bar -- 3mm*5m', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-246', 'Stainless Steel Round Chair -- 40cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-247', 'Stainless Steel Window -- 90cm*1m', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-248', 'Stainless Water Tank -- 5000L /6m*1.2m', 'mep', 'Water Storage Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-249', 'Stair (Worker Camp) -- 3m*1.2m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-250', 'Steel A (Worker Camp) -- 1.2m*1m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-251', 'Steel Bolt Cutter -- 1m', 'consumables', 'Hand Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-252', 'Steel C (Worker Camp) -- 3m*5cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-253', 'Galvanised Steel Wire Rope 2.50cm -- 6m', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-254', 'Galvanised Steel Wire Rope 50cm', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-255', 'Steel Cross (Worker Camp) -- 1m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-256', 'Steel Door -- 2m* 1.2m', 'finishes', 'Door Hardware', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-257', 'Steel Pipe -- 1.2m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-258', 'Steel Pipe -- 1.5m*3cm', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-259', 'Steel Pipe -- 2m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-260', 'Steel Pipe -- 4m*6m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-261', 'Steel Pipe -- 6m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-262', 'Steel Plate -- 1.5m*15mm*6m', 'structural', 'Plate Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-263', 'Steel Plate -- 2.5m*4.5m*25mm', 'structural', 'Plate Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-264', 'Steel Bars -- 14mm*12m', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-265', 'Steel Bars -- 16mm*12m', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-266', 'Steel Bars -- 20mm*12m', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-267', 'Steel Bars -- 25mm*12m', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-268', 'Steel Bars -- 32mm*12m', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-269', 'Steel Bars -- 32mm*4m', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-270', 'Steel Receipt (Worker Camp) -- 1.2m*1m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-271', 'Steel Tube 100×100 mm -- 3m', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-272', 'Steel Tube 100×100 mm -- 5m', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-273', 'Steel Tube 100×100 mm -- 4m', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-274', 'Steel Tube 100×100 mm -- 1.50cm', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-275', 'Steel Tube 100×100 mm -- 2.50cm', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-276', 'Steel Tube 100×100 mm -- 6.00cm', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-278', 'Steel Tube 50×100 mm -- 1m*50cm', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-279', 'Steel Tube 50×100 mm -- 4.50cm', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-280', 'Steel Tube 50×100 mm -- 6m', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-281', 'Steel Tube 50×100 mm -- 4m', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-282', 'Steel Tube 50×100 mm -- 2.50cm', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-283', 'Steel Tube 50×100 mm -- 6.00cm', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-285', 'Steel Tube 50×50 mm -- 2.50cm', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-286', 'Steel Tube 50×50 mm -- 6m', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-287', 'Steel Tube 50×50 mm -- 4m', 'structural', 'Steel Tube', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-288', 'Steel V -- 6m', 'structural', 'Metal Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-289', 'Steel Vertical Filing Cabinet with 4 Drawers -- 1.2m*60cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-290', 'Steel Wire Mesh -- 50m', 'structural', 'Mesh Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-291', 'Submersible Water Pump -- 50cm', 'mep', 'MEP Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-292', 'Submersible Water Pump -- 1.2m', 'mep', 'MEP Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-293', 'Syringe Bottle Adapter -- 15cm', 'others', 'Medical Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-294', 'Syringe Cylinder Injection -- 5cm', 'others', 'Medical Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-295', 'Wood Table Pieces -- 1.35cm * 1.50cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-296', 'Tempered Clear Glass Panel -- 900x2250x12mm thk.', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-297', 'Tent -- 3m * 120cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-298', 'Tie Wire (Small) -- 20cm', 'structural', 'Mesh Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-299', 'Tile -- 1.2m*60cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-300', 'Tile -- 1.2m*2m', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-302', 'Tile -- 60cm*60cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-305', 'Tile Cutter -- 1m', 'consumables', 'Hand Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-306', 'Grout Grey -- 20cm*15cm', 'finishes', 'Sealant & Adhesives', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-307', 'Tile Size 300x300x7.5mm thk -- 30cm*30cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-308', 'Tile Walkway -- 1m*20cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-309', 'Tiles 120cm*60cm (White) -- 1.2m*60cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-310', 'Tiles 120cm*60cm (Yellow) -- 1.2m*60cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-311', 'Tiles 60cm*30cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-312', 'Tiles 80cm*80cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-313', 'Toilet Container -- 2.4m*3m', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-314', 'Toilet Container -- 2.4m*6m', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-315', 'Toilet Seal Cover -- 50cm', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-316', 'Toilet Tower Bar Amarica standars -- 600mm/K-1393', 'mep', 'Sanitary', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-317', 'Tower Crane Connection Section -- 50cm', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-318', 'Tower Crane Fixed Leg -- 50cm', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-319', 'Tower Crane Jib Length 10m', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-320', 'Tower Crane Mast Section -- 3m', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-321', 'Tower Crane Mast Section -- 7m', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-322', 'Tower Crane Operator Cabin -- 2m*1.5m', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-323', 'Tower Crane Turntable -- 2.4m*2.4m', 'structural', 'Tower Crane Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-324', 'Transformer 250KVA', 'mep', 'Electrical & Mechanical Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-325', 'Transformer 500KVA', 'mep', 'Electrical & Mechanical Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-326', 'Transformer 650 KWA', 'mep', 'Electrical & Mechanical Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-327', 'Trash Bin -- 1.2m', 'mep', 'Sanitary', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-328', 'Triple Water Booster Pump -- 1.2m', 'mep', 'MEP Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-329', 'Aluminium Pipe (U-shape) -- 50cm', 'mep', 'Pipe & Plumbing Materials', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-330', 'Umbrella', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-331', 'Urine Toilet For Men -- 60cm', 'mep', 'Sanitary', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-332', 'Vacuum Cleaner -- 60cm', 'consumables', 'Cleaning & Hygiene', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-333', 'Vertical Profile Xclimb 60ST -- 5.35m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-334', 'Vertical Waling MF -- 4.50m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-335', 'Wall Groove Cutting Motor -- 50cm', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-336', 'Wall Mounted Rainfall Shower -- 1.2m', 'mep', 'Sanitary', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-337', 'Wall Panel (Worker Camp) -- 1.2m*1m', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-338', 'Wall-Mounted Toilet Paper Holder -- 1.2m*1m', 'mep', 'Sanitary', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-339', 'Wallpaper Decor -- 10m', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-340', 'Washing Machine TOSHIBA -- 1m*60cm', 'others', 'Office Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-341', 'Water Closet -- 50cm', 'mep', 'Sanitary', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-342', 'PVC Water Tank -- 1.5m*1.2m', 'mep', 'Water Storage Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-343', 'Welding Helmet -- 40cm', 'consumables', 'Safety Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-344', 'Welding Motor -- 40cm', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-345', 'WiFi Router -- 20cm', 'others', 'Networking Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-346', 'Wiltec Traffic Mirror -- 60cm*60cm', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-347', 'Window Frame (Worker Camp) -- 60cm*60cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-348', 'Wire Mesh Fish Bowl -- 1m', 'structural', 'Mesh Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-349', 'Wood Panel -- 1.2m*50cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-350', 'Wood Panel -- 1.5m*70cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-351', 'Zinc Plate -- 2.3m*1.2m', 'structural', 'Roofing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-352', 'FR-LH Power Cable length 5m', 'mep', 'Wire & Cable', 'Roll', false, true, false, false),
    (v_tenant_id, 'TLY-353', 'Wood Door -- 2m*60cm', 'others', 'Furniture', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-354', 'Welding Machine Daiyo -- DY-201N', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-355', 'S-Screw-on handrailpost ( Foot) -- DOKA-1.5m', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-356', 'Swivel fastener -- D48mm', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-357', 'Planking Hinge -- 39cm', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-358', 'S-Element Holder SK', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-359', 'Waling to Bracket Holder -- 9-15cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-360', 'Locking rod -- 15.0 330mm', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-361', 'Corner waling -- 45cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-362', 'Universal angle tie bracket', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-363', 'Super plate ( nut steel thread) 15.0 -- D17mm', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-364', 'Roller unite SK', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-365', 'S-Spindle strut connector SK', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-366', 'S-Roller stop SK', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-367', 'S-Strut connector', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-368', 'Connector -- WS10  Xclimb 60', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-369', 'S-Clamping shoe', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-370', 'S-Distancer -- 1', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-371', 'S-Platform strut', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-372', 'Connecting pin -- 25cm', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-373', 'Cone screw ( Bolt) -- B-7cm', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-374', 'Connecting pin -- 10cm', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-375', 'Tie rod non-treated -- 15.0mm/0.35m', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-376', 'Turnbuckle A', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-377', 'Clamping plate D', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-378', 'Brace stirrup 8', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-379', 'Universal climbing cone -- 20.0 2G', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-380', 'S-Platform profile -- Short N.4000', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-381', 'S-Platform profile SKE100plus -- 1.3m', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-382', 'S-Clamping plate ( steel plate) -- Square', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-383', 'S-Bolting plate SK -- Square', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-384', 'S-Waling connector', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-385', 'S-Distancer -- 2', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-386', 'S-Distancer -- 3', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-387', 'S-Joint plate -- A&B  L500mm', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-388', 'Horizontal profile xclimb 60 -- 2.45m', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-389', 'Doka Multi-Purpose Waling WS10 Top 50 -- 2.65m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-390', 'Doka Multi-Purpose Waling WS10 Top 50 -- 3.25m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-391', 'S-Roller support -- N.4018', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-392', 'Screw-on coupler -- D48mm/N.50', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-393', 'Screw-on coupler -- D48mm/N.95', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-394', 'Doka Multi-Purpose Waling WS10 Top 50 -- 2.55m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-395', 'S-U150 for horizontal ccnnection -- N.4042', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-396', 'Doka Beam H20 eco N -- 1.5m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-397', 'Doka Beam H20 eco N -- 1.3m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-398', 'Doka Beam H20 eco N -- 3m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-399', 'Doka Beam H20 eco N -- 5.9m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-400', 'Doka Beam H20 eco N -- 3.6m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-401', 'Doka Beam H20 eco N -- 7m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-402', 'Doka Beam H20 eco N -- 6.7m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-403', 'Doka Beam H20 eco N -- 6m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-404', 'Doka Beam H20 eco N -- 6.5m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-405', 'Doka Beam H20 eco N -- 5.5m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-406', 'Doka Beam H20 eco N -- 5m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-407', 'Doka Beam H20 eco N -- 2m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-408', 'Doka Beam H20 eco N -- 9.45m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-409', 'Doka Beam H20 eco N -- 12m', 'structural', 'Doka Beam', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-410', 'Scaffold tube (steel pip white) -- D48mm/3mm/ 2.5m', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-411', 'Scaffold tube (steel pip white) -- D48mm/3mm/3m', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-412', 'Scaffold tube (steel pip white) -- D48mm/3mm/3.5m', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-413', 'Safety net fan extra wide -- 4.80x5.85m', 'consumables', 'Safety Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-414', 'Safety net fan extra wide -- 4.80x4mm', 'consumables', 'Safety Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-415', 'Double fastener -- D48mm', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-416', 'Wind lock', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-417', 'Anchor Bolt -- M12x120', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-418', 'Assembly stool', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-419', 'Slab attachment adustable', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-420', 'Nut -- M12', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-421', 'Diagonal tube steel pip \whit) -- 4.25m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-422', 'Diagonal tube extension (steel pip whit)', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-423', 'Tube body (steel pip whit) -- 3.25m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-424', 'Extension leg (steel pip whit) -- 1.5m', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-425', 'Narrowside', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-426', 'Diagonal cross brace -- 18.20cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-427', 'Diagonal cross brace -- 9.100cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-428', 'Diagonal cross brace -- 12.250cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-429', 'Diagonal cross brace -- 18.25cm', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-430', 'S-Suspension profile xclimp 60 ST 1', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-431', 'Fixed loading platform 5.0 ton', 'structural', 'Formwork System', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-432', 'Scaffolding -interanal -- 1.8m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-433', 'Steel staircase -- 2m', 'structural', 'Scaffolding', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-434', 'PVC pip Blue -- D27mmx4m', 'mep', 'MEP Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-435', 'Electric Cable -- D3mm', 'mep', 'Wire & Cable', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-436', 'Electric Cable -- D5mm', 'mep', 'Wire & Cable', 'M', false, true, false, false),
    (v_tenant_id, 'TLY-437', 'Plat jack -- 2.5T', 'consumables', 'Power Tools', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-438', 'Boom kit concret', 'others', 'Machinery', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-439', 'Main power system', 'others', 'Concrete Plastering Boom', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-440', 'Electric System', 'others', 'Concrete Plastering Boom', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-441', 'Tubular column', 'others', 'Concrete Plastering Boom', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-442', 'Middle platform ( climbing frame )', 'others', 'Concrete Plastering Boom', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-443', 'Climbing device in elevator well (option )', 'others', 'Concrete Plastering Boom', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-444', 'Climping device on floor', 'others', 'Concrete Plastering Boom', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-445', 'Sponge concrete pump pipe cleaning ball', 'others', 'Concrete Plastering Boom', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-446', 'Tool box and remote control system', 'others', 'Concrete Plastering Boom', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-447', 'Standing support', 'others', 'Concrete Plastering Boom', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-448', 'Meeting table -- 80cm x L1.8m', 'others', 'Meeting Table', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-449', 'Wood box', 'others', 'Wood Box', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-450', 'Steel grating Gavernize -- 1mx37cm', 'structural', 'Construction Inventory', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-451', 'Electric box -- 60cm x 40cm', 'mep', 'MEP Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-452', 'Electric box -- 30cm x 40cm', 'mep', 'MEP Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-453', 'Fire hose cabinet -- 60cm x 1.2m', 'mep', 'MEP Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-454', 'HDPE pipe under ground -- D400mm x 6m', 'mep', 'Pipe & Plumbing Materials', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-455', 'Cart-brick -- 2wheel', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-456', 'Cart-Cement -- 2wheel', 'others', 'Site Equipment', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-457', 'Natural granite marble GRAY -- 60cm x 60cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-458', 'Natural granite curb -- 45cm x 30cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-459', 'Natural granite polish Black -- 30cm x 60cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-460', 'Porcelain Mat Gray -- 1.2m x 70cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-461', 'Natural granite marble WHITE -- 60cm x 60cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-462', 'Marble Big black -- 1.56m x 2.5m', 'finishes', 'Finishing Material', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-463', 'Marble Big gray', 'finishes', 'Finishing Material', 'Set', false, true, false, false),
    (v_tenant_id, 'TLY-464', 'Concrete Pip -- D600mmx 2.5m', 'civil', 'Construction Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-465', 'Manhole big -- H 1.5m x 1.3m', 'civil', 'Construction Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-466', 'Manhole -- H1.24m x 1.3m', 'civil', 'Construction Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-467', 'Cover manhol -- 60cmx40cm', 'civil', 'Construction Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-468', 'Mable -- 2mx22cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-469', 'Mable -- 1mx22cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-470', 'Mable -- 1.3m45cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-471', 'Mable -- 1.3mx40cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-472', 'Mable -- 1.3mx30cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false),
    (v_tenant_id, 'TLY-473', 'Mable -- 1mx22cm', 'finishes', 'Finishing Material', 'Pc', false, true, false, false);

  raise notice 'inv_items seed: % rows in inv_items for MCC', (select count(*) from public.inv_items where tenant_id = v_tenant_id);
end $$;
