-- Migration: 20260918000003_activity_step_template_seed_data.sql
-- Purpose: Seed the full Activity Step Template library from
--          docs/Activity_Step_Templates_Architectural_MEP.xlsx ("Template
--          Index" + "All Step Templates" sheets) — 70 templates across 8
--          disciplines (Architectural Finishes, MEP First/Second Fix, MEP
--          Final Fix / Plant, Structure & Early Works, Temporary Works,
--          Drywall & Special Partitions, External Works & Handover),
--          395 weighted steps total. Every template''s step weights sum to
--          100 (validated at generation time from the source workbook).
-- Depends on: 20260918000001_activity_step_templates.sql (base tables),
--             20260918000002_activity_step_template_fields.sql (discipline /
--             resource_crew / est_duration_days / inspection_hold_point
--             columns used below).
-- Idempotent: safe to re-run — templates are upserted by (group_name,
--             template_name), items by (template_id, step_no).

-- ────────────────────────────────────────────────────────────────────────
-- 1. Template masters (70 rows)
-- ────────────────────────────────────────────────────────────────────────
insert into public.activity_step_template_master (group_name, template_name, description, is_active)
values
  ('Architectural Finishes', 'Blockwork / Masonry – Typical Floor', 'GF–7F Blockwork activity', true),
  ('Architectural Finishes', 'Internal Partition – Typical Floor', 'GF–7F Internal Partition', true),
  ('Architectural Finishes', 'Plastering (Internal) – Typical Floor', 'GF–7F Plastering', true),
  ('Architectural Finishes', 'Waterproofing (Wet Areas) – Typical Floor', 'Wet areas only', true),
  ('Architectural Finishes', 'Screed – Typical Floor', 'GF–7F Screed', true),
  ('Architectural Finishes', 'Ceiling – Typical Floor', 'GF–7F Ceiling', true),
  ('Architectural Finishes', 'Flooring – Typical Floor', 'GF–7F Flooring', true),
  ('Architectural Finishes', 'Wall Tiling – Typical Floor', 'GF–7F Wall Tiling', true),
  ('Architectural Finishes', 'Stone / Marble – Typical Floor', 'Stone / Marble areas', true),
  ('Architectural Finishes', 'Internal Painting – Typical Floor', 'GF–7F Internal Painting', true),
  ('Architectural Finishes', 'Door Frames – Typical Floor', 'GF–7F Door Frames', true),
  ('Architectural Finishes', 'Doors (Leaf + Ironmongery) – Typical Floor', 'GF–7F Doors', true),
  ('Architectural Finishes', 'Windows / Glazing – Typical Floor', 'GF–7F Windows / Glass', true),
  ('MEP First Fix', 'Electrical Conduits – Typical Floor', 'GF–7F Electrical Conduits', true),
  ('MEP First Fix', 'Cable Trays – Typical Floor', 'GF–7F Cable Trays', true),
  ('MEP First Fix', 'Plumbing Pipes – Typical Floor', 'GF–7F Plumbing Pipes', true),
  ('MEP First Fix', 'Drainage Pipes – Typical Floor', 'GF–7F Drainage Pipes', true),
  ('MEP First Fix', 'HVAC Ductwork – Typical Floor', 'GF–7F HVAC Ductwork', true),
  ('MEP First Fix', 'HVAC Pipes – Typical Floor', 'GF–7F HVAC Pipes', true),
  ('MEP First Fix', 'Fire Fighting Pipes – Typical Floor', 'GF–7F Fire Fighting Pipes', true),
  ('MEP First Fix', 'Fire Alarm Conduits – Typical Floor', 'GF–7F Fire Alarm Conduits', true),
  ('MEP First Fix', 'ELV Conduits – Typical Floor', 'GF–7F ELV Conduits', true),
  ('MEP Second Fix', 'Cable Pulling – Typical Floor', 'GF–7F Cable Pulling', true),
  ('MEP Second Fix', 'DB Installation – Typical Floor', 'GF–7F DB Installation', true),
  ('MEP Second Fix', 'Lighting Installation – Typical Floor', 'GF–7F Lighting', true),
  ('MEP Second Fix', 'Switches & Sockets – Typical Floor', 'GF–7F Switches & Sockets', true),
  ('MEP Second Fix', 'Plumbing Fixtures – Typical Floor', 'GF–7F Plumbing Fixtures', true),
  ('MEP Second Fix', 'HVAC Equipment – Typical Floor', 'GF–7F HVAC Equipment', true),
  ('MEP Second Fix', 'Fire Alarm Devices – Typical Floor', 'GF–7F Fire Alarm Devices', true),
  ('MEP Second Fix', 'Sprinkler Heads – Typical Floor', 'GF–7F Sprinkler Heads', true),
  ('MEP Second Fix', 'Fire Fighting Equipment – Typical Floor', 'GF–7F Fire Fighting Equipment', true),
  ('MEP Second Fix', 'ELV Devices – Typical Floor', 'GF–7F ELV Devices', true),
  ('Structure & Early Works', 'Site Preparation', 'Early works – site establishment', true),
  ('Structure & Early Works', 'Anti-Termite Treatment', 'Before / during foundation', true),
  ('Structure & Early Works', 'Piling Works', 'Piling + testing + rectification', true),
  ('Structure & Early Works', 'Substructure Works', 'Pile cap, raft, ground beam, SOG', true),
  ('Structure & Early Works', 'Underground MEP / Embedded Services', 'Below ground MEP & services', true),
  ('Temporary Works', 'Tower Crane Installation', 'Temporary crane setup', true),
  ('Temporary Works', 'External Scaffolding', 'External access scaffolding', true),
  ('Temporary Works', 'Material Hoist / Loading Platform', 'Vertical material handling', true),
  ('Drywall & Special Partitions', 'Dry Wall Installation', 'Gypsum / drywall partitions', true),
  ('Drywall & Special Partitions', 'Toilet Cubicle / Partition', 'Toilet cubicles', true),
  ('Drywall & Special Partitions', 'Fabric Wall / Acoustic Panel', 'Acoustic fabric walls', true),
  ('MEP Final Fix / Plant', 'AHU Installation', 'Air Handling Units', true),
  ('MEP Final Fix / Plant', 'Busduct Works', 'Busduct installation', true),
  ('MEP Final Fix / Plant', 'Fire Hose Reel Installation', 'Fire hose reels', true),
  ('MEP Final Fix / Plant', 'Fire Hydrant Installation', 'External / internal hydrants', true),
  ('MEP Final Fix / Plant', 'Major Plant Equipment (Chiller / Cooling Tower / Genset)', 'Chiller, CT, Genset etc.', true),
  ('MEP Final Fix / Plant', 'Pumps & Tanks Installation', 'Transfer, booster, submersible, tanks', true),
  ('MEP Final Fix / Plant', 'LV-MSB / Switchgear Installation', 'Main switchboards', true),
  ('MEP Final Fix / Plant', 'Diffuser / Grille / Louver Installation', 'Air terminals & louvers', true),
  ('Architectural Finishes', 'Balustrade & Railings', 'Stair / balcony balustrades', true),
  ('Architectural Finishes', 'Timber Floor / Carpet Installation', 'Timber or carpet flooring', true),
  ('Architectural Finishes', 'Wall & Soffit Skim Coat', 'Skim coat before paint', true),
  ('External Works & Handover', 'Landscaping', 'Soft & hard landscape', true),
  ('External Works & Handover', 'External Drainage', 'Stormwater / external drainage', true),
  ('External Works & Handover', 'Permanent Fence / Boundary', 'Boundary wall / fence / gate', true),
  ('External Works & Handover', 'Client Inspection & Taking Over', 'Final inspection & handover', true),
  ('Structure & Early Works', 'Pile Cap', 'Pile cap construction', true),
  ('Structure & Early Works', 'Ground Beam', 'Ground beam', true),
  ('Structure & Early Works', 'Columns', 'Typical floor / basement columns', true),
  ('Structure & Early Works', 'Shear Wall / Core Wall', 'Shear walls & core walls', true),
  ('Structure & Early Works', 'Beams', 'Beam formwork + rebar + concrete', true),
  ('Structure & Early Works', 'Slab', 'Typical floor slab cycle', true),
  ('Structure & Early Works', 'Staircase', 'Structural staircase', true),
  ('Structure & Early Works', 'Ramp', 'Vehicle / access ramp', true),
  ('Structure & Early Works', 'Retaining Wall', 'Basement / site retaining wall', true),
  ('Structure & Early Works', 'Diaphragm Wall', 'Diaphragm wall panels', true),
  ('Structure & Early Works', 'CBP / Secant Pile Wall', 'Contiguous / secant bored pile wall', true),
  ('Structure & Early Works', 'Slab on Grade / Ground Slab', 'Ground floor slab on grade', true)

on conflict (group_name, template_name) do update set
  description = excluded.description,
  is_active = true,
  updated_at = now();

-- ────────────────────────────────────────────────────────────────────────
-- 2. Template steps (395 rows) — looked up by (group_name, template_name)
--    against the masters just upserted above, so this does not depend on
--    knowing generated UUIDs.
-- ────────────────────────────────────────────────────────────────────────
insert into public.activity_step_template_item
  (template_id, step_no, step_name, weight, discipline, resource_crew, est_duration_days, inspection_hold_point, notes)
select t.id, v.step_no, v.step_name, v.weight, v.discipline, v.resource_crew, v.est_duration_days, v.inspection_hold_point, v.notes
from (values
  ('Architectural Finishes', 'Blockwork / Masonry – Typical Floor', 1, 'Setting Out & Setting Out Marks', 10, 'Architectural', 'Architectural Crew', 1, false, 'Lines, openings, levels'),
  ('Architectural Finishes', 'Blockwork / Masonry – Typical Floor', 2, 'First Course & DPC', 15, 'Architectural', 'Architectural Crew', 1.5, false, 'Including DPC / waterproof course'),
  ('Architectural Finishes', 'Blockwork / Masonry – Typical Floor', 3, 'Block / Brick Laying', 50, 'Architectural', 'Masonry Crew', 1.5, false, 'Main wall construction'),
  ('Architectural Finishes', 'Blockwork / Masonry – Typical Floor', 4, 'Reinforcement & Ties', 10, 'Architectural', 'Architectural Crew', 2, false, 'Horizontal & vertical reinforcement'),
  ('Architectural Finishes', 'Blockwork / Masonry – Typical Floor', 5, 'Cleaning & Pointing', 10, 'Architectural', 'Architectural Crew', 1, false, 'Joint finishing'),
  ('Architectural Finishes', 'Blockwork / Masonry – Typical Floor', 6, 'Inspection & Handover', 5, 'Architectural', 'QA/QC', 0.5, true, 'QA check before plaster'),
  ('Architectural Finishes', 'Internal Partition – Typical Floor', 1, 'Setting Out', 10, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Internal Partition – Typical Floor', 2, 'Track & Stud Installation', 30, 'Architectural', 'Drywall Crew', 2, false, null),
  ('Architectural Finishes', 'Internal Partition – Typical Floor', 3, 'Insulation / Acoustic Fill', 15, 'Architectural', 'Architectural Crew', 1.5, false, 'If required'),
  ('Architectural Finishes', 'Internal Partition – Typical Floor', 4, 'Board Fixing (both sides)', 30, 'Architectural', 'Drywall Crew', 1.5, false, null),
  ('Architectural Finishes', 'Internal Partition – Typical Floor', 5, 'Jointing & Skimming', 10, 'Architectural', 'Plaster Crew', 1.5, false, null),
  ('Architectural Finishes', 'Internal Partition – Typical Floor', 6, 'Inspection', 5, 'Architectural', 'QA/QC', 0.5, true, null),
  ('Architectural Finishes', 'Plastering (Internal) – Typical Floor', 1, 'Surface Preparation & Dubbing', 15, 'Architectural', 'Architectural Crew', 1, false, 'Cleaning, hacking, bonding agent'),
  ('Architectural Finishes', 'Plastering (Internal) – Typical Floor', 2, 'Corner Beads & Stop Beads', 10, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Plastering (Internal) – Typical Floor', 3, 'Scratch / Base Coat', 30, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Plastering (Internal) – Typical Floor', 4, 'Finish Coat', 30, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Plastering (Internal) – Typical Floor', 5, 'Curing & Cleaning', 10, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Plastering (Internal) – Typical Floor', 6, 'Inspection', 5, 'Architectural', 'QA/QC', 0.5, true, null),
  ('Architectural Finishes', 'Waterproofing (Wet Areas) – Typical Floor', 1, 'Surface Preparation', 15, 'Architectural', 'Waterproofing Crew', 1, false, null),
  ('Architectural Finishes', 'Waterproofing (Wet Areas) – Typical Floor', 2, 'Primer Application', 15, 'Architectural', 'Waterproofing Crew', 1.5, false, null),
  ('Architectural Finishes', 'Waterproofing (Wet Areas) – Typical Floor', 3, 'First Coat Waterproofing', 25, 'Architectural', 'Waterproofing Crew', 1.5, false, null),
  ('Architectural Finishes', 'Waterproofing (Wet Areas) – Typical Floor', 4, 'Second Coat + Reinforcement', 25, 'Architectural', 'Waterproofing Crew', 2, false, 'Mesh / membrane at corners'),
  ('Architectural Finishes', 'Waterproofing (Wet Areas) – Typical Floor', 5, 'Protection Layer', 15, 'Architectural', 'Waterproofing Crew', 1.5, false, null),
  ('Architectural Finishes', 'Waterproofing (Wet Areas) – Typical Floor', 6, 'Flood Test / Inspection', 5, 'Architectural', 'Waterproofing Crew', 0.5, true, null),
  ('Architectural Finishes', 'Screed – Typical Floor', 1, 'Surface Preparation & Cleaning', 15, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Screed – Typical Floor', 2, 'Level Marks & Datum', 15, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Screed – Typical Floor', 3, 'Screed Laying', 40, 'Architectural', 'Screed Crew', 1.5, false, null),
  ('Architectural Finishes', 'Screed – Typical Floor', 4, 'Levelling & Finishing', 20, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Screed – Typical Floor', 5, 'Curing', 5, 'Architectural', 'Architectural Crew', 3, false, null),
  ('Architectural Finishes', 'Screed – Typical Floor', 6, 'Inspection', 5, 'Architectural', 'QA/QC', 0.5, true, null),
  ('Architectural Finishes', 'Ceiling – Typical Floor', 1, 'Ceiling Frame / Suspension', 25, 'Architectural', 'Ceiling Crew', 1.5, false, 'Main & cross runners, hangers'),
  ('Architectural Finishes', 'Ceiling – Typical Floor', 2, 'Ceiling Board / Panel Fixing', 35, 'Architectural', 'Ceiling Crew', 1.5, false, null),
  ('Architectural Finishes', 'Ceiling – Typical Floor', 3, 'Jointing & Skim Coat', 20, 'Architectural', 'Plaster Crew', 1.5, false, null),
  ('Architectural Finishes', 'Ceiling – Typical Floor', 4, 'Final Paint / Finish', 15, 'Architectural', 'Ceiling Crew', 1.5, false, null),
  ('Architectural Finishes', 'Ceiling – Typical Floor', 5, 'Inspection & Handover', 5, 'Architectural', 'Ceiling Crew', 0.5, true, null),
  ('Architectural Finishes', 'Flooring – Typical Floor', 1, 'Substrate Preparation', 15, 'Architectural', 'Architectural Crew', 1, false, 'Cleaning, priming'),
  ('Architectural Finishes', 'Flooring – Typical Floor', 2, 'Waterproofing (if wet area)', 10, 'Architectural', 'Waterproofing Crew', 1.5, false, 'Optional – set to 0 if not needed'),
  ('Architectural Finishes', 'Flooring – Typical Floor', 3, 'Setting Out & Layout', 10, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Flooring – Typical Floor', 4, 'Tile / Stone / Vinyl Laying', 40, 'Architectural', 'Tiling / Flooring Crew', 1.5, false, null),
  ('Architectural Finishes', 'Flooring – Typical Floor', 5, 'Grouting & Cleaning', 15, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Flooring – Typical Floor', 6, 'Final Inspection', 10, 'Architectural', 'QA/QC', 0.5, true, null),
  ('Architectural Finishes', 'Wall Tiling – Typical Floor', 1, 'Surface Preparation', 15, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Wall Tiling – Typical Floor', 2, 'Waterproofing (wet areas)', 15, 'Architectural', 'Waterproofing Crew', 1.5, false, null),
  ('Architectural Finishes', 'Wall Tiling – Typical Floor', 3, 'Setting Out & Guides', 10, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Wall Tiling – Typical Floor', 4, 'Tile Installation', 40, 'Architectural', 'Tiling / Flooring Crew', 2, false, null),
  ('Architectural Finishes', 'Wall Tiling – Typical Floor', 5, 'Grouting & Sealing', 15, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Wall Tiling – Typical Floor', 6, 'Cleaning & Inspection', 5, 'Architectural', 'QA/QC', 0.5, true, null),
  ('Architectural Finishes', 'Stone / Marble – Typical Floor', 1, 'Surface Preparation', 15, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Stone / Marble – Typical Floor', 2, 'Setting Out & Template', 15, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Stone / Marble – Typical Floor', 3, 'Stone Fixing / Laying', 40, 'Architectural', 'Tiling / Flooring Crew', 1.5, false, null),
  ('Architectural Finishes', 'Stone / Marble – Typical Floor', 4, 'Joint Filling / Grouting', 15, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Stone / Marble – Typical Floor', 5, 'Polishing & Protection', 10, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Stone / Marble – Typical Floor', 6, 'Inspection', 5, 'Architectural', 'QA/QC', 0.5, true, null),
  ('Architectural Finishes', 'Internal Painting – Typical Floor', 1, 'Surface Preparation & Sanding', 20, 'Architectural', 'Paint Crew', 1, false, null),
  ('Architectural Finishes', 'Internal Painting – Typical Floor', 2, 'Primer / Sealer', 20, 'Architectural', 'Paint Crew', 1.5, false, null),
  ('Architectural Finishes', 'Internal Painting – Typical Floor', 3, 'First Coat', 25, 'Architectural', 'Paint Crew', 1.5, false, null),
  ('Architectural Finishes', 'Internal Painting – Typical Floor', 4, 'Second / Final Coat', 25, 'Architectural', 'Paint Crew', 1.5, false, null),
  ('Architectural Finishes', 'Internal Painting – Typical Floor', 5, 'Touch-up & Cleaning', 5, 'Architectural', 'Paint Crew', 1, false, null),
  ('Architectural Finishes', 'Internal Painting – Typical Floor', 6, 'Inspection', 5, 'Architectural', 'Paint Crew', 0.5, true, null),
  ('Architectural Finishes', 'Door Frames – Typical Floor', 1, 'Setting Out & Opening Check', 20, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Door Frames – Typical Floor', 2, 'Frame Installation & Fixing', 50, 'Architectural', 'Joinery / Glazing Crew', 2, false, null),
  ('Architectural Finishes', 'Door Frames – Typical Floor', 3, 'Plumb, Level & Temporary Brace', 20, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Door Frames – Typical Floor', 4, 'Inspection', 10, 'Architectural', 'QA/QC', 0.5, true, null),
  ('Architectural Finishes', 'Doors (Leaf + Ironmongery) – Typical Floor', 1, 'Door Leaf Installation', 40, 'Architectural', 'Joinery / Glazing Crew', 2, false, null),
  ('Architectural Finishes', 'Doors (Leaf + Ironmongery) – Typical Floor', 2, 'Hinges & Alignment', 20, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Doors (Leaf + Ironmongery) – Typical Floor', 3, 'Lockset / Handle / Ironmongery', 25, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Doors (Leaf + Ironmongery) – Typical Floor', 4, 'Adjustment & Operation Test', 10, 'Architectural', 'Architectural Crew', 1.5, true, null),
  ('Architectural Finishes', 'Doors (Leaf + Ironmongery) – Typical Floor', 5, 'Inspection', 5, 'Architectural', 'QA/QC', 0.5, true, null),
  ('Architectural Finishes', 'Windows / Glazing – Typical Floor', 1, 'Frame Installation', 30, 'Architectural', 'Joinery / Glazing Crew', 2, false, null),
  ('Architectural Finishes', 'Windows / Glazing – Typical Floor', 2, 'Alignment & Fixing', 20, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Windows / Glazing – Typical Floor', 3, 'Glass / Panel Installation', 30, 'Architectural', 'Joinery / Glazing Crew', 2, false, null),
  ('Architectural Finishes', 'Windows / Glazing – Typical Floor', 4, 'Sealing & Weatherproofing', 15, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Windows / Glazing – Typical Floor', 5, 'Inspection & Operation Test', 5, 'Architectural', 'QA/QC', 0.5, true, null),
  ('MEP First Fix', 'Electrical Conduits – Typical Floor', 1, 'Setting Out & Marking', 15, 'Electrical / ELV', 'Electrical Crew', 1, false, 'Routes, boxes, levels'),
  ('MEP First Fix', 'Electrical Conduits – Typical Floor', 2, 'Conduit Installation (concealed)', 45, 'Electrical / ELV', 'Electrical Crew', 2, false, null),
  ('MEP First Fix', 'Electrical Conduits – Typical Floor', 3, 'Junction / Draw Boxes Installation', 15, 'Electrical / ELV', 'Electrical Crew', 2, false, null),
  ('MEP First Fix', 'Electrical Conduits – Typical Floor', 4, 'Pull Wire / Fish Wire', 10, 'Electrical / ELV', 'Electrical Crew', 1.5, false, null),
  ('MEP First Fix', 'Electrical Conduits – Typical Floor', 5, 'Continuity Check & Cleaning', 10, 'Electrical / ELV', 'Electrical Crew', 1, false, null),
  ('MEP First Fix', 'Electrical Conduits – Typical Floor', 6, 'Inspection', 5, 'Electrical / ELV', 'QA/QC + Electrical Engineer', 0.5, true, null),
  ('MEP First Fix', 'Cable Trays – Typical Floor', 1, 'Setting Out & Support Fixing', 20, 'Electrical / ELV', 'Electrical Crew', 1, false, 'Hangers, brackets'),
  ('MEP First Fix', 'Cable Trays – Typical Floor', 2, 'Tray / Ladder Installation', 40, 'Electrical / ELV', 'Electrical Crew', 2, false, null),
  ('MEP First Fix', 'Cable Trays – Typical Floor', 3, 'Jointing & Earthing', 15, 'Electrical / ELV', 'Electrical Crew', 1.5, false, null),
  ('MEP First Fix', 'Cable Trays – Typical Floor', 4, 'Cover / Lid Installation', 10, 'Electrical / ELV', 'Electrical Crew', 2, false, 'If applicable'),
  ('MEP First Fix', 'Cable Trays – Typical Floor', 5, 'Alignment & Level Check', 10, 'Electrical / ELV', 'Electrical Crew', 1.5, false, null),
  ('MEP First Fix', 'Cable Trays – Typical Floor', 6, 'Inspection', 5, 'Electrical / ELV', 'QA/QC + Electrical Engineer', 0.5, true, null),
  ('MEP First Fix', 'Plumbing Pipes – Typical Floor', 1, 'Setting Out & Marking', 15, 'Plumbing', 'Plumbing Crew', 1, false, null),
  ('MEP First Fix', 'Plumbing Pipes – Typical Floor', 2, 'Pipe Installation & Fixing', 40, 'Plumbing', 'Plumbing Crew', 2, false, null),
  ('MEP First Fix', 'Plumbing Pipes – Typical Floor', 3, 'Fittings & Joints', 20, 'Plumbing', 'Plumbing Crew', 1.5, false, null),
  ('MEP First Fix', 'Plumbing Pipes – Typical Floor', 4, 'Pressure Test', 15, 'Plumbing', 'QA/QC + Plumbing Engineer', 1, true, null),
  ('MEP First Fix', 'Plumbing Pipes – Typical Floor', 5, 'Insulation (if required)', 5, 'Plumbing', 'Plumbing Crew', 1.5, false, null),
  ('MEP First Fix', 'Plumbing Pipes – Typical Floor', 6, 'Inspection', 5, 'Plumbing', 'QA/QC + Plumbing Engineer', 0.5, true, null),
  ('MEP First Fix', 'Drainage Pipes – Typical Floor', 1, 'Setting Out & Gradient Check', 15, 'Plumbing', 'Plumbing Crew', 1, false, null),
  ('MEP First Fix', 'Drainage Pipes – Typical Floor', 2, 'Pipe Installation & Supports', 40, 'Plumbing', 'Plumbing Crew', 2, false, null),
  ('MEP First Fix', 'Drainage Pipes – Typical Floor', 3, 'Fittings & Joints', 20, 'Plumbing', 'Plumbing Crew', 1.5, false, null),
  ('MEP First Fix', 'Drainage Pipes – Typical Floor', 4, 'Slope / Gradient Verification', 10, 'Plumbing', 'Plumbing Crew', 1.5, false, null),
  ('MEP First Fix', 'Drainage Pipes – Typical Floor', 5, 'Leak / Water Test', 10, 'Plumbing', 'QA/QC + Plumbing Engineer', 1.5, true, null),
  ('MEP First Fix', 'Drainage Pipes – Typical Floor', 6, 'Inspection', 5, 'Plumbing', 'QA/QC + Plumbing Engineer', 0.5, true, null),
  ('MEP First Fix', 'HVAC Ductwork – Typical Floor', 1, 'Setting Out & Support Installation', 15, 'HVAC', 'HVAC Crew', 1, false, null),
  ('MEP First Fix', 'HVAC Ductwork – Typical Floor', 2, 'Duct Installation', 40, 'HVAC', 'HVAC Crew', 2, false, 'Straight ducts + fittings'),
  ('MEP First Fix', 'HVAC Ductwork – Typical Floor', 3, 'Joint Sealing & Gaskets', 15, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP First Fix', 'HVAC Ductwork – Typical Floor', 4, 'Flexible Connections', 10, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP First Fix', 'HVAC Ductwork – Typical Floor', 5, 'Insulation', 15, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP First Fix', 'HVAC Ductwork – Typical Floor', 6, 'Inspection & Cleaning', 5, 'HVAC', 'QA/QC + HVAC Engineer', 0.5, true, null),
  ('MEP First Fix', 'HVAC Pipes – Typical Floor', 1, 'Setting Out & Support Fixing', 15, 'HVAC', 'HVAC Crew', 1, false, null),
  ('MEP First Fix', 'HVAC Pipes – Typical Floor', 2, 'Pipe Installation', 35, 'HVAC', 'HVAC Crew', 2, false, null),
  ('MEP First Fix', 'HVAC Pipes – Typical Floor', 3, 'Fittings, Valves & Joints', 20, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP First Fix', 'HVAC Pipes – Typical Floor', 4, 'Pressure Test', 15, 'HVAC', 'QA/QC + HVAC Engineer', 1, true, null),
  ('MEP First Fix', 'HVAC Pipes – Typical Floor', 5, 'Insulation & Cladding', 10, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP First Fix', 'HVAC Pipes – Typical Floor', 6, 'Inspection', 5, 'HVAC', 'QA/QC + HVAC Engineer', 0.5, true, null),
  ('MEP First Fix', 'Fire Fighting Pipes – Typical Floor', 1, 'Setting Out & Support Installation', 15, 'Fire Fighting', 'Fire Fighting Crew', 1, false, null),
  ('MEP First Fix', 'Fire Fighting Pipes – Typical Floor', 2, 'Pipe Installation', 40, 'Fire Fighting', 'Fire Fighting Crew', 2, false, null),
  ('MEP First Fix', 'Fire Fighting Pipes – Typical Floor', 3, 'Fittings, Valves & Joints', 20, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP First Fix', 'Fire Fighting Pipes – Typical Floor', 4, 'Pressure / Hydrostatic Test', 15, 'Fire Fighting', 'QA/QC + FF Engineer', 1.5, true, null),
  ('MEP First Fix', 'Fire Fighting Pipes – Typical Floor', 5, 'Painting / Identification', 5, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP First Fix', 'Fire Fighting Pipes – Typical Floor', 6, 'Inspection', 5, 'Fire Fighting', 'QA/QC + FF Engineer', 0.5, true, null),
  ('MEP First Fix', 'Fire Alarm Conduits – Typical Floor', 1, 'Setting Out & Marking', 15, 'Electrical / ELV', 'Electrical Crew', 1, false, null),
  ('MEP First Fix', 'Fire Alarm Conduits – Typical Floor', 2, 'Conduit Installation', 45, 'Electrical / ELV', 'Electrical Crew', 2, false, null),
  ('MEP First Fix', 'Fire Alarm Conduits – Typical Floor', 3, 'Junction Boxes & Accessories', 15, 'Electrical / ELV', 'Electrical Crew', 1.5, false, null),
  ('MEP First Fix', 'Fire Alarm Conduits – Typical Floor', 4, 'Pull Wire Installation', 10, 'Electrical / ELV', 'Electrical Crew', 2, false, null),
  ('MEP First Fix', 'Fire Alarm Conduits – Typical Floor', 5, 'Continuity Check', 10, 'Electrical / ELV', 'Electrical Crew', 1.5, false, null),
  ('MEP First Fix', 'Fire Alarm Conduits – Typical Floor', 6, 'Inspection', 5, 'Electrical / ELV', 'QA/QC + Electrical Engineer', 0.5, true, null),
  ('MEP First Fix', 'ELV Conduits – Typical Floor', 1, 'Setting Out & Marking', 15, 'Electrical / ELV', 'Electrical Crew', 1, false, null),
  ('MEP First Fix', 'ELV Conduits – Typical Floor', 2, 'Conduit / Trunking Installation', 45, 'Electrical / ELV', 'Electrical Crew', 2, false, null),
  ('MEP First Fix', 'ELV Conduits – Typical Floor', 3, 'Boxes & Accessories', 15, 'Electrical / ELV', 'Electrical Crew', 1.5, false, null),
  ('MEP First Fix', 'ELV Conduits – Typical Floor', 4, 'Pull Wire / Draw Rope', 10, 'Electrical / ELV', 'Electrical Crew', 1.5, false, null),
  ('MEP First Fix', 'ELV Conduits – Typical Floor', 5, 'Continuity & Cleaning', 10, 'Electrical / ELV', 'Electrical Crew', 1, false, null),
  ('MEP First Fix', 'ELV Conduits – Typical Floor', 6, 'Inspection', 5, 'Electrical / ELV', 'QA/QC + Electrical Engineer', 0.5, true, null),
  ('MEP Second Fix', 'Cable Pulling – Typical Floor', 1, 'Cable Preparation & Labeling', 15, 'Electrical', 'Electrical Crew', 1, false, 'Cutting, tagging, checking'),
  ('MEP Second Fix', 'Cable Pulling – Typical Floor', 2, 'Cable Pulling', 50, 'Electrical', 'Electrical Crew', 1.5, false, 'Main pulling work'),
  ('MEP Second Fix', 'Cable Pulling – Typical Floor', 3, 'Termination at both ends', 20, 'Electrical', 'Electrical Crew', 1.5, false, 'Glanding, lug, connection'),
  ('MEP Second Fix', 'Cable Pulling – Typical Floor', 4, 'Continuity & Insulation Test', 10, 'Electrical', 'QA/QC + Electrical Engineer', 1.5, true, 'Megger / continuity'),
  ('MEP Second Fix', 'Cable Pulling – Typical Floor', 5, 'Inspection & Documentation', 5, 'Electrical', 'QA/QC + Electrical Engineer', 0.5, true, null),
  ('MEP Second Fix', 'DB Installation – Typical Floor', 1, 'DB Positioning & Fixing', 25, 'Electrical', 'Electrical Crew', 1.5, false, 'Wall / floor mounting'),
  ('MEP Second Fix', 'DB Installation – Typical Floor', 2, 'Incoming Cable Termination', 20, 'Electrical', 'Electrical Crew', 1.5, false, null),
  ('MEP Second Fix', 'DB Installation – Typical Floor', 3, 'Outgoing Circuit Termination', 30, 'Electrical', 'Electrical Crew', 1.5, false, null),
  ('MEP Second Fix', 'DB Installation – Typical Floor', 4, 'Internal Wiring & Labelling', 15, 'Electrical', 'Electrical Crew', 1, false, null),
  ('MEP Second Fix', 'DB Installation – Typical Floor', 5, 'Testing & Inspection', 10, 'Electrical', 'QA/QC + Electrical Engineer', 0.5, true, null),
  ('MEP Second Fix', 'Lighting Installation – Typical Floor', 1, 'Fixture Positioning & Fixing', 30, 'Electrical', 'Electrical Crew', 1.5, false, null),
  ('MEP Second Fix', 'Lighting Installation – Typical Floor', 2, 'Wiring & Connection', 30, 'Electrical', 'Electrical Crew', 1.5, false, null),
  ('MEP Second Fix', 'Lighting Installation – Typical Floor', 3, 'Lamp / Driver Installation', 20, 'Electrical', 'Electrical Crew', 2, false, null),
  ('MEP Second Fix', 'Lighting Installation – Typical Floor', 4, 'Testing & Alignment', 15, 'Electrical', 'QA/QC + Electrical Engineer', 1, true, null),
  ('MEP Second Fix', 'Lighting Installation – Typical Floor', 5, 'Final Cleaning & Inspection', 5, 'Electrical', 'QA/QC + Electrical Engineer', 0.5, true, null),
  ('MEP Second Fix', 'Switches & Sockets – Typical Floor', 1, 'Back Box Preparation', 15, 'Electrical', 'Electrical Crew', 1, false, null),
  ('MEP Second Fix', 'Switches & Sockets – Typical Floor', 2, 'Wiring & Connection', 40, 'Electrical', 'Electrical Crew', 1.5, false, null),
  ('MEP Second Fix', 'Switches & Sockets – Typical Floor', 3, 'Device Fixing & Faceplate', 30, 'Electrical', 'Electrical Crew', 1.5, false, null),
  ('MEP Second Fix', 'Switches & Sockets – Typical Floor', 4, 'Function Test', 10, 'Electrical', 'QA/QC + Electrical Engineer', 1, true, null),
  ('MEP Second Fix', 'Switches & Sockets – Typical Floor', 5, 'Inspection', 5, 'Electrical', 'QA/QC + Electrical Engineer', 0.5, true, null),
  ('MEP Second Fix', 'Plumbing Fixtures – Typical Floor', 1, 'Fixture Positioning & Setting Out', 15, 'Plumbing', 'Plumbing Crew', 1, false, null),
  ('MEP Second Fix', 'Plumbing Fixtures – Typical Floor', 2, 'Connection to Supply & Waste', 40, 'Plumbing', 'Plumbing Crew', 1.5, false, null),
  ('MEP Second Fix', 'Plumbing Fixtures – Typical Floor', 3, 'Fixing & Sealing', 25, 'Plumbing', 'Plumbing Crew', 1.5, false, null),
  ('MEP Second Fix', 'Plumbing Fixtures – Typical Floor', 4, 'Testing (flow & leakage)', 15, 'Plumbing', 'QA/QC + Plumbing Engineer', 1, true, null),
  ('MEP Second Fix', 'Plumbing Fixtures – Typical Floor', 5, 'Cleaning & Inspection', 5, 'Plumbing', 'QA/QC + Plumbing Engineer', 0.5, true, null),
  ('MEP Second Fix', 'HVAC Equipment – Typical Floor', 1, 'Equipment Positioning & Fixing', 25, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP Second Fix', 'HVAC Equipment – Typical Floor', 2, 'Duct / Pipe Connection', 30, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP Second Fix', 'HVAC Equipment – Typical Floor', 3, 'Electrical & Control Connection', 20, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP Second Fix', 'HVAC Equipment – Typical Floor', 4, 'Insulation & Cladding', 15, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP Second Fix', 'HVAC Equipment – Typical Floor', 5, 'Testing & Commissioning Check', 10, 'HVAC', 'QA/QC + HVAC Engineer', 1, true, null),
  ('MEP Second Fix', 'Fire Alarm Devices – Typical Floor', 1, 'Device Positioning & Fixing', 25, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, 'Detectors, MCPs, sounders'),
  ('MEP Second Fix', 'Fire Alarm Devices – Typical Floor', 2, 'Wiring & Termination', 35, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Second Fix', 'Fire Alarm Devices – Typical Floor', 3, 'Addressing / Programming', 20, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Second Fix', 'Fire Alarm Devices – Typical Floor', 4, 'Function Test', 15, 'Fire Fighting', 'QA/QC + FF Engineer', 1, true, null),
  ('MEP Second Fix', 'Fire Alarm Devices – Typical Floor', 5, 'Inspection & Documentation', 5, 'Fire Fighting', 'QA/QC + FF Engineer', 0.5, true, null),
  ('MEP Second Fix', 'Sprinkler Heads – Typical Floor', 1, 'Head Positioning & Alignment', 20, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Second Fix', 'Sprinkler Heads – Typical Floor', 2, 'Installation & Tightening', 40, 'Fire Fighting', 'Fire Fighting Crew', 2, false, null),
  ('MEP Second Fix', 'Sprinkler Heads – Typical Floor', 3, 'Escutcheon / Cover Plate', 15, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Second Fix', 'Sprinkler Heads – Typical Floor', 4, 'Pressure / Leak Test', 20, 'Fire Fighting', 'QA/QC + FF Engineer', 1.5, true, null),
  ('MEP Second Fix', 'Sprinkler Heads – Typical Floor', 5, 'Inspection', 5, 'Fire Fighting', 'QA/QC + FF Engineer', 0.5, true, null),
  ('MEP Second Fix', 'Fire Fighting Equipment – Typical Floor', 1, 'Equipment Positioning & Fixing', 30, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Second Fix', 'Fire Fighting Equipment – Typical Floor', 2, 'Pipe / Hose Connection', 30, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Second Fix', 'Fire Fighting Equipment – Typical Floor', 3, 'Valve / Accessory Installation', 20, 'Fire Fighting', 'Fire Fighting Crew', 2, false, null),
  ('MEP Second Fix', 'Fire Fighting Equipment – Typical Floor', 4, 'Pressure Test & Function Check', 15, 'Fire Fighting', 'QA/QC + FF Engineer', 1, true, null),
  ('MEP Second Fix', 'Fire Fighting Equipment – Typical Floor', 5, 'Inspection & Signage', 5, 'Fire Fighting', 'QA/QC + FF Engineer', 0.5, true, null),
  ('MEP Second Fix', 'ELV Devices – Typical Floor', 1, 'Device Positioning & Fixing', 25, 'ELV', 'Electrical Crew', 1.5, false, null),
  ('MEP Second Fix', 'ELV Devices – Typical Floor', 2, 'Cable Termination', 30, 'ELV', 'Electrical Crew', 1.5, false, null),
  ('MEP Second Fix', 'ELV Devices – Typical Floor', 3, 'Power & Network Connection', 20, 'ELV', 'Electrical Crew', 1.5, false, null),
  ('MEP Second Fix', 'ELV Devices – Typical Floor', 4, 'Configuration / Programming', 15, 'ELV', 'Electrical Crew', 1.5, false, null),
  ('MEP Second Fix', 'ELV Devices – Typical Floor', 5, 'Testing & Inspection', 10, 'ELV', 'QA/QC + Electrical Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Site Preparation', 1, 'Site Clearance & Demolition', 20, 'Structural', 'Structural Crew', 1.5, false, 'Clear vegetation, debris, existing structures'),
  ('Structure & Early Works', 'Site Preparation', 2, 'Temporary Fencing & Access', 15, 'Structural', 'Structural Crew', 1.5, false, null),
  ('Structure & Early Works', 'Site Preparation', 3, 'Temporary Facilities Setup', 20, 'Structural', 'Structural Crew', 1.5, false, 'Site office, stores, welfare'),
  ('Structure & Early Works', 'Site Preparation', 4, 'Temporary Roads & Drainage', 20, 'Structural', 'Structural Crew', 1.5, false, null),
  ('Structure & Early Works', 'Site Preparation', 5, 'Site Grading & Levelling', 15, 'Structural', 'Structural Crew', 1.5, false, null),
  ('Structure & Early Works', 'Site Preparation', 6, 'Inspection & Handover to Survey', 10, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Anti-Termite Treatment', 1, 'Surface Preparation & Cleaning', 15, 'Structural', 'Structural Crew', 1, false, null),
  ('Structure & Early Works', 'Anti-Termite Treatment', 2, 'Trench / Hole Preparation', 15, 'Structural', 'Structural Crew', 1, false, null),
  ('Structure & Early Works', 'Anti-Termite Treatment', 3, 'Chemical Application (Horizontal)', 25, 'Structural', 'Structural Crew', 1.5, false, 'Under slab / foundation'),
  ('Structure & Early Works', 'Anti-Termite Treatment', 4, 'Chemical Application (Vertical)', 25, 'Structural', 'Structural Crew', 1.5, false, 'Perimeter / walls'),
  ('Structure & Early Works', 'Anti-Termite Treatment', 5, 'Protection & Backfill', 10, 'Structural', 'Structural Crew', 1.5, false, null),
  ('Structure & Early Works', 'Anti-Termite Treatment', 6, 'Certificate & Inspection', 10, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Piling Works', 1, 'Setting Out & Pile Points', 10, 'Structural', 'Civil / Survey Crew', 1, false, null),
  ('Structure & Early Works', 'Piling Works', 2, 'Pile Installation / Driving', 40, 'Structural', 'Structural Crew', 2, false, null),
  ('Structure & Early Works', 'Piling Works', 3, 'Pile Head Breaking / Cut-off', 15, 'Structural', 'Structural Crew', 1.5, false, null),
  ('Structure & Early Works', 'Piling Works', 4, 'Pile Testing (Working Load / Integrity)', 20, 'Structural', 'Structural Crew', 1, true, null),
  ('Structure & Early Works', 'Piling Works', 5, 'Pile Rectification (if any)', 10, 'Structural', 'Structural Crew', 1.5, false, null),
  ('Structure & Early Works', 'Piling Works', 6, 'As-built & Inspection', 5, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Substructure Works', 1, 'Excavation to Formation', 15, 'Structural', 'Civil / Survey Crew', 1.5, false, null),
  ('Structure & Early Works', 'Substructure Works', 2, 'Blinding / Lean Concrete', 10, 'Structural', 'Concrete Crew', 1.5, false, null),
  ('Structure & Early Works', 'Substructure Works', 3, 'Pile Cap / Raft Reinforcement', 20, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Substructure Works', 4, 'Pile Cap / Raft Formwork & Concrete', 25, 'Structural', 'Formwork Crew', 1.5, false, null),
  ('Structure & Early Works', 'Substructure Works', 5, 'Ground Beam / Slab on Grade', 20, 'Structural', 'Structural Crew', 1.5, false, null),
  ('Structure & Early Works', 'Substructure Works', 6, 'Inspection & Backfill Preparation', 10, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Underground MEP / Embedded Services', 1, 'Setting Out & Coordination', 15, 'Structural', 'Civil / Survey Crew', 1, false, null),
  ('Structure & Early Works', 'Underground MEP / Embedded Services', 2, 'Trenching / Sleeve Installation', 25, 'Structural', 'Structural Crew', 2, false, null),
  ('Structure & Early Works', 'Underground MEP / Embedded Services', 3, 'Pipe / Conduit / Duct Installation', 30, 'Structural', 'Structural Crew', 2, false, null),
  ('Structure & Early Works', 'Underground MEP / Embedded Services', 4, 'Testing & Protection', 15, 'Structural', 'Structural Crew', 1, true, null),
  ('Structure & Early Works', 'Underground MEP / Embedded Services', 5, 'Backfill & Compaction', 10, 'Structural', 'Structural Crew', 1.5, false, null),
  ('Structure & Early Works', 'Underground MEP / Embedded Services', 6, 'As-built & Inspection', 5, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Temporary Works', 'Tower Crane Installation', 1, 'Foundation / Base Preparation', 20, 'Temporary Works', 'Temporary Works / Crane Crew', 1, false, null),
  ('Temporary Works', 'Tower Crane Installation', 2, 'Crane Erection & Assembly', 35, 'Temporary Works', 'Temporary Works / Crane Crew', 1.5, false, null),
  ('Temporary Works', 'Tower Crane Installation', 3, 'Electrical Connection & Testing', 20, 'Temporary Works', 'Temporary Works / Crane Crew', 1, true, null),
  ('Temporary Works', 'Tower Crane Installation', 4, 'Load Testing & Certification', 15, 'Temporary Works', 'Temporary Works / Crane Crew', 1, true, null),
  ('Temporary Works', 'Tower Crane Installation', 5, 'Inspection & Handover', 10, 'Temporary Works', 'Temporary Works / Crane Crew', 0.5, true, null),
  ('Temporary Works', 'External Scaffolding', 1, 'Foundation / Base Plates', 15, 'Temporary Works', 'Temporary Works / Crane Crew', 1.5, false, null),
  ('Temporary Works', 'External Scaffolding', 2, 'Scaffold Erection (Main Structure)', 40, 'Temporary Works', 'Temporary Works / Crane Crew', 1.5, false, null),
  ('Temporary Works', 'External Scaffolding', 3, 'Platforms, Guardrails & Access', 20, 'Temporary Works', 'Temporary Works / Crane Crew', 1.5, false, null),
  ('Temporary Works', 'External Scaffolding', 4, 'Ties, Bracing & Safety Netting', 15, 'Temporary Works', 'Temporary Works / Crane Crew', 1.5, false, null),
  ('Temporary Works', 'External Scaffolding', 5, 'Inspection & Tagging', 10, 'Temporary Works', 'Temporary Works / Crane Crew', 0.5, true, null),
  ('Temporary Works', 'Material Hoist / Loading Platform', 1, 'Support Structure / Frame Installation', 25, 'Temporary Works', 'Temporary Works / Crane Crew', 2, false, null),
  ('Temporary Works', 'Material Hoist / Loading Platform', 2, 'Hoist / Platform Assembly', 30, 'Temporary Works', 'Temporary Works / Crane Crew', 1.5, false, null),
  ('Temporary Works', 'Material Hoist / Loading Platform', 3, 'Electrical & Safety Devices', 20, 'Temporary Works', 'Temporary Works / Crane Crew', 1.5, false, null),
  ('Temporary Works', 'Material Hoist / Loading Platform', 4, 'Load Test & Certification', 15, 'Temporary Works', 'Temporary Works / Crane Crew', 1, true, null),
  ('Temporary Works', 'Material Hoist / Loading Platform', 5, 'Inspection & Handover', 10, 'Temporary Works', 'Temporary Works / Crane Crew', 0.5, true, null),
  ('Drywall & Special Partitions', 'Dry Wall Installation', 1, 'Setting Out & Marking', 10, 'Architectural', 'Drywall Crew', 1, false, null),
  ('Drywall & Special Partitions', 'Dry Wall Installation', 2, 'Track & Stud Framing', 25, 'Architectural', 'Drywall Crew', 1.5, false, null),
  ('Drywall & Special Partitions', 'Dry Wall Installation', 3, 'Insulation / Acoustic Fill', 15, 'Architectural', 'Drywall Crew', 1.5, false, null),
  ('Drywall & Special Partitions', 'Dry Wall Installation', 4, 'Board Fixing (both sides)', 25, 'Architectural', 'Drywall Crew', 1.5, false, null),
  ('Drywall & Special Partitions', 'Dry Wall Installation', 5, 'Jointing, Taping & Skimming', 15, 'Architectural', 'Plaster Crew', 1.5, false, null),
  ('Drywall & Special Partitions', 'Dry Wall Installation', 6, 'Inspection & Handover', 10, 'Architectural', 'Drywall Crew', 0.5, true, null),
  ('Drywall & Special Partitions', 'Toilet Cubicle / Partition', 1, 'Setting Out & Floor Fixings', 15, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Drywall & Special Partitions', 'Toilet Cubicle / Partition', 2, 'Panel & Door Installation', 40, 'Architectural', 'Joinery / Glazing Crew', 2, false, null),
  ('Drywall & Special Partitions', 'Toilet Cubicle / Partition', 3, 'Headrail, Fittings & Hardware', 25, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Drywall & Special Partitions', 'Toilet Cubicle / Partition', 4, 'Adjustment & Operation Test', 10, 'Architectural', 'Architectural Crew', 1.5, true, null),
  ('Drywall & Special Partitions', 'Toilet Cubicle / Partition', 5, 'Inspection & Cleaning', 10, 'Architectural', 'QA/QC', 0.5, true, null),
  ('Drywall & Special Partitions', 'Fabric Wall / Acoustic Panel', 1, 'Substrate Preparation', 15, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Drywall & Special Partitions', 'Fabric Wall / Acoustic Panel', 2, 'Frame / Batten Installation', 25, 'Architectural', 'Joinery / Glazing Crew', 2, false, null),
  ('Drywall & Special Partitions', 'Fabric Wall / Acoustic Panel', 3, 'Acoustic Fill / Backing', 20, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Drywall & Special Partitions', 'Fabric Wall / Acoustic Panel', 4, 'Fabric / Panel Fixing', 30, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Drywall & Special Partitions', 'Fabric Wall / Acoustic Panel', 5, 'Inspection & Cleaning', 10, 'Architectural', 'QA/QC', 0.5, true, null),
  ('MEP Final Fix / Plant', 'AHU Installation', 1, 'Positioning & Base Frame', 20, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'AHU Installation', 2, 'Duct & Pipe Connections', 25, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'AHU Installation', 3, 'Electrical & Control Wiring', 20, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'AHU Installation', 4, 'Insulation & Cladding', 15, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'AHU Installation', 5, 'Testing & Commissioning Checks', 15, 'HVAC', 'QA/QC + HVAC Engineer', 1, true, null),
  ('MEP Final Fix / Plant', 'AHU Installation', 6, 'Inspection & Handover', 5, 'HVAC', 'QA/QC + HVAC Engineer', 0.5, true, null),
  ('MEP Final Fix / Plant', 'Busduct Works', 1, 'Support & Hanger Installation', 15, 'Electrical', 'Electrical Crew', 2, false, null),
  ('MEP Final Fix / Plant', 'Busduct Works', 2, 'Busduct Section Installation', 35, 'Electrical', 'Electrical Crew', 2, false, null),
  ('MEP Final Fix / Plant', 'Busduct Works', 3, 'Jointing & Torqueing', 20, 'Electrical', 'Electrical Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Busduct Works', 4, 'Earthing & Bonding', 10, 'Electrical', 'Electrical Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Busduct Works', 5, 'Insulation Resistance Test', 15, 'Electrical', 'QA/QC + Electrical Engineer', 1.5, true, null),
  ('MEP Final Fix / Plant', 'Busduct Works', 6, 'Inspection & Documentation', 5, 'Electrical', 'QA/QC + Electrical Engineer', 0.5, true, null),
  ('MEP Final Fix / Plant', 'Fire Hose Reel Installation', 1, 'Cabinet / Frame Positioning', 20, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Fire Hose Reel Installation', 2, 'Hose Reel & Pipe Connection', 35, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Fire Hose Reel Installation', 3, 'Valve, Nozzle & Accessories', 20, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Fire Hose Reel Installation', 4, 'Pressure Test & Function Check', 15, 'Fire Fighting', 'QA/QC + FF Engineer', 1, true, null),
  ('MEP Final Fix / Plant', 'Fire Hose Reel Installation', 5, 'Signage & Inspection', 10, 'Fire Fighting', 'QA/QC + FF Engineer', 0.5, true, null),
  ('MEP Final Fix / Plant', 'Fire Hydrant Installation', 1, 'Hydrant Body Positioning', 20, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Fire Hydrant Installation', 2, 'Pipe Connection & Valves', 30, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Fire Hydrant Installation', 3, 'Backfill & Protection', 15, 'Fire Fighting', 'Fire Fighting Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Fire Hydrant Installation', 4, 'Pressure Test & Flushing', 20, 'Fire Fighting', 'QA/QC + FF Engineer', 1, true, null),
  ('MEP Final Fix / Plant', 'Fire Hydrant Installation', 5, 'Painting, Signage & Inspection', 15, 'Fire Fighting', 'QA/QC + FF Engineer', 0.5, true, null),
  ('MEP Final Fix / Plant', 'Major Plant Equipment (Chiller / Cooling Tower / Genset)', 1, 'Foundation / Base Preparation', 15, 'MEP Plant', 'MEP Plant Crew + Specialist', 1, false, null),
  ('MEP Final Fix / Plant', 'Major Plant Equipment (Chiller / Cooling Tower / Genset)', 2, 'Equipment Positioning & Alignment', 25, 'MEP Plant', 'MEP Plant Crew + Specialist', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Major Plant Equipment (Chiller / Cooling Tower / Genset)', 3, 'Pipe / Duct / Exhaust Connections', 20, 'MEP Plant', 'MEP Plant Crew + Specialist', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Major Plant Equipment (Chiller / Cooling Tower / Genset)', 4, 'Electrical & Control Connections', 20, 'MEP Plant', 'MEP Plant Crew + Specialist', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Major Plant Equipment (Chiller / Cooling Tower / Genset)', 5, 'Testing, Start-up & Commissioning', 15, 'MEP Plant', 'MEP Plant Crew + Specialist', 1, true, null),
  ('MEP Final Fix / Plant', 'Major Plant Equipment (Chiller / Cooling Tower / Genset)', 6, 'Inspection & Handover', 5, 'MEP Plant', 'MEP Plant Crew + Specialist', 0.5, true, null),
  ('MEP Final Fix / Plant', 'Pumps & Tanks Installation', 1, 'Base / Foundation Preparation', 15, 'MEP Plant', 'MEP Plant Crew + Specialist', 1, false, null),
  ('MEP Final Fix / Plant', 'Pumps & Tanks Installation', 2, 'Equipment Positioning & Fixing', 25, 'MEP Plant', 'MEP Plant Crew + Specialist', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Pumps & Tanks Installation', 3, 'Pipework & Valve Connections', 25, 'MEP Plant', 'MEP Plant Crew + Specialist', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Pumps & Tanks Installation', 4, 'Electrical & Control Wiring', 15, 'MEP Plant', 'MEP Plant Crew + Specialist', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Pumps & Tanks Installation', 5, 'Testing & Commissioning', 15, 'MEP Plant', 'MEP Plant Crew + Specialist', 1, true, null),
  ('MEP Final Fix / Plant', 'Pumps & Tanks Installation', 6, 'Inspection & Handover', 5, 'MEP Plant', 'MEP Plant Crew + Specialist', 0.5, true, null),
  ('MEP Final Fix / Plant', 'LV-MSB / Switchgear Installation', 1, 'Positioning & Fixing', 20, 'Electrical', 'Electrical Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'LV-MSB / Switchgear Installation', 2, 'Busbar / Cable Termination', 30, 'Electrical', 'Electrical Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'LV-MSB / Switchgear Installation', 3, 'Internal Wiring & Labelling', 20, 'Electrical', 'Electrical Crew', 1, false, null),
  ('MEP Final Fix / Plant', 'LV-MSB / Switchgear Installation', 4, 'Testing (IR, Continuity, Function)', 20, 'Electrical', 'QA/QC + Electrical Engineer', 1, true, null),
  ('MEP Final Fix / Plant', 'LV-MSB / Switchgear Installation', 5, 'Inspection & Energisation Ready', 10, 'Electrical', 'QA/QC + Electrical Engineer', 0.5, true, null),
  ('MEP Final Fix / Plant', 'Diffuser / Grille / Louver Installation', 1, 'Opening Preparation & Frame', 20, 'HVAC', 'HVAC Crew', 1, false, null),
  ('MEP Final Fix / Plant', 'Diffuser / Grille / Louver Installation', 2, 'Device Fixing & Alignment', 40, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Diffuser / Grille / Louver Installation', 3, 'Connection to Duct / Flexible', 20, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Diffuser / Grille / Louver Installation', 4, 'Adjustment & Balancing Check', 10, 'HVAC', 'HVAC Crew', 1.5, false, null),
  ('MEP Final Fix / Plant', 'Diffuser / Grille / Louver Installation', 5, 'Inspection & Cleaning', 10, 'HVAC', 'QA/QC + HVAC Engineer', 0.5, true, null),
  ('Architectural Finishes', 'Balustrade & Railings', 1, 'Setting Out & Fixing Points', 15, 'Architectural', 'Metalworks Crew', 1, false, null),
  ('Architectural Finishes', 'Balustrade & Railings', 2, 'Post / Frame Installation', 30, 'Architectural', 'Joinery / Glazing Crew', 2, false, null),
  ('Architectural Finishes', 'Balustrade & Railings', 3, 'Handrail / Infill Installation', 30, 'Architectural', 'Metalworks Crew', 2, false, null),
  ('Architectural Finishes', 'Balustrade & Railings', 4, 'Alignment, Welding / Fixing', 15, 'Architectural', 'Metalworks Crew', 1.5, false, null),
  ('Architectural Finishes', 'Balustrade & Railings', 5, 'Finishing, Cleaning & Inspection', 10, 'Architectural', 'Metalworks Crew', 0.5, true, null),
  ('Architectural Finishes', 'Timber Floor / Carpet Installation', 1, 'Substrate Preparation & Levelling', 20, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Timber Floor / Carpet Installation', 2, 'Underlay / Moisture Barrier', 15, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Timber Floor / Carpet Installation', 3, 'Flooring Installation', 40, 'Architectural', 'Tiling / Flooring Crew', 2, false, null),
  ('Architectural Finishes', 'Timber Floor / Carpet Installation', 4, 'Finishing / Skirting / Edges', 15, 'Architectural', 'Architectural Crew', 1.5, false, null),
  ('Architectural Finishes', 'Timber Floor / Carpet Installation', 5, 'Cleaning & Inspection', 10, 'Architectural', 'QA/QC', 0.5, true, null),
  ('Architectural Finishes', 'Wall & Soffit Skim Coat', 1, 'Surface Preparation', 20, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Wall & Soffit Skim Coat', 2, 'First Skim Coat Application', 30, 'Architectural', 'Plaster Crew', 1.5, false, null),
  ('Architectural Finishes', 'Wall & Soffit Skim Coat', 3, 'Second Skim Coat & Sanding', 30, 'Architectural', 'Plaster Crew', 1.5, false, null),
  ('Architectural Finishes', 'Wall & Soffit Skim Coat', 4, 'Final Touch-up & Cleaning', 10, 'Architectural', 'Architectural Crew', 1, false, null),
  ('Architectural Finishes', 'Wall & Soffit Skim Coat', 5, 'Inspection', 10, 'Architectural', 'QA/QC', 0.5, true, null),
  ('External Works & Handover', 'Landscaping', 1, 'Soil Preparation & Grading', 15, 'External / Handover', 'Landscape Crew', 1, false, null),
  ('External Works & Handover', 'Landscaping', 2, 'Softscape (Trees, Shrubs, Grass)', 35, 'External / Handover', 'Landscape Crew', 1.5, false, null),
  ('External Works & Handover', 'Landscaping', 3, 'Hardscape (Paving, Edging)', 25, 'External / Handover', 'Landscape Crew', 1.5, false, null),
  ('External Works & Handover', 'Landscaping', 4, 'Irrigation System', 15, 'External / Handover', 'Landscape Crew', 1.5, false, null),
  ('External Works & Handover', 'Landscaping', 5, 'Final Cleaning & Inspection', 10, 'External / Handover', 'Landscape Crew', 0.5, true, null),
  ('External Works & Handover', 'External Drainage', 1, 'Setting Out & Excavation', 15, 'External / Handover', 'External Works Crew', 1, false, null),
  ('External Works & Handover', 'External Drainage', 2, 'Pipe / Channel Installation', 30, 'External / Handover', 'External Works Crew', 2, false, null),
  ('External Works & Handover', 'External Drainage', 3, 'Manholes / Catch Pits', 20, 'External / Handover', 'External Works Crew', 1.5, false, null),
  ('External Works & Handover', 'External Drainage', 4, 'Backfill, Testing & Connection', 20, 'External / Handover', 'External Works Crew', 1, true, null),
  ('External Works & Handover', 'External Drainage', 5, 'Cover, Surfacing & Inspection', 15, 'External / Handover', 'QA/QC + PM Team', 0.5, true, null),
  ('External Works & Handover', 'Permanent Fence / Boundary', 1, 'Setting Out & Foundation', 20, 'External / Handover', 'External Works Crew', 1, false, null),
  ('External Works & Handover', 'Permanent Fence / Boundary', 2, 'Post / Panel Installation', 35, 'External / Handover', 'External Works Crew', 2, false, null),
  ('External Works & Handover', 'Permanent Fence / Boundary', 3, 'Gate Installation', 20, 'External / Handover', 'External Works Crew', 2, false, null),
  ('External Works & Handover', 'Permanent Fence / Boundary', 4, 'Finishing & Hardware', 15, 'External / Handover', 'External Works Crew', 1.5, false, null),
  ('External Works & Handover', 'Permanent Fence / Boundary', 5, 'Inspection & Handover', 10, 'External / Handover', 'QA/QC + PM Team', 0.5, true, null),
  ('External Works & Handover', 'Client Inspection & Taking Over', 1, 'Internal Snagging & Rectification', 25, 'External / Handover', 'QA/QC + PM Team', 1.5, false, null),
  ('External Works & Handover', 'Client Inspection & Taking Over', 2, 'External Snagging & Rectification', 20, 'External / Handover', 'QA/QC + PM Team', 1.5, false, null),
  ('External Works & Handover', 'Client Inspection & Taking Over', 3, 'Client Inspection Walkthrough', 20, 'External / Handover', 'QA/QC + PM Team', 0.5, true, null),
  ('External Works & Handover', 'Client Inspection & Taking Over', 4, 'Touch-up & Final Cleaning', 15, 'External / Handover', 'QA/QC + PM Team', 1, false, null),
  ('External Works & Handover', 'Client Inspection & Taking Over', 5, 'Documentation & Taking Over Certificate', 20, 'External / Handover', 'QA/QC + PM Team', 0.5, true, null),
  ('Structure & Early Works', 'Pile Cap', 1, 'Setting Out & Excavation', 10, 'Structural', 'Civil / Survey Crew', 1, false, null),
  ('Structure & Early Works', 'Pile Cap', 2, 'Blinding Concrete', 10, 'Structural', 'Concrete Crew', 1.5, false, null),
  ('Structure & Early Works', 'Pile Cap', 3, 'Reinforcement Fixing', 25, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Pile Cap', 4, 'Formwork Installation', 20, 'Structural', 'Formwork Crew', 2, false, null),
  ('Structure & Early Works', 'Pile Cap', 5, 'Concrete Pouring', 20, 'Structural', 'Concrete Crew', 1, true, null),
  ('Structure & Early Works', 'Pile Cap', 6, 'Curing & Formwork Removal', 10, 'Structural', 'Formwork Crew', 3, false, null),
  ('Structure & Early Works', 'Pile Cap', 7, 'Inspection & Handover', 5, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Ground Beam', 1, 'Setting Out & Excavation', 10, 'Structural', 'Civil / Survey Crew', 1, false, null),
  ('Structure & Early Works', 'Ground Beam', 2, 'Blinding (if required)', 5, 'Structural', 'Civil / Survey Crew', 1.5, false, null),
  ('Structure & Early Works', 'Ground Beam', 3, 'Reinforcement Fixing', 25, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Ground Beam', 4, 'Formwork Installation', 20, 'Structural', 'Formwork Crew', 2, false, null),
  ('Structure & Early Works', 'Ground Beam', 5, 'Concrete Pouring', 20, 'Structural', 'Concrete Crew', 1, true, null),
  ('Structure & Early Works', 'Ground Beam', 6, 'Curing & Formwork Removal', 15, 'Structural', 'Formwork Crew', 3, false, null),
  ('Structure & Early Works', 'Ground Beam', 7, 'Inspection', 5, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Columns', 1, 'Setting Out & Starter Bars Check', 10, 'Structural', 'Rebar Crew', 1, false, null),
  ('Structure & Early Works', 'Columns', 2, 'Reinforcement Fixing', 25, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Columns', 3, 'Formwork Installation', 25, 'Structural', 'Formwork Crew', 2, false, null),
  ('Structure & Early Works', 'Columns', 4, 'Concrete Pouring', 20, 'Structural', 'Concrete Crew', 1, true, null),
  ('Structure & Early Works', 'Columns', 5, 'Curing', 10, 'Structural', 'Concrete Crew', 3, false, null),
  ('Structure & Early Works', 'Columns', 6, 'Formwork Removal & Inspection', 10, 'Structural', 'Formwork Crew', 0.5, true, null),
  ('Structure & Early Works', 'Shear Wall / Core Wall', 1, 'Setting Out & Starter Bars', 10, 'Structural', 'Rebar Crew', 1, false, null),
  ('Structure & Early Works', 'Shear Wall / Core Wall', 2, 'Reinforcement Fixing', 25, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Shear Wall / Core Wall', 3, 'Formwork / Jump Form Installation', 25, 'Structural', 'Formwork Crew', 2, false, null),
  ('Structure & Early Works', 'Shear Wall / Core Wall', 4, 'Concrete Pouring', 20, 'Structural', 'Concrete Crew', 1, true, null),
  ('Structure & Early Works', 'Shear Wall / Core Wall', 5, 'Curing', 10, 'Structural', 'Concrete Crew', 3, false, null),
  ('Structure & Early Works', 'Shear Wall / Core Wall', 6, 'Formwork Removal & Inspection', 10, 'Structural', 'Formwork Crew', 0.5, true, null),
  ('Structure & Early Works', 'Beams', 1, 'Setting Out & Level Check', 10, 'Structural', 'Civil / Survey Crew', 1, false, null),
  ('Structure & Early Works', 'Beams', 2, 'Formwork Installation', 25, 'Structural', 'Formwork Crew', 2, false, null),
  ('Structure & Early Works', 'Beams', 3, 'Reinforcement Fixing', 25, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Beams', 4, 'MEP Embedded Items / Sleeves', 10, 'Structural', 'Structural Crew', 1.5, false, null),
  ('Structure & Early Works', 'Beams', 5, 'Concrete Pouring', 15, 'Structural', 'Concrete Crew', 1, true, null),
  ('Structure & Early Works', 'Beams', 6, 'Curing & Formwork Removal', 10, 'Structural', 'Formwork Crew', 3, false, null),
  ('Structure & Early Works', 'Beams', 7, 'Inspection', 5, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Slab', 1, 'Setting Out & Level Check', 10, 'Structural', 'Civil / Survey Crew', 1, false, null),
  ('Structure & Early Works', 'Slab', 2, 'Formwork / Table Form Installation', 20, 'Structural', 'Formwork Crew', 2, false, null),
  ('Structure & Early Works', 'Slab', 3, 'Bottom Reinforcement', 15, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Slab', 4, 'MEP Embedded Items / Sleeves / Conduits', 15, 'Structural', 'Structural Crew', 1.5, false, null),
  ('Structure & Early Works', 'Slab', 5, 'Top Reinforcement', 15, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Slab', 6, 'Concrete Pouring', 15, 'Structural', 'Concrete Crew', 1, true, null),
  ('Structure & Early Works', 'Slab', 7, 'Curing & Formwork Removal', 10, 'Structural', 'Formwork Crew', 3, false, null),
  ('Structure & Early Works', 'Staircase', 1, 'Setting Out & Level Check', 10, 'Structural', 'Civil / Survey Crew', 1, false, null),
  ('Structure & Early Works', 'Staircase', 2, 'Formwork Installation', 25, 'Structural', 'Formwork Crew', 2, false, null),
  ('Structure & Early Works', 'Staircase', 3, 'Reinforcement Fixing', 25, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Staircase', 4, 'Concrete Pouring', 20, 'Structural', 'Concrete Crew', 1, true, null),
  ('Structure & Early Works', 'Staircase', 5, 'Curing & Formwork Removal', 15, 'Structural', 'Formwork Crew', 3, false, null),
  ('Structure & Early Works', 'Staircase', 6, 'Inspection', 5, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Ramp', 1, 'Setting Out & Gradient Check', 15, 'Structural', 'Civil / Survey Crew', 1, false, null),
  ('Structure & Early Works', 'Ramp', 2, 'Formwork Installation', 20, 'Structural', 'Formwork Crew', 2, false, null),
  ('Structure & Early Works', 'Ramp', 3, 'Reinforcement Fixing', 25, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Ramp', 4, 'Concrete Pouring', 20, 'Structural', 'Concrete Crew', 1, true, null),
  ('Structure & Early Works', 'Ramp', 5, 'Curing, Surface Finish & Formwork Removal', 15, 'Structural', 'Formwork Crew', 3, false, null),
  ('Structure & Early Works', 'Ramp', 6, 'Inspection', 5, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Retaining Wall', 1, 'Setting Out & Excavation', 10, 'Structural', 'Civil / Survey Crew', 1, false, null),
  ('Structure & Early Works', 'Retaining Wall', 2, 'Blinding / Base Preparation', 10, 'Structural', 'Civil / Survey Crew', 1, false, null),
  ('Structure & Early Works', 'Retaining Wall', 3, 'Reinforcement Fixing', 25, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Retaining Wall', 4, 'Formwork Installation', 20, 'Structural', 'Formwork Crew', 2, false, null),
  ('Structure & Early Works', 'Retaining Wall', 5, 'Concrete Pouring (in lifts if high)', 20, 'Structural', 'Concrete Crew', 1, true, null),
  ('Structure & Early Works', 'Retaining Wall', 6, 'Curing, Formwork Removal & Backfill Prep', 10, 'Structural', 'Formwork Crew', 3, false, null),
  ('Structure & Early Works', 'Retaining Wall', 7, 'Inspection', 5, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Diaphragm Wall', 1, 'Guide Wall Construction', 15, 'Structural', 'Piling Crew', 1.5, false, null),
  ('Structure & Early Works', 'Diaphragm Wall', 2, 'Trench Excavation under Bentonite', 25, 'Structural', 'Civil / Survey Crew', 1.5, false, null),
  ('Structure & Early Works', 'Diaphragm Wall', 3, 'Reinforcement Cage Installation', 20, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Diaphragm Wall', 4, 'Concrete Pouring (Tremie)', 25, 'Structural', 'Concrete Crew', 1, true, null),
  ('Structure & Early Works', 'Diaphragm Wall', 5, 'Panel Joint Cleaning & Inspection', 10, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Diaphragm Wall', 6, 'As-built & Integrity Check', 5, 'Structural', 'Piling Crew', 0.5, true, null),
  ('Structure & Early Works', 'CBP / Secant Pile Wall', 1, 'Setting Out & Guide Wall (if any)', 10, 'Structural', 'Civil / Survey Crew', 1, false, null),
  ('Structure & Early Works', 'CBP / Secant Pile Wall', 2, 'Bored Pile Installation (Primary)', 30, 'Structural', 'Piling Crew', 2, false, null),
  ('Structure & Early Works', 'CBP / Secant Pile Wall', 3, 'Bored Pile Installation (Secondary / Secant)', 25, 'Structural', 'Piling Crew', 2, false, null),
  ('Structure & Early Works', 'CBP / Secant Pile Wall', 4, 'Pile Head Breaking & Capping Beam', 20, 'Structural', 'Piling Crew', 1.5, false, null),
  ('Structure & Early Works', 'CBP / Secant Pile Wall', 5, 'Testing & Integrity Check', 10, 'Structural', 'Piling Crew', 1, true, null),
  ('Structure & Early Works', 'CBP / Secant Pile Wall', 6, 'Inspection & Handover', 5, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null),
  ('Structure & Early Works', 'Slab on Grade / Ground Slab', 1, 'Subgrade Preparation & Compaction', 15, 'Structural', 'Structural Crew', 1, false, null),
  ('Structure & Early Works', 'Slab on Grade / Ground Slab', 2, 'Blinding / Vapour Barrier', 10, 'Structural', 'Civil / Survey Crew', 1.5, false, null),
  ('Structure & Early Works', 'Slab on Grade / Ground Slab', 3, 'Reinforcement / Mesh Fixing', 25, 'Structural', 'Rebar Crew', 2, false, null),
  ('Structure & Early Works', 'Slab on Grade / Ground Slab', 4, 'Formwork / Edge Form', 10, 'Structural', 'Formwork Crew', 1.5, false, null),
  ('Structure & Early Works', 'Slab on Grade / Ground Slab', 5, 'Concrete Pouring & Finishing', 25, 'Structural', 'Concrete Crew', 1, true, null),
  ('Structure & Early Works', 'Slab on Grade / Ground Slab', 6, 'Curing & Joint Cutting', 10, 'Structural', 'Concrete Crew', 3, false, null),
  ('Structure & Early Works', 'Slab on Grade / Ground Slab', 7, 'Inspection', 5, 'Structural', 'QA/QC + Structural Engineer', 0.5, true, null)

) as v(group_name, template_name, step_no, step_name, weight, discipline, resource_crew, est_duration_days, inspection_hold_point, notes)
join public.activity_step_template_master t
  on t.group_name = v.group_name and t.template_name = v.template_name
on conflict (template_id, step_no) do update set
  step_name = excluded.step_name,
  weight = excluded.weight,
  discipline = excluded.discipline,
  resource_crew = excluded.resource_crew,
  est_duration_days = excluded.est_duration_days,
  inspection_hold_point = excluded.inspection_hold_point,
  notes = excluded.notes;