// Data access for the procurement module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── budget_code_groups ────────────────────────────────────────────────────────

// @table budget_code_groups
export function getBudgetCodeGroupByCodeLetter(codeLetter: string | number | boolean) {
  return db().from("budget_code_groups").select("name").eq("code_letter", codeLetter).single();
}

// @table budget_code_groups
export function listBudgetCodeGroups() {
  return db().from("budget_code_groups").select("code_letter, name").order("sort_order");
}

// ── budget_codes ──────────────────────────────────────────────────────────────

// @table budget_codes
export function listBudgetCodesByIds(ids: readonly (string | number)[]) {
  return db().from("budget_codes").select("id, code_letter").in("id", ids);
}

// ── inv_items ─────────────────────────────────────────────────────────────────

// @table inv_items
export function listReorderableInvItems() {
  return db()
    .from("inv_items")
    .select("id, item_code, name, unit_of_measure, min_stock_level, reorder_quantity, inv_stock(quantity_available, unit_cost_fifo, store_id)")
    .eq("is_active", true)
    .not("min_stock_level", "is", null)
    .order("item_code");
}

// ── procurement_audit_log ─────────────────────────────────────────────────────

// @table procurement_audit_log
export function listAuditLog() {
  return db().from("procurement_audit_log").select("*").order("changed_at", { ascending: false }).limit(100);
}

// ── procurement_budget_confirmation_items ─────────────────────────────────────

// @table procurement_budget_confirmation_items
export function insertBudgetConfirmationItems(rows: object[]) {
  return db().from("procurement_budget_confirmation_items").insert(rows);
}

// @table procurement_budget_confirmation_items
export function listBudgetConfirmationItemsByBcId(bcId: string | number | boolean) {
  return db().from("procurement_budget_confirmation_items").select("*").eq("bc_id", bcId).order("line_no");
}

// ── procurement_budget_confirmations ──────────────────────────────────────────

// @table procurement_budget_confirmations
export function getBudgetConfirmationById(id: string | number | boolean) {
  return db()
    .from("procurement_budget_confirmations")
    .select("id, bc_number, budget_status")
    .eq("id", id)
    .single();
}

// @table procurement_budget_confirmations
export function getBudgetConfirmationByPrId(prId: string | number | boolean) {
  return db().from("procurement_budget_confirmations").select("*").eq("pr_id", prId).single();
}

// @table procurement_budget_confirmations
export function insertBudgetConfirmation(row: object) {
  return db().from("procurement_budget_confirmations").insert([row]).select("id").single();
}

// @table procurement_budget_confirmations
export function listBudgetConfirmationsByProjectId(projectId: string | number | boolean) {
  return db().from("procurement_budget_confirmations").select("bc_number").eq("project_id", projectId);
}

// ── procurement_delivery_notes ────────────────────────────────────────────────

// @table procurement_delivery_notes
export function countDeliveriesInTransit() {
  return db()
    .from("procurement_delivery_notes")
    .select("id", { count: "exact", head: true })
    .eq("status", "in_transit");
}

// @table procurement_delivery_notes
export function insertDeliveryNote(row: object) {
  return db().from("procurement_delivery_notes").insert([row]).select("id").single();
}

// @table procurement_delivery_notes
export function listDeliveryNoteColumns(columns: string) {
  return db().from("procurement_delivery_notes").select(columns as "*");
}

// @table procurement_delivery_notes
export function listDeliveryNotes() {
  return db()
    .from("procurement_delivery_notes")
    .select("*, procurement_pos!procurement_delivery_notes_po_id_fkey(po_number)")
    .order("created_at", { ascending: false });
}

// ── procurement_goods_receipts ────────────────────────────────────────────────

// @table procurement_goods_receipts
export function insertGoodsReceipt(row: object) {
  return db().from("procurement_goods_receipts").insert([row]);
}

// @table procurement_goods_receipts
export function insertGoodsReceipts(rows: object[]) {
  return db().from("procurement_goods_receipts").insert(rows);
}

// @table procurement_goods_receipts
export function listGoodsReceipts() {
  return db()
    .from("procurement_goods_receipts")
    .select("quantity_accepted, quantity_rejected, procurement_po_items!inner(po_id, procurement_pos!inner(supplier_id))");
}

// @table procurement_goods_receipts
export function listGoodsReceiptsByPoId(poId: string | number | boolean) {
  return db()
    .from("procurement_goods_receipts")
    .select("quantity_accepted, procurement_po_items!inner(unit_price)")
    .eq("procurement_po_items.po_id", poId);
}

// ── procurement_invoice_matches ───────────────────────────────────────────────

// @table procurement_invoice_matches
export function getInvoiceMatchById(id: string | number | boolean) {
  return db().from("procurement_invoice_matches").select("*").eq("id", id).single();
}

// @table procurement_invoice_matches
export function insertInvoiceMatch(row: object) {
  return db().from("procurement_invoice_matches").insert([row]).select("id").single();
}

// @table procurement_invoice_matches
export function listInvoiceMatches() {
  return db()
    .from("procurement_invoice_matches")
    .select("*, procurement_pos(po_number), procurement_suppliers(supplier_name)")
    .order("created_at", { ascending: false });
}

// @table procurement_invoice_matches
export function updateInvoiceMatchById(patch: object, id: string | number | boolean) {
  return db().from("procurement_invoice_matches").update(patch).eq("id", id);
}

// ── procurement_notifications ─────────────────────────────────────────────────

// @table procurement_notifications
export function listNotifications() {
  return db()
    .from("procurement_notifications")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(50);
}

// @table procurement_notifications
export function updateNotificationById(patch: object, id: string | number | boolean) {
  return db().from("procurement_notifications").update(patch).eq("id", id);
}

// @table procurement_notifications
export function updateNotificationsByIds(patch: object, ids: readonly (string | number)[]) {
  return db().from("procurement_notifications").update(patch).in("id", ids);
}

// ── procurement_po_items ──────────────────────────────────────────────────────

// @table procurement_po_items
export function insertPoItems(rows: object[]) {
  return db().from("procurement_po_items").insert(rows);
}

// @table procurement_po_items
export function listPoItemsByPoId(poId: string | number | boolean, columns: string) {
  return db().from("procurement_po_items").select(columns as "*").eq("po_id", poId).order("line_no");
}

// @table procurement_po_items
export function updatePoItemById(patch: object, id: string | number | boolean) {
  return db().from("procurement_po_items").update(patch).eq("id", id);
}

// ── procurement_po_revisions ──────────────────────────────────────────────────

// @table procurement_po_revisions
export function insertPoRevision(row: object) {
  return db().from("procurement_po_revisions").insert([row]);
}

// @table procurement_po_revisions
export function listPoRevisionsByPoId(poId: string | number | boolean) {
  return db()
    .from("procurement_po_revisions")
    .select("id, rev_no, description, rev_date")
    .eq("po_id", poId)
    .order("rev_no");
}

// ── procurement_pos ───────────────────────────────────────────────────────────

// @table procurement_pos
export function countPosInApproval() {
  return db()
    .from("procurement_pos")
    .select("id", { count: "exact", head: true })
    .in("status", ["submitted", "approved"]);
}

// @table procurement_pos
export function getPoById(id: string | number | boolean) {
  return db().from("procurement_pos").select("*").eq("id", id).single();
}

// @table procurement_pos
export function getPoByQuotationId(quotationId: string | number | boolean) {
  return db().from("procurement_pos").select("id").eq("quotation_id", quotationId).single();
}

// @table procurement_pos
export function insertPo(row: object) {
  return db().from("procurement_pos").insert([row]).select("id").single();
}

// @table procurement_pos
export function listPos(columns: string) {
  return db().from("procurement_pos").select(columns as "*");
}

// @table procurement_pos
export function listPosAwaitingDelivery() {
  return db()
    .from("procurement_pos")
    .select(`id, po_number, supplier_id, procurement_po_items(id, item_type, item_code, item_description, unit, quantity_ordered, quantity_delivered, unit_price)`)
    .in("status", ["issued", "partially_delivered"])
    .order("created_at", { ascending: false });
}

// @table procurement_pos
export function listPosAwaitingDeliveryBySupplierId(supplierId: string | number | boolean) {
  return db()
    .from("procurement_pos")
    .select("id, po_number, delivery_date_expected")
    .eq("supplier_id", supplierId)
    .in("status", ["issued", "partially_delivered"])
    .order("created_at", { ascending: false });
}

// @table procurement_pos
export function listPosByProjectId(projectId: string | number | boolean) {
  return db().from("procurement_pos").select("po_number").eq("project_id", projectId);
}

// @table procurement_pos
export function listPosBySupplierId(supplierId: string | number | boolean) {
  return db()
    .from("procurement_pos")
    .select("*")
    .eq("supplier_id", supplierId)
    .order("created_at", { ascending: false });
}

// @table procurement_pos
export function listPosNewestFirst() {
  return db().from("procurement_pos").select("*").order("created_at", { ascending: false });
}

// @table procurement_pos
export function listPosReadyForInvoiceMatch() {
  return db()
    .from("procurement_pos")
    .select("id, po_number, supplier_id, total_amount, grand_total, status")
    .in("status", ["delivered", "partially_delivered", "under_invoice_match", "closed"])
    .order("created_at", { ascending: false });
}

// @table procurement_pos
export function updatePoById(patch: object, id: string | number | boolean) {
  return db().from("procurement_pos").update(patch).eq("id", id);
}

// @table procurement_pos
export function updatePosByIds(patch: object, ids: readonly (string | number)[]) {
  return db().from("procurement_pos").update(patch).in("id", ids);
}

// ── procurement_pr_items ──────────────────────────────────────────────────────

// @table procurement_pr_items
export function deletePrItemsByPrId(prId: string | number | boolean) {
  return db().from("procurement_pr_items").delete().eq("pr_id", prId);
}

// @table procurement_pr_items
export function insertPrItem(row: object) {
  return db().from("procurement_pr_items").insert([row]);
}

// @table procurement_pr_items
export function insertPrItems(rows: object[]) {
  return db().from("procurement_pr_items").insert(rows);
}

// @table procurement_pr_items
export function listPrItemsByPrId(prId: string | number | boolean, columns: string) {
  return db().from("procurement_pr_items").select(columns as "*").eq("pr_id", prId).order("line_no");
}

// ── procurement_prs ───────────────────────────────────────────────────────────

// @table procurement_prs
export function countPrsAwaitingApproval() {
  return db()
    .from("procurement_prs")
    .select("id", { count: "exact", head: true })
    .in("approval_status", ["submitted", "under_budget_review"]);
}

// @table procurement_prs
export function deletePrById(id: string | number | boolean) {
  return db().from("procurement_prs").delete().eq("id", id);
}

// @table procurement_prs
export function getPrById(id: string | number | boolean, columns: string) {
  return db().from("procurement_prs").select(columns as "*").eq("id", id).single();
}

// @table procurement_prs
export function insertPr(row: object) {
  return db().from("procurement_prs").insert([row]).select("id").single();
}

// @table procurement_prs
export function listApprovedPrs() {
  return db()
    .from("procurement_prs")
    .select("id, pr_number")
    .in("approval_status", ["approved", "closed"])
    .order("created_at", { ascending: false });
}

// @table procurement_prs
export function listApprovedPrsByProjectId(projectId: string | number | boolean) {
  return db()
    .from("procurement_prs")
    .select("id, pr_number")
    .eq("project_id", projectId)
    .in("approval_status", ["approved", "closed"])
    .order("created_at", { ascending: false });
}

// @table procurement_prs
export function listPrApprovalStatuses() {
  return db().from("procurement_prs").select("approval_status");
}

// @table procurement_prs
export function listPrs() {
  return db().from("procurement_prs").select("*").order("created_at", { ascending: false });
}

// @table procurement_prs
export function listPrsByProjectId(projectId: string | number | boolean) {
  return db().from("procurement_prs").select("pr_number").eq("project_id", projectId);
}

// @table procurement_prs
export function updatePrById(patch: object, id: string | number | boolean) {
  return db().from("procurement_prs").update(patch).eq("id", id);
}

// @table procurement_prs
export function updatePrsByIds(patch: object, ids: readonly (string | number)[]) {
  return db().from("procurement_prs").update(patch).in("id", ids);
}

// ── procurement_quotation_items ───────────────────────────────────────────────

// @table procurement_quotation_items
export function insertQuotationItems(rows: object[]) {
  return db().from("procurement_quotation_items").insert(rows);
}

// ── procurement_quotations ────────────────────────────────────────────────────

// @table procurement_quotations
export function insertQuotation(row: object) {
  return db().from("procurement_quotations").insert([row]).select("id").single();
}

// @table procurement_quotations
export function listQuotationsByRfqId(rfqId: string | number | boolean) {
  return db()
    .from("procurement_quotations")
    .select("*, procurement_quotation_items(*), procurement_suppliers(supplier_name)")
    .eq("rfq_id", rfqId);
}

// @table procurement_quotations
export function updateOtherQuotationsOfRfq(patch: object, id: string | number | boolean, rfqId: string | number | boolean) {
  return db().from("procurement_quotations").update(patch).neq("id", id).eq("rfq_id", rfqId);
}

// @table procurement_quotations
export function updateQuotationById(patch: object, id: string | number | boolean) {
  return db().from("procurement_quotations").update(patch).eq("id", id);
}

// ── procurement_rfq_suppliers ─────────────────────────────────────────────────

// @table procurement_rfq_suppliers
export function insertRfqSuppliers(rows: object[]) {
  return db().from("procurement_rfq_suppliers").insert(rows);
}

// @table procurement_rfq_suppliers
export function listRfqSuppliers() {
  return db()
    .from("procurement_rfq_suppliers")
    .select("supplier_id, responded, procurement_rfqs!inner(status)");
}

// @table procurement_rfq_suppliers
export function listRfqSuppliersByRfqId(rfqId: string | number | boolean) {
  return db()
    .from("procurement_rfq_suppliers")
    .select("*, procurement_suppliers(supplier_name)")
    .eq("rfq_id", rfqId);
}

// @table procurement_rfq_suppliers
export function listRfqSuppliersBySupplierId(supplierId: string | number | boolean) {
  return db()
    .from("procurement_rfq_suppliers")
    .select("*, procurement_rfqs(rfq_number, issue_date, response_deadline, status)")
    .eq("supplier_id", supplierId)
    .order("invited_at", { ascending: false });
}

// @table procurement_rfq_suppliers
export function updateRfqSuppliersByRfqIdAndSupplierId(patch: object, rfqId: string | number | boolean, supplierId: string | number | boolean) {
  return db()
    .from("procurement_rfq_suppliers")
    .update(patch)
    .eq("rfq_id", rfqId)
    .eq("supplier_id", supplierId);
}

// ── procurement_rfqs ──────────────────────────────────────────────────────────

// @table procurement_rfqs
export function getRfqById(id: string | number | boolean, columns: string) {
  return db().from("procurement_rfqs").select(columns as "*").eq("id", id).single();
}

// @table procurement_rfqs
export function insertRfq(row: object) {
  return db().from("procurement_rfqs").insert([row]).select("id").single();
}

// @table procurement_rfqs
export function listRfqs() {
  return db()
    .from("procurement_rfqs")
    .select("*, procurement_prs(pr_number)")
    .order("created_at", { ascending: false });
}

// @table procurement_rfqs
export function updateRfqById(patch: object, id: string | number | boolean) {
  return db().from("procurement_rfqs").update(patch).eq("id", id);
}

// ── procurement_suppliers ─────────────────────────────────────────────────────

// @table procurement_suppliers
export function countApprovedSuppliersExpiringBy(pqExpiresAt: string | number | boolean) {
  return db()
    .from("procurement_suppliers")
    .select("id", { count: "exact", head: true })
    .eq("pq_status", "approved")
    .lte("pq_expires_at", pqExpiresAt);
}

// @table procurement_suppliers
export function countSuppliers() {
  return db().from("procurement_suppliers").select("id", { count: "exact", head: true });
}

// @table procurement_suppliers
export function deleteSupplierById(id: string | number | boolean) {
  return db().from("procurement_suppliers").delete().eq("id", id);
}

// @table procurement_suppliers
export function insertSupplier(row: object) {
  return db().from("procurement_suppliers").insert([row]);
}

// @table procurement_suppliers
export function listActiveSuppliers(columns: string) {
  return db()
    .from("procurement_suppliers")
    .select(columns as "*")
    .eq("status", "active")
    .order("supplier_name");
}

// @table procurement_suppliers
export function listActiveSuppliersUnordered(columns: string) {
  return db().from("procurement_suppliers").select(columns as "*").eq("status", "active");
}

// @table procurement_suppliers
export function listSuppliers() {
  return db().from("procurement_suppliers").select("id, supplier_name");
}

// @table procurement_suppliers
export function listSuppliersByName() {
  return db().from("procurement_suppliers").select("*").order("supplier_name");
}

// @table procurement_suppliers
export function updateSupplierById(patch: object, id: string | number | boolean) {
  return db().from("procurement_suppliers").update(patch).eq("id", id);
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function getProfileById(id: string | number | boolean) {
  return db().from("profiles").select("full_name").eq("id", id).single();
}

// @table profiles
export function listProfilesByIds(ids: readonly (string | number)[]) {
  return db().from("profiles").select("id, full_name").in("id", ids);
}

// ── projects ──────────────────────────────────────────────────────────────────

// @table projects
export function getProjectById(id: string | number | boolean, columns: string) {
  return db().from("projects").select(columns as "*").eq("id", id).single();
}

// @table projects
export function listProjectsByIds(ids: readonly (string | number)[]) {
  return db().from("projects").select("id, project_code, project_name").in("id", ids);
}

// ── qs_boq_items ──────────────────────────────────────────────────────────────

// @table qs_boq_items
export function deleteQsBoqItemById(id: string | number | boolean) {
  return db().from("qs_boq_items").delete().eq("id", id);
}

// @table qs_boq_items
export function insertQsBoqItem(row: object) {
  return db().from("qs_boq_items").insert([row]).select().single();
}

// @table qs_boq_items
export function listQsBoqItemsByIds(ids: readonly (string | number)[]) {
  return db().from("qs_boq_items").select("id, budget_code_id, total_amount, baseline_status").in("id", ids);
}

// @table qs_boq_items
export function listQsBoqItemsByProjectId(projectId: string | number | boolean) {
  return db().from("qs_boq_items").select("*").eq("project_id", projectId).order("seq");
}

// @table qs_boq_items
export function updateQsBoqItemById(patch: object, id: string | number | boolean) {
  return db().from("qs_boq_items").update(patch).eq("id", id).select().single();
}

// ── qs_boq_sections ───────────────────────────────────────────────────────────

// @table qs_boq_sections
export function deleteQsBoqSectionById(id: string | number | boolean) {
  return db().from("qs_boq_sections").delete().eq("id", id);
}

// @table qs_boq_sections
export function insertQsBoqSection(row: object) {
  return db().from("qs_boq_sections").insert([row]).select().single();
}

// @table qs_boq_sections
export function listQsBoqSectionsByProjectId(projectId: string | number | boolean, columns: string) {
  return db().from("qs_boq_sections").select(columns as "*").eq("project_id", projectId).order("seq");
}

// @table qs_boq_sections
export function updateQsBoqSectionById(patch: object, id: string | number | boolean) {
  return db().from("qs_boq_sections").update(patch).eq("id", id).select().single();
}

// ── qs_v_boq_requisition_status ───────────────────────────────────────────────

// @table qs_v_boq_requisition_status
export function listBoqRequisitionStatusByBoqItemIds(boqItemIds: readonly (string | number)[]) {
  return db().from("qs_v_boq_requisition_status").select("*").in("boq_item_id", boqItemIds);
}

// @table qs_v_boq_requisition_status
export function listOpenBoqRequisitionStatusByProjectId(projectId: string | number | boolean) {
  return db()
    .from("qs_v_boq_requisition_status")
    .select("*")
    .eq("project_id", projectId)
    .gt("remaining_quantity", 0)
    .order("seq");
}
