// Data access for the projects-queries.ts module. Every query and write its screens make
// goes through here; components do not call the database directly.
//
// Each function returns the Supabase query itself, so callers await it (or call
// .then) and read `{ data, error }` as usual. Functions are grouped by table.
//
// Generated by scripts/codemods/extract-service.mjs and then maintained by hand.
// Keep the "// @table" markers: the codemod reads them when it is run again.

import { createClient } from "@/lib/supabase/client";

const db = () => createClient();

// ── contract_register ─────────────────────────────────────────────────────────

// @table contract_register
export function getContractRegisterByProjectIdWithStatusActiveDraft(projectId: string | number | boolean) {
  return db()
    .from("contract_register")
    .select("*")
    .eq("project_id", projectId)
    .in("status", ["active", "draft"])
    .order("status")
    .limit(1)
    .maybeSingle();
}

// @table contract_register
export function insertContractRegister(row: object) {
  return db().from("contract_register").insert([row]);
}

// ── profiles ──────────────────────────────────────────────────────────────────

// @table profiles
export function listProfiles() {
  return db().from("profiles").select("id, full_name").order("full_name");
}

// @table profiles
export function listProfilesOfIdAndFullName(columns: string) {
  return db().from("profiles").select(columns as "*");
}

// @table profiles
export function listProfilesOrderedByFullName() {
  return db().from("profiles").select("id, full_name, employee_id").order("full_name", { ascending: true });
}

// ── project_activation_log ────────────────────────────────────────────────────

// @table project_activation_log
export function upsertProjectActivationLog(row: object) {
  return db().from("project_activation_log").upsert([row], { onConflict: "project_id" });
}

// ── project_precontract_details ───────────────────────────────────────────────

// @table project_precontract_details
export function getProjectPrecontractDetailByProjectId(projectId: string | number | boolean, columns: string) {
  return db()
    .from("project_precontract_details")
    .select(columns as "*")
    .eq("project_id", projectId)
    .maybeSingle();
}

// @table project_precontract_details
export function updateProjectPrecontractDetailsByProjectId(patch: object, projectId: string | number | boolean) {
  return db().from("project_precontract_details").update(patch).eq("project_id", projectId);
}

// @table project_precontract_details
export function upsertProjectPrecontractDetails(rows: object | object[]) {
  return db().from("project_precontract_details").upsert(rows, { onConflict: "project_id" });
}

// ── project_stakeholder_mappings ──────────────────────────────────────────────

// @table project_stakeholder_mappings
export function deleteProjectStakeholderMappingsByProjectId(projectId: string | number | boolean) {
  return db().from("project_stakeholder_mappings").delete().eq("project_id", projectId);
}

// @table project_stakeholder_mappings
export function insertProjectStakeholderMapping(row: object) {
  return db().from("project_stakeholder_mappings").insert([row]);
}

// @table project_stakeholder_mappings
export function listProjectStakeholderMappingsByProjectId(projectId: string | number | boolean, columns: string) {
  return db().from("project_stakeholder_mappings").select(columns as "*").eq("project_id", projectId);
}

// ── project_stakeholder_teams ─────────────────────────────────────────────────

// @table project_stakeholder_teams
export function deleteProjectStakeholderTeamsByProjectId(projectId: string | number | boolean) {
  return db().from("project_stakeholder_teams").delete().eq("project_id", projectId);
}

// @table project_stakeholder_teams
export function insertProjectStakeholderTeamReturning(row: object) {
  return db().from("project_stakeholder_teams").insert([row]).select().single();
}

// @table project_stakeholder_teams
export function insertProjectStakeholderTeamsReturning(rows: object | object[]) {
  return db().from("project_stakeholder_teams").insert(rows).select().single();
}

// @table project_stakeholder_teams
export function listProjectStakeholderTeamsByProjectId(projectId: string | number | boolean, columns: string) {
  return db().from("project_stakeholder_teams").select(columns as "*").eq("project_id", projectId);
}

// ── project_stakeholders ──────────────────────────────────────────────────────

// @table project_stakeholders
export function deleteProjectStakeholdersByProjectId(projectId: string | number | boolean) {
  return db().from("project_stakeholders").delete().eq("project_id", projectId);
}

// @table project_stakeholders
export function insertProjectStakeholder(row: object) {
  return db().from("project_stakeholders").insert([row]);
}

// @table project_stakeholders
export function listProjectStakeholdersByProjectId(projectId: string | number | boolean, columns: string) {
  return db().from("project_stakeholders").select(columns as "*").eq("project_id", projectId);
}

// ── project_team_members ──────────────────────────────────────────────────────

// @table project_team_members
export function deleteProjectTeamMemberById(id: string | number | boolean) {
  return db().from("project_team_members").delete().eq("id", id);
}

// @table project_team_members
export function insertProjectTeamMember(row: object) {
  return db().from("project_team_members").insert([row]);
}

// @table project_team_members
export function insertProjectTeamMembers(rows: object | object[]) {
  return db().from("project_team_members").insert(rows);
}

// @table project_team_members
export function listProjectTeamMembersByProjectId(projectId: string | number | boolean) {
  return db()
    .from("project_team_members")
    .select("*, project_stakeholder_teams!inner(*)")
    .eq("project_stakeholder_teams.project_id", projectId);
}

// @table project_team_members
export function listProjectTeamMembersByProjectStakeholderTeamIds(projectStakeholderTeamIds: readonly (string | number)[], columns: string) {
  return db()
    .from("project_team_members")
    .select(columns as "*")
    .in("project_stakeholder_team_id", projectStakeholderTeamIds);
}

// ── projects ──────────────────────────────────────────────────────────────────

// @table projects
export function getProjectById(id: string | number | boolean) {
  return db().from("projects").select("*").eq("id", id).single();
}

// @table projects
export function insertProjectsReturning(rows: object | object[]) {
  return db().from("projects").insert(rows).select().single();
}

// @table projects
export function listProjects() {
  return db().from("projects").select("*").order("created_at", { ascending: false });
}

// @table projects
export function updateProjectById(patch: object, id: string | number | boolean | null) {
  return db().from("projects").update(patch).eq("id", id);
}

// @table projects
export function updateProjectByIdReturning(patch: object, id: string | number | boolean) {
  return db().from("projects").update(patch).eq("id", id).select().single();
}

// ── qs_risk_items ─────────────────────────────────────────────────────────────

// @table qs_risk_items
export function listQsRiskItemsByProjectId(projectId: string | number | boolean) {
  return db().from("qs_risk_items").select("*").eq("project_id", projectId).order("created_at");
}

// ── roles ─────────────────────────────────────────────────────────────────────

// @table roles
export function listRoles() {
  return db().from("roles").select("code, name").order("level");
}

// @table roles
export function listRolesOrderedByTypeAndLevel() {
  return db().from("roles").select("code, name, type").order("type").order("level");
}

// ── stakeholder_staff ─────────────────────────────────────────────────────────

// @table stakeholder_staff
export function listStakeholderStaffByStakeholderId(stakeholderId: string | number | boolean) {
  return db()
    .from("stakeholder_staff")
    .select("id, full_name, job_title")
    .eq("stakeholder_id", stakeholderId);
}

// @table stakeholder_staff
export function listStakeholderStaffByStakeholderIds(stakeholderIds: readonly (string | number)[]) {
  return db()
    .from("stakeholder_staff")
    .select("id, stakeholder_id, full_name, job_title")
    .in("stakeholder_id", stakeholderIds);
}

// ── stakeholder_templates ─────────────────────────────────────────────────────

// @table stakeholder_templates
export function listStakeholderTemplates() {
  return db().from("stakeholder_templates").select("id, name").order("name", { ascending: true });
}

// @table stakeholder_templates
export function listStakeholderTemplatesWithTemplatePlaceholders() {
  return db()
    .from("stakeholder_templates")
    .select("id, name, description, template_placeholders(id, label, description, sort_order)");
}

// ── stakeholders ──────────────────────────────────────────────────────────────

// @table stakeholders
export function getStakeholderById(id: string | number | boolean) {
  return db().from("stakeholders").select("organization_name").eq("id", id).maybeSingle();
}

// @table stakeholders
export function listStakeholders() {
  return db()
    .from("stakeholders")
    .select("id, organization_name, stakeholder_type")
    .order("organization_name");
}

// @table stakeholders
export function listStakeholdersByIds(ids: readonly (string | number)[]) {
  return db().from("stakeholders").select("id, organization_name").in("id", ids);
}

// @table stakeholders
export function listStakeholdersWithStatusActive() {
  return db()
    .from("stakeholders")
    .select("id, organization_name, stakeholder_type")
    .eq("status", "active")
    .order("organization_name", { ascending: true });
}

// ── template_placeholders ─────────────────────────────────────────────────────

// @table template_placeholders
export function listTemplatePlaceholdersByTemplateId(templateId: string | number | boolean) {
  return db()
    .from("template_placeholders")
    .select("*, template_placeholder_teams(*)")
    .eq("template_id", templateId)
    .order("sort_order", { ascending: true });
}

// ── tender_bid_summaries ──────────────────────────────────────────────────────

// @table tender_bid_summaries
export function countTenderBidSummariesByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_bid_summaries")
    .select("id", { count: "exact", head: true })
    .eq("tender_id", tenderId);
}

// ── tender_boq_items ──────────────────────────────────────────────────────────

// @table tender_boq_items
export function countTenderBoqItemsByTenderId(tenderId: string | number | boolean) {
  return db().from("tender_boq_items").select("id", { count: "exact", head: true }).eq("tender_id", tenderId);
}

// ── tender_clarifications ─────────────────────────────────────────────────────

// @table tender_clarifications
export function deleteTenderClarificationById(id: string | number | boolean) {
  return db().from("tender_clarifications").delete().eq("id", id);
}

// @table tender_clarifications
export function insertTenderClarification(row: object) {
  return db().from("tender_clarifications").insert([row]);
}

// @table tender_clarifications
export function listTenderClarificationsByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_clarifications")
    .select("*")
    .eq("tender_id", tenderId)
    .order("raised_date", { ascending: false })
    .order("query_no", { ascending: false });
}

// @table tender_clarifications
export function updateTenderClarificationById(patch: object, id: string | number | boolean) {
  return db().from("tender_clarifications").update(patch).eq("id", id);
}

// ── tender_commercial_items ───────────────────────────────────────────────────

// @table tender_commercial_items
export function listTenderCommercialItemsByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_commercial_items")
    .select("topic, client_requirement, assessment, qualification")
    .eq("tender_id", tenderId)
    .order("sort_order");
}

// ── tender_preliminaries_items ────────────────────────────────────────────────

// @table tender_preliminaries_items
export function countTenderPreliminariesItemsByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_preliminaries_items")
    .select("id", { count: "exact", head: true })
    .eq("tender_id", tenderId);
}

// ── tender_price_list ─────────────────────────────────────────────────────────

// @table tender_price_list
export function countTenderPriceListByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_price_list")
    .select("id", { count: "exact", head: true })
    .eq("tender_id", tenderId);
}

// ── tender_register ───────────────────────────────────────────────────────────

// @table tender_register
export function getTenderRegisterById(id: string | number | boolean, columns: string) {
  return db().from("tender_register").select(columns as "*").eq("id", id).maybeSingle();
}

// @table tender_register
export function getTenderRegisterByProjectId(projectId: string | number | boolean) {
  return db().from("tender_register").select("id").eq("project_id", projectId).maybeSingle();
}

// @table tender_register
export function getTenderRegisterByTenderNo(tenderNo: string | number | boolean) {
  return db().from("tender_register").select("id, project_id").eq("tender_no", tenderNo).maybeSingle();
}

// @table tender_register
export function insertTenderRegisterReturning(row: object) {
  return db().from("tender_register").insert([row]).select().single();
}

// @table tender_register
export function updateTenderRegisterById(patch: object, id: string | number | boolean) {
  return db().from("tender_register").update(patch).eq("id", id);
}

// ── tender_returnables ────────────────────────────────────────────────────────

// @table tender_returnables
export function deleteTenderReturnableById(id: string | number | boolean) {
  return db().from("tender_returnables").delete().eq("id", id);
}

// @table tender_returnables
export function insertTenderReturnableReturning(row: object) {
  return db().from("tender_returnables").insert([row]).select().single();
}

// @table tender_returnables
export function listTenderReturnablesByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_returnables")
    .select("*")
    .eq("tender_id", tenderId)
    .order("sort_order")
    .order("created_at");
}

// @table tender_returnables
export function updateTenderReturnableById(patch: object, id: string | number | boolean) {
  return db().from("tender_returnables").update(patch).eq("id", id);
}

// ── tender_risk_items ─────────────────────────────────────────────────────────

// @table tender_risk_items
export function countTenderRiskItemsByTenderId(tenderId: string | number | boolean) {
  return db()
    .from("tender_risk_items")
    .select("id", { count: "exact", head: true })
    .eq("tender_id", tenderId);
}

// @table tender_risk_items
export function insertTenderRiskItems(rows: object | object[]) {
  return db().from("tender_risk_items").insert(rows);
}

// ── tender_workstreams ────────────────────────────────────────────────────────

// @table tender_workstreams
export function listTenderWorkstreamsByTenderId(tenderId: string | number | boolean) {
  return db().from("tender_workstreams").select("*").eq("tender_id", tenderId).order("sort_order");
}

// @table tender_workstreams
export function updateTenderWorkstreamById(patch: object, id: string | number | boolean) {
  return db().from("tender_workstreams").update(patch).eq("id", id);
}

// ── wbs_tasks ─────────────────────────────────────────────────────────────────

// @table wbs_tasks
export function countWbsTasksByProjectId(projectId: string | number | boolean) {
  return db().from("wbs_tasks").select("id", { count: "exact", head: true }).eq("project_id", projectId);
}
